### ISSUE TITLE
Add dirty/filtered/clean water for canteens/bottles, add juices and make milk restore thirst

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#10]
When collecting water from a water source, the water will naturally be dirty.

Dirty Water can be filtered into Filtered Water with a charcoal filter, and Filtered Water can be turned into Clean Water by boiling it in a furnace.

The player can drink Dirty Water, however, it will have a very high chance of giving water poisoning, and will not restore much thirst/hydration at all.  Filtered Water will have a small chance of giving water poisoning, but Clean Water will not.  Clean Water will also restore more thirst/hydration.

Potions will not be able to be brewed with dirty or filtered water either, and will need to be purified.

---

Juices can be made from different fruits/vegetables, including:
- Apple Juice (5)
- Golden Apple Juice (16)
- Melon Juice (6)
- Pumpkin Juice (4)
- Carrot Juice (3)
- Golden Carrot Juice (14)
- Cacti Juice (7)
- Beetroot Juice (9)

Each juice will provide a different amount of thirst/hydration, and will not have any chance of giving water poisoning.

---

Milk should restore the player's thirst.  Pretty self-explanatory.

**Comment by UndeadZeratul** [comment]
What about hot and/or cold water?  Cold water would obviously come from cold/snowy biomes, but maybe hot water could come from warmer biomes, or maybe even when cooked.  Whether or not these temperatures are permanent or temporary is up to you, but they should be able to push the player's internal body temperature one way or the other for a time.

**Comment by Forstride** [comment]
That could work, although I'm still not sure how we're going to handle items changing to other items after a certain amount of time, like with food rotting.  I'm sure it's possible, targeting individual item stacks or whatever, but for food, IDK how it's going to work, unless we change stack sizes for food, which I don't want to do.
