### ISSUE TITLE
Add a temperature sensor

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#100]
Similar to daylight/season sensors, temperature sensors could be switched between checking for hot/cold temps, and provide a redstone signal depending on the extremity of the temperature (More extreme temp = Stronger signal)

**Comment by Vectrobe** [comment]
I'd suggest it would just output a standard level of 0-15 for the temperature, with an option to invert the direction of 15 being either the hottest or coldest value.

How far does the current code allow temperature values to go? If it's simply a -1.f to 1.f based around 'ice' to 'lava' then this method should be just fine.
