### ISSUE TITLE
Push current version on Github

### ISSUE THREAD

**Issue by Rawrnekton** [Glitchfiend/ToughAsNails#106]
Last version is outdated and i'like to tinker with the new one and try my best at fixing the season skipping bug (after currently 4 terms cs i should be able to do that .. right?) or at least add german localization.

Or is a simple decompiled jar sufficient for such a thing?

**Comment by Forstride** [comment]
I don't see why that needs to be done.  Just create a new workspace in eclipse or intellij or whatever if it conflicts with other mods you have in another one.  There's no reason for us to build against 1.10.2, as we have don't have any 1.10.2 stuff we need to access in the mod, and 1.9.4 mods work just fine on it.

**Comment by Rawrnekton** [comment]
Sorry i was dumb and cant read, sorry for bothering you and thanks for the quick answer!
