### ISSUE TITLE
Add air quality stat, underground gases, respirators, air filters, and ventilators

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#11]
Air quality will replace the player's breath meter if they're in a situation where the air quality is bad (Underground, near machinery, etc.).

Gases are one example of bad air quality.  Different types of gases will generate randomly underground, including:
- Blackdamp (Carbon Dioxide, suffocating)
- Firedamp (Methane, combustable)
- Whitedamp (Carbon Monoxide, deadly)
- Stinkdamp (Hydrogen Sulfide, explosive)

Gas blocks will not actually be visible, and will instead have small particle effects that appear within them randomly, making them a virtually unseen hazard, and making respirators an important item to have while exploring the underground.

Respirators can be crafted with leather, iron ingots, string, and air filters.  Air filters can be crafted with leather and charcoal filters.  Respirators will go in the player's helmet slot.

**Comment by TinkerWorX** [comment]
It would be great if this could be configured for individual biomes. Let's say I want to make all the nether act as Blackdamp, requiring a respirator to move around.

**Comment by Forstride** [comment]
If we were to make the Nether require a respirator (Which is a cool idea), we would just have it check the dimension type, rather than going by every single biome.  So, it probably won't really happen like that.

**Comment by TinkerWorX** [comment]
That sounds like a good solution. Making it customizable would be great. I could imagine a challenge pack where the overworld is made to be an oxygenless planet.

**Comment by UndeadZeratul** [comment]
Could be nice for specifically themed skyblocks, like a space station or something.

**Comment by Cat09** [comment]
It's neat to have a reference like that for the names... but damp at the end of everything makes me think swamps everywhere! perhaps it could be the german word (Dampf) or it's translation (vapour/vapor) instead?
+1 on the config thoughts, when I was reading up there I was thinking about the nether's air quality. Worx' thought would be great for space themed maps as well, though a custom config would be needed with the map I guess

**Comment by Stormwind99** [comment]
The discontinued EnviroMine mod contains a good example of an air quality feature:
https://github.com/EnviroMine/EnviroMine-1.7/wiki/Air-Quality
