### ISSUE TITLE
Combining canteens produces weird results

### ISSUE THREAD

**Issue by Ademonjh** [Glitchfiend/ToughAsNails#115]
When you combine canteens in a crafting grid you get canteens with 'interesting' values.

Example: Two 1/3 full Dirty Canteens (toughasnails:canteen:9) in a crafting grid creates a "Clean Water Canteen" (toughasnails:canteen:15) 

I believe this is due to the canteen inheriting the vanilla minecraft property of normal tools to be able to combine 2 of the same type of item create a single repaired item.

You could add:  this.setNoRepair(); to the public ItemCanteen() section of the ItemCanteen.java file.

The idea I had was to be able to combine canteens in crafting so that a player can "pour" like-water canteens together to fill them a single canteen ( a 2/3 canteen + 1/3 canteen  = Full canteen + empty canteen)
However with the properties of repairing like normal tools; this is a problem

**Comment by Adubbz** [comment]
This was fixed in https://github.com/Glitchfiend/ToughAsNails/commit/ed42f345b335d9e22c2f3a7210245ed8b1fb428b

Perhaps water pouring may be added in the future, although given how few uses canteens have to begin with I'm not sure it's really worthwhile.
