### ISSUE TITLE
Leather Armor does NOT warm you up

### ISSUE THREAD

**Issue by Scootty** [Glitchfiend/ToughAsNails#116]
It says it on the wiki, but after testing, I've found that Leather Armor does NOT warm you up, only Wool Armor. You only need 3 pieces in order to receive the full effect I believe as the thermometer did not change after the fourth was equipped so it's addition was probably insignificant.

**Comment by Rawrnekton** [comment]
As you may or may not noticed: the mod is pretty broken and i advise you to just clone this repo and do your own stuff.

To answer your question:
Use "/tan tempinfo" to get the details on what is going on with the temperatur.
Every piece of wool armor adds 1 to the "target-temp" (the temp your body will adjust itself to) and jelled armor reduces that by one.
Armor in general reduces the time to heat you up and increases the time to cool you down.
And as you noticed: wiki entries do not necessarily reflect the ingame status.

**Comment by Adubbz** [comment]
After talking to Forstride, it sounds like this is just a mistake in the wiki. He was probably tossing up whether to allow vanilla armours to change the temperature but ultimately settled on not doing so. I've corrected the entry on body temperature to reflect the current state of armour in the mod.
