### ISSUE TITLE
[Suggestion] Drinking dirty water can cause really bad consequences, not just "Thirst"

### ISSUE THREAD

**Issue by rinart73** [Glitchfiend/ToughAsNails#121]
Currently I can just walk with a single bottle and a bucket filled with water.
Sometimes dirty water causes "Thirst" debuff, but it does noting.
Maybe we need some serious debuffs that caused by drinking dirty water?

**Comment by rckymtnrfc** [comment]
Poison would make sense to me.  You get sick from drinking it and take some damage vs just being thirsty.

**Comment by scigeotech** [comment]
yeah, but there should also be a small chance of getting the wither effect, or a weaker version of it.

**Comment by rckymtnrfc** [comment]
I've never seen that.  I think perhaps it should work like zombie flesh.  While you have the Thirst effect, you get thirsty much faster....to where you are worse off, after the effect wears off, than you were before you drank.  Perhaps making the Thirst effect only happen X% of the time you drink dirty water (maybe it's already like that, I forget currently).

**Comment by WolfieWaffle** [comment]
It could use a system like Enviromine, which I really don't get why they don't, personally.  Now Enviromine did have the water quality based on the biome, which could cause some issues, but we could just make all non filtered water be worse off. This means you cant just carry a water bucket, you have to stop for a little and filter some water, or stock up on water at a home base. Combine that with some configuration options and you have a thirst system that can fit into modpacks and work on its own.

**Comment by scigeotech** [comment]
i don't think adding the thirst effect is going to discourage drinking dirty water as much as it having a faster way of hurting the player. the player should only get the thirst effect if they drink saltwater or something (which isn't in the mod).

**Comment by rinart73** [comment]
So why do you keep closing suggestions like this? I tried this mod recently again and I still have no need of filtering water. Maybe apply sometimes some of the random effects like Posion, Weakness, Slowdown?
