### ISSUE TITLE
[Suggestion] Someway prevent players from 'Thirst cheating' using the water bucket

### ISSUE THREAD

**Issue by rinart73** [Glitchfiend/ToughAsNails#124]
Currently players can just have a bottle and a bucket filled with water.
They place water in a hole in ground and just constantly drink it using the bottle. And then they collect the water back using the bucket.
Yes, they have a good chance to get the Thirst status effect, but then they'll just do this cycle again. And again.

With this little 'trick' players don't need juices or milk. This is kinda sad.

**Comment by Quizer9O8** [comment]
The Thirst debuff isn't a penalty that holds me back from doing this trick indeed.
Besides a Thirst debuff we should get another penalty debuff that will hurt you the more you drink salt water.
