### ISSUE TITLE
API for TemperatureModifier

### ISSUE THREAD

**Issue by joshiejack** [Glitchfiend/ToughAsNails#125]
Hi there. I've had many many requests to add support for your temperature system with my own seasons in my mod Harvest Festival. Is there any way currently that I'd be able to do such a thing? I Know you add your own seasons. But some people say they're using mine but would still like them to affect the temperature.

**Comment by 0Navis0** [comment]
It would be nice if there was a support for the season system too, if it doesn't already exists.

**Comment by MojoDwarf** [comment]
+1 for temp/seasons API, this would be very useful

**Comment by Adubbz** [comment]
I've just added this now. New temperature modifiers can be added with just TaN's API.
