### ISSUE TITLE
crash while loading Minecraft

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#127]
I get this crash when I try to load Minecraft, I'm not sure what causes it. http://pastebin.com/bdgKVWeX

**Comment by Forstride** [comment]
Forge likely changed stuff in a newer version, and it's not compatible.  Gonna have to just update the mod natively to 1.10.2 at some point.

**Comment by 0Navis0** [comment]
Nah it was linked to the forge id limit, but strangely the "id block limit exceeded error" didn't display in the crash report. Anyway the installation of notenoughid solved the problem. ;)
