### ISSUE TITLE
Dying carries a lot of status effects such as Hyperthermia and thirst

### ISSUE THREAD

**Issue by Siigari** [Glitchfiend/ToughAsNails#130]
So I fell in lava and died to hyperthermia. When I respawned, I still had hyperthermia status for a full 1:30, and I died again. Also, thirst status carries over from death.

I believe these things need to be fixed. Thanks!

**Comment by Forstride** [comment]
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/108
