### ISSUE TITLE
[Suggestion] Water Bottle/Canteens more convenient, less cluttering

### ISSUE THREAD

**Issue by chaNcharge** [Glitchfiend/ToughAsNails#133]
I think this would be a much better for the sake of convenience and not cluttering your inventory with a bunch of water bottles. My suggestions: (pick just one of these)
1. Water bottles should be stackable
2. Water inside a canteen can be smelted to make a clean water canteen
3. Ability to fill canteens with water bottles
To balance this out, you can make the crafting recipe of canteens a little more expensive, if needed

**Comment by WolfieWaffle** [comment]
I support these changes, perhaps some config options for individual options?

**Comment by chaNcharge** [comment]
That would be nice, that way stacking water bottles isn't enforced for some people who still want the challenge. Also, these changes also apply to juices too.

**Comment by hanleybrand** [comment]
Or how about making a 'filtering' canteen that would collect filtered water but would wear out and neer to be recombined with a filter to recharge?

**Comment by chaNcharge** [comment]
That could be a great addition. I support your idea.
