### ISSUE TITLE
support for modded drinks

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#135]
It would be awesome to add a support for ActuallyAdditions and Harvestcraft drinks that would restore thirst.

**Comment by 0Navis0** [comment]
It would be nice to support BloodMagic, Botania, Reliquary and ExtraAlchemy potions too.

**Comment by WesCook** [comment]
Perhaps a whitelist feature with some common defaults?  Writing custom support for all the mods may be a difficult task.

**Comment by 0Navis0** [comment]
Yeah it's what I thought too.
