### ISSUE TITLE
Issue with GregTech same as in BoP

### ISSUE THREAD

**Issue by GordonHollow** [Glitchfiend/ToughAsNails#136]
https://github.com/Glitchfiend/BiomesOPlenty/issues/897
https://github.com/Glitchfiend/BiomesOPlenty/commit/4f802ca60cda8b1e00866c0d71c1fba69df4e9ea

already fxd in BoP, need the same change in code in this mode too

**Comment by Adubbz** [comment]
Could you please provide the crash log with TAN and Gregtech? Since BoP and TAN don't share the exact same codebase the problem may appear similar however that may not necessarily be the case. I need a log before I can work on any fixes

**Comment by GordonHollow** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/759 - has the crash log with TAN

at toughasnails.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:35)

**Comment by demethan** [comment]
I can reproduce if you need more info.

**Comment by demethan** [comment]
Will there be a patch for 1.10.2?  This mod it the key to my Delusion Of Adequacy pack.  I saw the 1.11 update.  Are you going to use the McJty lib that makes 1.11 mods backward compatible to 1.10?
