### ISSUE TITLE
red on my server when loading

### ISSUE THREAD

**Issue by taluseve** [Glitchfiend/ToughAsNails#139]
my server console keeps telling me this for 1.10.2 minecraft, newest forge and optifine.....

20.11 11:54:38 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur!
20.11 11:54:36 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.item.ItemBlock (acl)
20.11 11:54:36 [Server] main/INFO [asmtweaks.ASMTweaksManager]: applying method modification from ItemBlockPlaceOverride to a(func_180614_a)
20.11 11:54:36 [Server] main/INFO [asmtweaks.ASMTweaksManager]: detected that obfuscation is true
20.11 11:54:30 [Server] main/INFO [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
20.11 11:54:28 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.world.chunk.Chunk (asv)
20.11 11:54:28 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.world.World (aid)
20.11 11:54:28 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.world.World (aid)
20.11 11:54:28 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash b85e91d5bf07c267f4f35e3818a8185e detected for class World. Crashes or bugs may occur!
20.11 11:54:27 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.world.World (aid)
20.11 11:54:27 [Server] main/INFO [malisiscore]: Found hooks for net.minecraft.world.World (aid)
20.11 11:54:27 [Server] main/INFO [mixin]: A re-entrant transformer '$wrapper.toughasnails.asm.transformer.WorldTransformer' was detected and will no longer process meta class data
20.11 11:54:27 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash b85e91d5bf07c267f4f35e3818a8185e detected for class World. Crashes or bugs may occur!
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ClientNotifTransformer] Hook registered for net.minecraft.world.World
20.11 11:54:26 [Server] main/INFO [malisiscore]: [TextureMapTransformer] Hook registered for net.minecraft.client.renderer.texture.TextureMap
20.11 11:54:26 [Server] main/INFO [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockModelShapes
20.11 11:54:26 [Server] main/INFO [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.RenderItem
20.11 11:54:26 [Server] main/INFO [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockRendererDispatcher
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
20.11 11:54:26 [Server] main/INFO [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
20.11 11:54:26 [Server] main/INFO [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@376a312c
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:26 [Server] main/INFO [IC2-core]: Loaded library EJML-core-0.26.jar.
20.11 11:54:26 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:23 [Server] main/INFO [asmtweaks.ASMTweaksManager]: using mappings for version 1.10.2
20.11 11:54:23 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:23 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:23 [Server] main/INFO [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
20.11 11:54:20 [Server] main/INFO [mixin]: Compatibility level set to JAVA_8
20.11 11:54:20 [Server] main/INFO [mixin]: SpongePowered MIXIN Subsystem Version=0.6 Source=file:/mods/movingworld-1.10.2-0003-full.jar Env=SERVER
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
20.11 11:54:20 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
20.11 11:54:20 [Server] main/WARN [FML]: The coremod toughasnails.asm.TANLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
20.11 11:54:20 [Server] main/WARN [FML]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
20.11 11:54:20 [Server] main/INFO [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.10.2-0003-full.jar
20.11 11:54:20 [Server] main/WARN [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
20.11 11:54:20 [Server] main/WARN [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
20.11 11:54:19 [Server] main/WARN [FML]: The coremod com.hea3ven.buildingbricks.core.load.LoadingPluginBuildingBricks does not have a MCVersion annotation, it may cause issues with this version of Minecraft
20.11 11:54:19 [Server] main/INFO [H3NTBootstrap.Bootstrap]: loading libraries
20.11 11:54:19 [Server] main/INFO [H3NTBootstrap.Bootstrap]: initializing
20.11 11:54:16 [Server] main/INFO [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:2.6.32-642.6.2.el6.x86_64, installed at /usr/java/jre1.8.0_111
20.11 11:54:16 [Server] main/INFO [FML]: Forge Mod Loader version 12.18.2.2123 for Minecraft 1.10.2 loading
20.11 11:54:15 [Server] INFO 2016-11-20 11:54:15,633 WARN Disabling terminal, you're running in an unsupported environment.
20.11 11:54:12 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
20.11 11:54:12 [Server] main/INFO [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
20.11 11:54:12 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
20.11 11:54:09 [Multicraft] Loaded config for "Default"
20.11 11:54:09 [Multicraft] Starting server!
20.11 11:54:09 [Multicraft] Loading server properties
20.11 11:54:09 [Multicraft] Received start command

the game loads but is there a way to fix it so it doesnt tell me this?          20.11 11:54:28 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash b85e91d5bf07c267f4f35e3818a8185e detected for class World. Crashes or bugs may occur!

jasyjui

**Comment by zerafox** [comment]
I too am getting this error...

01.12 06:15:48 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur!

Things appear to be working fine, although we haven't had it long/aren't familiar with everything just yet.

01.12 06:15:48 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur! 01.12 06:15:47 [Server] main/INFO [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer} 01.12 06:15:45 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash b85e91d5bf07c267f4f35e3818a8185e detected for class World. Crashes or bugs may occur! 01.12 06:15:43 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash b85e91d5bf07c267f4f35e3818a8185e detected for class World. Crashes or bugs may occur! 01.12 06:15:40 [Server] main/INFO [mixin]: A re-entrant transformer '$wrapper.toughasnails.asm.transformer.BlockCropsTransformer' was detected and will no longer process meta class data 01.12 06:15:40 [Server] main/ERROR [ToughAsNails Transformer]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur!

**Comment by Adubbz** [comment]
This isn't a 'problem' that can be fixed. The message is simply informing you that the class has been modified by some other mod, so it's not completely as TAN expected it to be. This may be a problem, it may not - you won't know until something does actually go wrong. However the message intends to warn you that this is a possibility.
