### ISSUE TITLE
Duplicating Items when hung

### ISSUE THREAD

**Issue by zerafox** [Glitchfiend/ToughAsNails#147]
Placing a Season Clock in an item-frame causes both the item-frame and clock to periodically 'pop off the wall' but still maintains the original items.
Sometimes this occurs and the hung items are invisible.

This is most common after teleporting out of the area and back again.
This is only noticed so far on SpongeForge, a similar ticket has been reported to Sponge.

SpongeForge: 1.10.2-2171 (1942)
Forge: 12.18.2.2171
Tough as Nails: 1.0.11

**Comment by Adubbz** [comment]
Yeah, I think this one is SpongeForge, especially if it's duplicating other entities based on the issue you made on their tracker. There's not really anything special about the season clock from a server's perspective, essentially all of the texture stuff the makes it work is client side. I made a massive wall of frames containing them just to be sure, and teleported away and back, and couldn't get this to happen. If the Sponge guys come back with something that does need changing on our end, I'm happy to look at it, but at this moment in time there's not a whole lot that we can do.
