### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by N9199** [Glitchfiend/ToughAsNails#148]
While loading Minecraft it fails, it says unexpected hash "hash" detected for class BlockCrops. Crashes or bugs may occur. It also says that for the class World.

http://pastebin.com/W0JKa9fT

Tough As Nails version: ToughAsNails-1.9.4-10.11

I also have the following mods:
- Optifine_1.10.2_HD_U_D4
- ae2stuff-0.6.0.4-mc1.10.2
- AppleCore-mc1.10.2-2.0.1
- AppleSkin-mc1.10.2-1.0.4
- appliedernergistics2-rv4-alpha-5
- AutoRegLib-1.0-2
- Autosapling-1.3.3-MC1.10
- Baubles-1.10.2-1.3.5
- bdlib-1.12.2.17-mc1.10.2
- BiomesOPlenty-1.10.2-5.0.0.2068-universal
- BloodMagic-1.9.4-2.1.0-66
- Botania r1.9-339
- Chameleon-1.10-2.1.7
- Charset-0.3.0-pre15
- Chisel-MC1.10.2-0.0.7.7
- chiselandbits-12.1
- DrawersBits-1.10.2-0.35
- EnderCore-1.10.2-0.4.1.58-beta
- EnderIO-1.10.2-3.0.1.126_beta
- FastLeaveDecay-MC1.9.4-1.2.1
- flatcoloredblocks-mc1.10-v4.1
- forestry_1.10.2-5.2.16.321
- FTBLiB-1.10.2-3.1.2
- FTBUtilities-1.10.2-3.1.2
- GardenOfGlass
- Guide-API-1.10.2-20.2-45
- hopperducts-mc1.9.4-1.4.8
- ImmersiveEngineering-0.10-48
- industrialcraft-2-2.6.87-ex110
- InventoryTweaks-1.61-58
- ironchest-1.10.2-7.0.11.797
- jei_1.10.2-3.13.6.387
- journeymap-1.10.2-5.3.0
- JustEnoughResources-1.10.2-0.5.1.56
- magneticraft-1.0.2-release
- Mantle-1.10.2-1.1.1
- mcjtylib-1.10-2.2.0
- Mekanism-1.10.2-9.2.0.292
- MekanismGenerators-1.10.2-9.2.0.292
- MekanismTools-1.10.2-9.20.292
- Morph-o-Tool-1.0-10
- natura-1.10.2-4.0.0.86
- Neat 1.3-12
- Pam's HarvestCraft 1.9.4-1.10.2h
- Psi-r1.0-42
- Quark-r1.0-55
- Railcraft_1.10.2-10.0.0
- rftools-1.10-5.59
- roots-1.10.2-0.204.0
- SpiceOfLife-mc1.9.4-1.3.6
- StorageDrawers-1.10.2-3.2.7
- TConstruct-1.10.2-2.5.6b
- Waila-1.7.0-B3_1.9.4
- WailaHarvestability-mc1.10.2-1.1.9

**Comment by Adubbz** [comment]
Please see my response to https://github.com/Glitchfiend/ToughAsNails/issues/139 . The warning indicates that another mod has touched the file in a way that may be incompatible with TAN. In this instance, it looks like that conflict has indeed resulted in a crash. I'd suggest to try removing AppleCore, Applied Energestics, IC2, Mekanism and Quark individually to determine which one is responsible.

**Comment by N9199** [comment]
It seems it was Applecore, but it also seems that it was fixed in a newer version. Thanks for the help.
