### ISSUE TITLE
Weather2 Compatibility

### ISSUE THREAD

**Issue by MaegnusTheBlackMage** [Glitchfiend/ToughAsNails#149]
I have noticed that despite it being winter it still rains. I am using the Weather Mod and it seems that since that overrides vanilla weather it is also causing issues with the winter weather. I am also reporting this to Weather2 but would love to see a fix for compatibility

**Comment by Corosauce** [comment]
I don't have an api at all yet so I might look into detecting tough as nails state to prevent rain etc on my side.
