### ISSUE TITLE
Add lanterns and torch dying

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#15]
Torches should die out after an in-game day (Or two maybe), and need to be re-lit with a flint and steel.  This was originally planned to be a feature in Minecraft with the Halloween update, but was never added.

Lanterns will stay lit forever, and be able to be placed on walls and floors, just like torches.  They will be crafted with gold ingots, glass, and torches.

**Comment by TDWPFTW** [comment]
Decided to scrap this feature

**Comment by Quizer9O8** [comment]
There should a kind of decay for torches and lanterns that have been lit for a long time.
People do leave behind a lot of torches, a lot. especially in explored caves, so it would be a surprise for them to see it all lit out when visiting those places again.

**Comment by Forstride** [comment]
Well, yes, that's the point of this.  Lanterns are meant to be permanent though.

**Comment by Quizer9O8** [comment]
speaking about realism, what about torches that die out if they are in the rain?

**Comment by pastellexists** [comment]
Maybe have a config for this? Many players will find it annoying. Which was the reason it wasn't in the halloween update, too much backlash.

**Comment by Forstride** [comment]
Yes, there will be a config option for it whenever it gets added (As with every main feature in the mod)
