### ISSUE TITLE
Thermometer in item frame

### ISSUE THREAD

**Issue by MaegnusTheBlackMage** [Glitchfiend/ToughAsNails#150]
Despite my temperature going up a thermometer in a frame does not correctly display the temperature
 
![2016-12-07_00 11 36](https://cloud.githubusercontent.com/assets/1408174/20955504/be78ea1e-bc11-11e6-9554-c8fa8561d536.png)

![2016-12-07_00 09 49](https://cloud.githubusercontent.com/assets/1408174/20955487/928c38ac-bc11-11e6-8b35-570d6fbf125c.png)

**Comment by Adubbz** [comment]
This is intentional, you must be holding a thermometer for it to display your temperature.
