### ISSUE TITLE
Requests list

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#151]
I think that you should delete(or add this option in config) Heating and Cooling Coils, because with them, seasons become uninteresting(because if you have coils, it's not important which season is now, you can grow plants always, and you never will supercooled or overcooled). And when Agricraft will port on 1.10.2(it will be soon) add an integration with crops(do that they didn't grow when are hot or cold to much).

**Comment by MaegnusTheBlackMage** [comment]
I disagree in fact I would like to see the ability to disable crops being affected. No matter what i try my crops die. I build a lot of underground bases and even though ive built a huge underground farm with heating and cooling my crops still die

**Comment by maxiride** [comment]
@BurovB Have you thought of tweaking the coils recipe to make them harder to get? Might be a workaround.
