### ISSUE TITLE
Problems, improvements, suggestions

### ISSUE THREAD

**Issue by lumagatto** [Glitchfiend/ToughAsNails#154]
This is the list of things i would like to see for now in the mod. Things with more "-" have highter priority for me. 

--- Furnace should heat the player like the firecamp;

---- Firecamp could be used to cook (only) food (with config to add from other mods), and will take double time to do it;
---- Firecamp crafted with sticks instead of logs;
--- Sticks used to light it should be no more than 5;
-- If not already possible it could be started by flint and steels or right clicking with torches (also from RealisticTorches mod);
-- It could also set on fire flammable blocks above it.

--- Water from rivers should not be dirty;
----- Dirty water and filtered water should not give thirst effect (does not make sense that when you drink you don't get hydratated), but weakness (80% chance for dirty and 20% filtered) and nausea (25% chance for dirty and 5% chance for filtered)(weakness and nausea from vomiting);
-----Water from oceans and beaches will also give hunger and thirst (weakness 80%, nausea 50%, hunger 50%, thirst 100%) until filtered (salt water is even worse for the stomach).

----- You could drink by right clicking on water with empty hands but will have a very hight chance of being bad, depending on biome. Rivers will be the safest (25% weakness and 10% nausea), beaches and oceans won't be good (85% weakness, 55% nausea, 55% hunger, 100% thirst), and swamps will be the worst (90% weakness, 50% slowness, 90% nausea, 90% poison, 10% withering)(bleah).

----- Filters should have a durability of 64;
---- You could right click with wool on water to get wet clean wool. Then you could cook wet clean wool in a furnace to get clean wool that could be used as a filter and should have durabilty of 16 (less expensive but less durable, good for early game).

-- The highter the biome temperature, the faster fire will spread.

--- EVERYTHIG configurable: first of all biome temperatures.

---- Torches from RealisticTorches mod could be lit in firepits.

I think that for now is not very enjoyable :s but it can become a really good simple mod and i hope it. I will support it if it will be developed. 👍

**Comment by FoxZOolm** [comment]
"--- EVERYTHIG configurable"
I agreed !!!

**Comment by Exsolutus** [comment]
The mod definitely needs a more extensive config file, agreed.
