### ISSUE TITLE
cant get season in bop mod

### ISSUE THREAD

**Issue by taluseve** [Glitchfiend/ToughAsNails#156]
i use 1.10.2 version of the mod, which i love but when i build in plains- vanilla biome and prairie - bop biome it only rains in winter... is there a way to change it so it also gets the seasons?

jasyjui

**Comment by Forstride** [comment]
Not every biome gets snow.  It depends on what the base temperature of the biome is, and those biomes are too warm to get snow.

**Comment by taluseve** [comment]
any way to change them using CC?
