### ISSUE TITLE
Major Bug/Glich

### ISSUE THREAD

**Issue by FlagrantFool** [Glitchfiend/ToughAsNails#157]
hello, I would like to report a major mod braking bug/glitch here. Also, thank you in advance for your time, and for the work that you have put into developing this awesome content!

I found this glitch while playing a newly created moded survival. After about 15-20 in game days of gameplay (sleeping every night at sundown) the season cycle begins to become heavily glitched. Once this began to occur I began to set out to identify the problem, as I thought it may be related to conflicting mods. first I tried to identify the problem in creative (I thought that I would be successful at this so I deleted my current survival save) however I was not able to reproduce the bug in creative, and I tried a lot of different things. For my next attempt to identify the problem, I began a new survival world in hard - here I was able to successfully reproduce the bug - and then switched it to peaceful. After reproducing the bug, I then set out to reveal the specific nature of the bug and then systematically identify what mod TAN may be conflicting with, this is what I found:

To reveal the nature of the bug, I gathered materials in peaceful and created 4 season sensors, and set them up so that I could monitor the progression of the seasons. What I saw was that, with this bug in full effect, every time I slept, when I woke up, it would be the next season, so that each day I would be experiencing a new season - this was tested extensively.

I then set out to systematically identify the conflict by use of the 4 season sensors I had set up and systematically removing every mod I had installed, one-by-one, in an attempt to try to correct the season progression in game (so, I would remove a mod boot up the game wait for night fall and then sleep - success would be determined if when i awoke the season sensors did not jump to the next season - if I was not successful, then I would shut the game down, remove a single mod, then begin again).

I removed all mods except the following three, from the list bellow, and was never able to correct the season progression: joypad, optifine, tough as nails.

Apple-Shields-Mod-1.10.2
BaublesHud-Mod-1.10.2
Baubles-Mod-1.10.2
Better-PvP-Mod-1.10.2
Blood-Magic-Mod-1.10.2
Botania-Mod-1.10.2
Building-Bricks-Mod-1.10.2
Deadly-Monsters-Mod-1.10.2
Dynamic-Surroundings-Mod-1.10.2
Ender-Compass-Mod-1.10.2
EnderCore-1.10.2-0.4.1.61-beta
Ender-IO-Mod-1.10.2
Forestry-Mod-1.10.2
jei_1.10.2-3.13.6.387
JEI-Bees-Mod-1.10.2
JoypadMod-1.9-12.16.0.1842-1.9
morebees-1.10.2-1.1.6
natural_absorption-1.10.2-1.2.2
Natures-Compass-Mod-1.10.2
Netherrocks-Mod-1.10.2
OptiFine_1.10.2_HD_U_D3
Pet-Bat-Mod-1.10.2
Power-apples-mod-by-lothrazar-1.10.2
Reliquary-1.10.2-1.3.3.585
Salty-Mod-1.10.2
simplecore-1.10.2-1.3.15.1
Terrain-Crystals-Mod-1.10.2
Tough-As-Nails-Mod-1.10.2

And then I erased all config files and tried one last time, to no avail. I do not know whether or not this means if there is a conflict or not - I have zero programming skills - but I know that it is more than I can deal with. So, I thought that I would hand it over to you guys. because frankly I am getting tired of trying to fix it. I am starting a new survival world now with seasons and temp turned off, in the config file, and I hope that if/when you guys get this fixed, I'll be able to turn them back on and everything will be cool.

Once again, thank you for your time, and if there is anything that I can do to help just let me know. I'll be monitoring this thread.

**Comment by Forstride** [comment]
This was fixed in the latest version of the mod for 1.11:

https://github.com/Glitchfiend/ToughAsNails/commit/47e618ef92cf6c4fa81dbef0ef148cd9a228d3a3

https://minecraft.curseforge.com/projects/tough-as-nails/files/2352873
