### ISSUE TITLE
[1.9.4] World transformer has incorrect method name reference for non-obsfucated..

### ISSUE THREAD

**Issue by OreCruncher** [Glitchfiend/ToughAsNails#159]
[Here is the link.](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.9.4-1.0.0/src/main/java/toughasnails/asm/transformer/WorldTransformer.java#L36)  "getBiomeGenForCoords" is incorrect - should be "getBiome".  Explains that nasty exception I get when running in my IDE. :)

(I have TAN as a library in my sandbox so I can build against it.  However I can't run a debug session because of the transform error.)

EDIT: I should state that I am working with Minecraft Forge 1.10.2-12.18.3.2185

**Comment by Adubbz** [comment]
Odd, I had to fix this for 1.11 but I don't recall it being a problem when updating to 1.9.4... In any case, I've pushed a commit to fix it. I won't bother making a new release though since it's only really relevant for the development environment

**Comment by OreCruncher** [comment]
Thanks! Picked up the changes in a local sandbox and it works well.

Is there a forum that you frequent where I can post questions?

**Comment by Adubbz** [comment]
Generally Discord is the best place https://discordapp.com/invite/0loJvLMgvZi0q596 (There's also a client for it too if you dislike the browser version)

**Comment by p455w0rd** [comment]
a direct clone of the 1.9.4 branch fails due to this 'fix' because this is a 1.10.2 change
