### ISSUE TITLE
Add Lifeblood Crystals and lower starting health

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#16]
Lower the player's starting health to 5 (Will be configurable), and add Lifeblood Crystals for the player to find in Nether fortresses, which will add additional hearts.  The player will not be able to have more than 10 hearts total.

**Comment by UndeadZeratul** [comment]
What about scaling the starting max health based on world difficulty?  Peaceful and Easy could drop slightly to 9, Normal to 7, Hard to 5, Hardcore to 3?

**Comment by Forstride** [comment]
I was thinking that, but I'm not sure if that would work well, seeing as you can change difficulty (Assuming it's not locked).

Also, if we did it that way, I'd do it 10 peaceful, 7 easy, 5 normal, 3 hard/hardcore.

**Comment by RJHG56** [comment]
can i change the place where de  lifeblood crystals spawn for the overword or in ordinary crates?
