### ISSUE TITLE
2 issues and 2 requested features

### ISSUE THREAD

**Issue by Gunmodder** [Glitchfiend/ToughAsNails#160]
First, i really like this mod. I think it's one of the best one's ever made for Minecraft. But there are a few things i really don't like and hope you can improve it.

1. The biggest issue i had with the mod. A bug or a missing feature. You can't collect water with your canteen from flowing water. Little backstory: I was in a deep dungeon and i got thirsty. There were many water sources coming through wall holes or from an waterfall. But i never could fill my canteen. I died in this dungeon because thirst next to a water source.

2. This should be a realistic mod and it also feels like it. But why do you need a canteen only to drink water? Why can i not just go to a water source and drink it? Canteen should only be an item to transport water for you or as basic item to make clean water later with it. But nothing is more frustrating as dying next to water because it is flowing water and you cant drink it or you can't drink it because you didn't find cows fast enough to craft a canteen. I think thirst and hunger are different and thirst should be possible to refill without a required item.

3. If I suffer damage by drowning in the water, you lose hearts each time. I think you should make it so, that for every heart you loose, thirst will be restored. Because it's realistic.

4. The lowered health is by far the most difficult thing in this mod. I think you should offer more options to restore your hearts or add more spawns for the required items for example caves or as loot from the witch.

That's all for now. I was testing this mod for 3 days now and im really impressed. Specially the body temperature part and the seasons are really good and balanced as far as i can say.

**Comment by Forstride** [comment]
I do agree with the first two, but the latter two aren't really ideas that I'd want implemented.

Just because you're taking in water when you're drowning, doesn't mean your thirst is gonna be restored.  You gotta figure, in real life, you'd be hyperventilating and whatnot, and your body would be working hard to not die.

As for the 4th suggestion, I think that would just make the lowered starting health feature pointless.

**Comment by Gunmodder** [comment]
Ok maybe point 3 and 4 are no good ideas. But if someone can fix problem 1 and 2 it will be an epic and must have mod for me :) And if someone not like the lowered health thing (like me) you can simply turn it off so its fine
