### ISSUE TITLE
Crash with a debuff

### ISSUE THREAD

**Issue by GWSheridan** [Glitchfiend/ToughAsNails#162]
When you drink a heat potion with any debuff minecraft will completely crash

**Comment by Adubbz** [comment]
We need much more information than that. A crash report, version numbers, whether you have tried with TAN on its own etc.

**Comment by GWSheridan** [comment]
Vanilla Minecraft with only Tough as nails mod Crash when there is a debuff
Crash Report > http://pastebin.com/0stSrUp1
Tough as nails version 1.0.11
Minecraft version 1.10.2
Forge version 12.18.3.2185

**Comment by GWSheridan** [comment]
Any fix for this yet please
