### ISSUE TITLE
[Suggestion] Air quality

### ISSUE THREAD

**Issue by Stormwind99** [Glitchfiend/ToughAsNails#166]
Air quality may fit well in the game design of Tough As Nails.   

Deeper underground, nether, lava, etc could decrease air quality and eventually cause suffocation.   Gas masks, plants, and respiration enchantments could offset suffocation.

The discontinued EnviroMine mod contains a good example of an air quality feature:
https://github.com/EnviroMine/EnviroMine-1.7/wiki/Air-Quality

**Comment by maxiride** [comment]
Already posted in #11

**Comment by Stormwind99** [comment]
Dupe of #11, sorry
