### ISSUE TITLE
[Suggestion] Naturally clean water sources

### ISSUE THREAD

**Issue by Stormwind99** [Glitchfiend/ToughAsNails#167]
Some sources of water are naturally clean, such as springs, mountain streams, and underground aquifers.

Make some water sources naturally clean to reflect this, and to make finding them a special treat.

For example, flowing water found in mountain biomes could be considered naturally clean.

**Comment by Forstride** [comment]
Bit late with the response, but we really don't want to change world gen much, if at all, with TAN.
