### ISSUE TITLE
Canteen bugs

### ISSUE THREAD

**Issue by Dalethium** [Glitchfiend/ToughAsNails#172]
The canteen appears to be bugged for the current version on curse (jar name: ToughAsNails-1.11-2.0.4.jar)
Durability can go down into the negatives if you refill it before it is empty, and the durability bar remains at full (colored red) length even when you have used it more than once when the durability is in the negatives. 

It still only allows for 3 uses, but the display is definitely bugged.

**Comment by JasonMcRay** [comment]
I have personally found out also if the durability is in the negatives and you drink it, even if it is filtered, you get the Thirst debuff.
