### ISSUE TITLE
[Suggestion] Clean wells

### ISSUE THREAD

**Issue by Dalethium** [Glitchfiend/ToughAsNails#173]
Why not test for wells in villages? They should have clean water should they not?

I was thinking a few ways this could be done, 

1. Test for a village in the seed, see where the well is, (I am not sure if you can test for a well based off the seed though)
2. Test for a multi block structure similar to a well, perhaps allow for maybe 5 or 10 blocks to be out of place?
3. Combination of 1 and 2, since normally you can't have clean ground water everywhere, you find the multi block structure from option 2, and test if it is in range of a village, that way making wells only "pull" clean water from the ground in specific places.

Thanks, 
  - Daleth.

**Comment by WolfieWaffle** [comment]
I think this is actually one of the best ideas presented so far, what about making special "well blocks" that you make a multiblock out of and it will provide clean water, then just change the village generation to use that multiblock. Either way I think the thirst system needs some work.

**Comment by Winddbourne** [comment]
I like this idea; and agree with WolfieWaffle that it would be easier to just over-ride the placement of normal village wells with a special structure of your own. 

Extra +1 if you also can build it yourself out of specially crafted blocks including a long drop and clean water blocks placed at the bottom. The multiblock should only work in Biomes that would normally have an accessible aquifer though. Forests and plains mostly, and a certain number of blocks away from any ocean biome.
