### ISSUE TITLE
Some of the Foods Should Restore Thirst

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#179]
for example, apple. it should restore my thirst. and also a soup, pumpkin pie... and terraqueous fruits.
edit: and also water bottle should.

**Comment by InjuredWolf** [comment]
and natura berries. considering how saturating they are, they kinda should. Maybe add a command for ops to define thirst-giving foods? eg /tan setThirstValue <item> <value_in_half_drops>

**Comment by Ressed** [comment]
and there're also many kinds of juice in other mods,i think adding a config is good

**Comment by ghost** [comment]
Yes, exactly. Adding a config to add thirst restorer items and also restore count for them would be awesome. Hope they do it.

**Comment by Winddbourne** [comment]
Perhaps a two part configuration option. First a listing for the food that is restoring thirst, and then a percentage number.  The percentage would be taken away from the foods natural saturation and added to it's ability to quench a certain amount of thirst. 

So we might list a natura berry and then 50% . . . now when you eat the berry you only get half it's normal saturation, but the remainder would go towards restoring thirst. I'd suggest that the minimum thirst restoration would be perhaps a quarter water drop. 

This is after all "Tough as nails" if a food is going to restore thirst it should also lose some of it's normal benefits. lol

**Comment by InjuredWolf** [comment]
I support that.

**Comment by SamGunGraven** [comment]
A config of consumables and how much they replenish thirst would be godsent to anybody using this for a modpack - without the configs it severely limits any pack
