### ISSUE TITLE
How do I use Api??

### ISSUE THREAD

**Issue by Squirtle8459** [Glitchfiend/ToughAsNails#180]
Forgive my stupidity, I am trying to use get the current season and if the season is the proper one i need it will do what I want, the problem is it wants to import the config files and therefore everything else? Do I not just add the api as I would COFH api? ... Or am I doing it wrong?

**Comment by Squirtle8459** [comment]
This is what i meant by importing, it's needing this handler supposedly 'SyncedConfigHandler'... I feel dumb haha... probably doing it wrong..

**Comment by Dalethium** [comment]
look at dsurround by oremuncher (cruncher?) he hooks into the api in there. it's on github.

**Comment by Squirtle8459** [comment]
I am blind as I see no reference to the API for the mod..

**Comment by Dalethium** [comment]
seasoninfotanregistry.java or something like that

in the package registry/season

**Comment by Adubbz** [comment]
Indeed, this specific issue was an oversight, the imports used should've also been included in the api
