### ISSUE TITLE
[1.10.2] Feature Suggestion

### ISSUE THREAD

**Issue by XvSkItZvX** [Glitchfiend/ToughAsNails#181]
I have been working on compiling a survival themed mod pack, one of the mods I make use of is "Apple Skin" which provides a number of interface options regarding food and saturation. 

During my play tests with your mod I noticed the behavior of the water droplets (Hydration gauge?) seemed to act very similar to the hunger/saturation mechanic of vanilla. 

If this is the case and there is another gauge behind the scenes, similar to saturation, I thought it would be nice to have an overlay similar to the one provided by Apple Skin. In actuality I suggested this to the Dev for Apple Skin first but they felt this is a feature better implemented within Tough As Nails itself.

**Comment by Forstride** [comment]
Our mods are meant to feel like they're just a part of the base game rather than actual add-ons, and I feel like doing that would make thirst feel a bit too different, even if it's not a huge change.
