### ISSUE TITLE
Ars Magica hud overrides Tough As Nails hud

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#183]
I link this issue here because I have some problems to include both hud in pretty visible way, Ars Magica huds can be moved, but it seems Tough As Nails one can't, it would be nice if it was possible to move it too.
https://github.com/Mithion/ArsMagica2/issues/1589#issuecomment-277612429

**Comment by Forstride** [comment]
HUD issues should be fixed now.
