### ISSUE TITLE
[Suggestion] Fire as heat source

### ISSUE THREAD

**Issue by grundyboy34** [Glitchfiend/ToughAsNails#186]
Something I've noticed is that fire doesn't provide heat. Could this be added as functionality, and possibly disabled with a config? Perhaps it could even be setup to be a list of blocks defined in the config that provide heat or cooling.

**Comment by bob0bob** [comment]
Yes.   I've noticed that also.  Fire means nothing.   Get Netherrack block and ignite it and it does nothing.

**Comment by bob0bob** [comment]
The issue with fire.  Is that block temperature will over ride material temperature.   I don't think if you are standing on a block that might have a temperature that is lower then fire.  It should over ride fire.

**Comment by Adubbz** [comment]
I believe this was resolved awhile back in newer versions (1.12 definitely, 1.11 too possibly?)
