### ISSUE TITLE
Sleeping in a Bed advances seasons dramatically

### ISSUE THREAD

**Issue by Vaevictusnet** [Glitchfiend/ToughAsNails#190]
I'm playing Forever Stranded and monitoring season modifier via /tan tempinfo.

I've slept the last three nights in bed going from +6 to -6 to -4 to +2, for the season offset.
I've heard other people say that the season value "changes from day to day" but i only notice this when sleeping.

**Comment by Adubbz** [comment]
This has already been fixed, see https://github.com/Glitchfiend/ToughAsNails/issues/60
