### ISSUE TITLE
Seasons config and snow

### ISSUE THREAD

**Issue by joshiejack** [Glitchfiend/ToughAsNails#193]
Hello there! Would it be possible if seasons are disabled to get https://github.com/Glitchfiend/ToughAsNails/blob/85ec7ddd56574a22fccf4cd021b0e63f6429f0b4/src/main/java/toughasnails/season/SeasonASMHelper.java#L37

to redirect to the normal call of this.provider.canSnowAt(pos, checkLight); as well as not registering this to the event bus https://github.com/Glitchfiend/ToughAsNails/blob/85ec7ddd56574a22fccf4cd021b0e63f6429f0b4/src/main/java/toughasnails/handler/season/RandomUpdateHandler.java

My mod https://github.com/PenguinSquad/Harvest-Festival also has seasons but I'm having the issue that snow isn't getting placed when it is winter in my mod because this one is blocking it from happening even with the seasons disabled, since i override the worldprovider for my changes.

**Comment by Forstride** [comment]
Closing this since we're moving seasons to a separate mod (https://github.com/Glitchfiend/SereneSeasons).
