### ISSUE TITLE
Server memory leak (1.10.2)

### ISSUE THREAD

**Issue by Thyriel** [Glitchfiend/ToughAsNails#195]
Tough As Nails 1.0.11 on 1.10.2 server seems to have a huge memory leak.
Without tough as nails my servers never going above 0.96GB, with the mod it's increasing by like 1-200MB per minute. Saw it going up to 8GB with only 1 player on it standing still.

**Comment by Adubbz** [comment]
Does this occur with TAN on its own? Logs with only TAN installed would also be good as well.

**Comment by Thyriel** [comment]
I will try around with only TAN this evening and post an update. Atm it was with quite some other mods, but after testing every mod one by one until the server didn't had the leak problem it definitly was TAN causing the problem. (Need to test further but could be that it didn't happen until i placed a couple Heatcoils - at least i didn't notice a problem before)

**Comment by Thyriel** [comment]
Sorry for the delay. I could reproduce the problem with only TAN installed and nothing else. It's not TAN causing the problem, it's the Heatcoils. With just TAN and playing around the server runs stable at 0.6GB RAM used. I then digged underground, made a big room and placed a couple heatcoils powered by redstone torches.
RAM usage went withing a couple minutes up to several GB used.
Serverlog: http://pastebin.com/vfWDGUhr

edit: Just in case it plays a role, it was in an ice plains biome.

**Comment by Adubbz** [comment]
How big was the room out of curiosity? If it's *extremely* large than it would likely be due to the masses of potential changes it has to check for. Also, it's definitely heat coils and not cooling coils? Since there was an issue with particles affecting performance that hasn't been fixed in the 1.10 version

**Comment by Thyriel** [comment]
Only heating coils as i'm playing in a snow biome (Didn't test coolings or if campfires have the same effect). Room was 40x40x6 blocks.

**Comment by Thyriel** [comment]
Any chance for a fix ? Would be pretty sad if i have to remove TAN from the modpack i am working on because of this gamebreaking bug
