### ISSUE TITLE
Campfire lasts forever

### ISSUE THREAD

**Issue by InjuredWolf** [Glitchfiend/ToughAsNails#196]
I lit a campfire, and haven't needed to relight it.

Also, breaking a campfire doesn't drop anything at all.

**Comment by ghost** [comment]
Bumping this issue as it's happening to me, too.  I'm not sure if maybe I just got lucky, but my campfire has lasted at least a couple nights now.

**Comment by Forstride** [comment]
A bit late, but I just changed the campfire so it should *hopefully* not last as long.  It's kind of iffy trying to do this with random block ticks though, so it can last for wildly different amounts of time.
