### ISSUE TITLE
Request: Green House Glass

### ISSUE THREAD

**Issue by dannydjdk** [Glitchfiend/ToughAsNails#197]
It would be great to have green house glass that warms the area below it when exposed to the sky. Since the heating coils don't work under glass, this would add support for more realistic greenhouse builds. Compatibility with greenhouse glass made by other mods such as Forestry and Actually Additions would be a huge plus as well. Perhaps even regular glass could have a small warming affect.

**Comment by aelfwyne** [comment]
This would be a great idea. Greenhouses serve this exact purpose, to allow light in but keep the crops warm.

**Comment by aelfwyne** [comment]
This is desperately needed. I have tried the "add a roof" to the temperature regulator trick and it doesn't seem to work. Crops still die in an enclosed room under glass. In the real world you can make a greenhouse, there's no reason it should not be possible with TAN. As is, vanilla seeds/crops are basically worthless.
