### ISSUE TITLE
Heating Coil Doesn't Work

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#205]
i'm freezing in my little home which has a heating coil inside... that shaking snow crystal... why is this? 
and... oh, no heating source don't work. i really wonder what the problem is. should i send my latest fml log?
edit: weird, it's fixed when i kill myself with /kill command

**Comment by ghost** [comment]
i can show you as this:
![thermometer](https://cloud.githubusercontent.com/assets/24831406/23524744/a508b5de-ff94-11e6-9c6c-b8bd04a21eb6.PNG)
look at thermometer. it shows it's very cold. but i have heating coil :( it shouldn't be cold...

**Comment by Vectrobe** [comment]
Do you have a roof? and how long were you sitting there?

**Comment by ghost** [comment]
yes i had, but i deleted that world a long time ago. you can close this issue

**Comment by CorneliusCornbread** [comment]
I'm having the same issue
