### ISSUE TITLE
No Seasons (Bug)

### ISSUE THREAD

**Issue by HypnoPants** [Glitchfiend/ToughAsNails#208]
I've been messing with the days and time in minecraft to see the seasons in action... nothing seems to be occurring, I'm wondering if it could be a mod like dynamic surroundings or better foliage getting in the way?

Edit: Been playing with the season clock and I'm adding days 1 by one and I'm not noticing the season clock moving at all.
Edit2: Tested with only tough as nails mod loaded, seasons still aren't changing :(

**Comment by HypnoPants** [comment]
... I take it no one else is having this problem?

**Comment by HypnoPants** [comment]
Do the seasons not change based on days? Because I think I noticed a change, but from regularly playing and not from /time add

**Comment by Adubbz** [comment]
`/time add` is not intended to progress seasons, `/tan setseason` is. Sounds like this is just a mixup in commands

**Comment by HypnoPants** [comment]
Thank You! I couldn't find any info on the TaN commands :)

**Comment by Adubbz** [comment]
Did you have a look at the wiki? They are documented pretty well there: https://github.com/Glitchfiend/ToughAsNails/wiki/Commands

**Comment by HypnoPants** [comment]
... I had no idea, so many times when I click on a github wiki it just shows a blank page, guess I got used to it :P
