### ISSUE TITLE
[1.11.2] Filtered Canteen still applying Thirst debuff

### ISSUE THREAD

**Issue by Rosethorns** [Glitchfiend/ToughAsNails#210]
Description: Filtered canteens are still applying the thirst debuff.
Steps:
1.Fill Canteen with dirty source
2. Use charcoal filter
3. drink from now "filtered" canteen for a normal chance to get the thirst debuff

Minecraft; 1.11.2
Forge: 13.20.0.2252
Tough As Nails: 2.0.5

**Comment by aelfwyne** [comment]
I noticed this myself. What's the purpose of charcoal filtering if you still get sick from it?

**Comment by Forstride** [comment]
Filtering water doesn't make it *completely* clean.  You have half the chance of getting "sick" from it compared to dirty water, although maybe it should be lower.
