### ISSUE TITLE
[1.11.2] Terraqueous life fruit decreases total health with TAN installed, should increase.

### ISSUE THREAD

**Issue by MrNinja93** [Glitchfiend/ToughAsNails#212]
Little bit of an odd one.

Terraqueous add a fruit that gives a health boost when eaten, without TAN it works as intended but with each time it's eaten total health is decreased to 0 hearts (you still remain alive).

Death resets total health back to normal levels.

Is this intended or an actual bug in logic?

Forge: 13.20.0.2259
TAN: 1.11.2.0.5

**Comment by asanetargoss** [comment]
This is a bug with Terraqueous. @ShetiPhian is mixing up the base value of the health modifier with the value of the max health after modifiers are applied. They should use a max health [modifier](http://www.minecraftforge.net/forum/topic/29927-the-entity-attribute-system-how-to-manipulate-it-in-code/) instead.

**Comment by ShetiPhian** [comment]
Well I've been wanting to rework the fruit to provide a non time limited absorption effect, been on my to do list forever, just need the time to do so.

Edit:
Next build will have the fix.
