### ISSUE TITLE
Plains rain during winter

### ISSUE THREAD

**Issue by HypnoPants** [Glitchfiend/ToughAsNails#213]
I'm in a village with half in plains and half on the lower parts of extreme hills, half the town is covered in snow the other half it rains during mid_winter... is that a bug, or is it supposed to do that?

**Comment by Forstride** [comment]
yes, it's "intentional."  plains just have a high enough temperature value that the automatic temperature shift in winter doesn't make it snow.

**Comment by HypnoPants** [comment]
Kay! thank you :P
