### ISSUE TITLE
Config Changes [Suggestion]

### ISSUE THREAD

**Issue by Yspatil** [Glitchfiend/ToughAsNails#215]
Hi,
 
I was wondering if you could make it so that we can change the length of each season in the config. Also, during winter, it only seems to snow in foresty biomes (I am using biomes o' plenty), can you make it so that we can control what biomes get snow in the config as well because I want other biomes such as the plains to get snow too. ( Tough as Nails for 1.11.2)
 
Thanks,
Yspatil

**Comment by Kaelthalon** [comment]
I talked to Darkosto, and he too agrees with more config options. A good idea for this mod is to separate it out in a folder and have different categories of configs.

- Length of Seasons
- Rate of Hot/Cold
- Seasonal Effect: List Biomes


Just remember, Modpack Developers LOVE config options! The more the merrier. Configs offer a way to balance their pack to make it enjoyable.

**Comment by Andvee** [comment]
Very much this, and/or an option to lock TAN seasons in sync with HarvestFestival seasons (82 "days" vs 120 days for a "year").
