### ISSUE TITLE
GUI conflicts with Ars Magica 2

### ISSUE THREAD

**Issue by TomberWolf** [Glitchfiend/ToughAsNails#217]
Sometimes the GUI is glitchy and not shown when using Ars Magica 2 on 1.10.2.
I'm going to report this to Ars Magica as well.

**Comment by EPIICTHUNDERCAT** [comment]
this is known over at ars

**Comment by gigafunk** [comment]
It kinda works though.  If you study magic with ars you start to lose track of your bodys needs.....I mean thats a feature!!

**Comment by Forstride** [comment]
HUD issues should be fixed now.
