### ISSUE TITLE
Going to Nether sets hearts to 10 rather then 5 and going back to overworld keeps it as 5 unless player dies

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#218]
Title says it all
If You go to Nether, the hearts are 10 rather than the 5 which You start with
Then returning from the nether to the over

**Comment by ghost** [comment]
Sorry, hit enter by mistake
returning from the nether to the overworld, it keeps them as 10 unless player dies

**Comment by Adubbz** [comment]
This is a duplicate of this issue https://github.com/Glitchfiend/ToughAsNails/issues/42
