### ISSUE TITLE
Commands do not work in command blocks

### ISSUE THREAD

**Issue by jihoonchoi724** [Glitchfiend/ToughAsNails#219]
When I use a /tan command in a command block (for example, /tan setseason mid_winter), it outputs "You must specify which player you wish to perform this action on" even though player selection is not relevant to the command.

**Comment by ghost** [comment]
Seasons are saved per-world ; and the commands code ([example here for _setseason_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/command/TANCommand.java#L138)) is using the _CommandSender_ to retrieve the world that should be updated, thus making it unusable from a command block (and maybe from the console too).
