### ISSUE TITLE
[1.10.2] Rain collector doesn't fill with the rain storms from Local Weather and Storms  

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#222]
I tried some times but the Rain collector doesn't fill any water. I created some rain storms, one after the end of the last, trying almost one hour and nothing.

I'm use:
weather2-1.10.2-2.4.10
Tough As Nails 1.11
Forge 1.10.2 - 12.18.3.2185

**Comment by Forstride** [comment]
Likely nothing we can do about this.  The way their rain works probably doesn't trigger the vanilla rain checks, which is what we use.
