### ISSUE TITLE
[1.10.2] Crashing with item from Aroma1997 mod

### ISSUE THREAD

**Issue by deni500** [Glitchfiend/ToughAsNails#224]
When I used DimensionChanger I get crash, and when I Start up minecraft again I was in Mining dimension, but when I used DimensionChanger to go back to Overworld it crashed me again and I think with same crash log: https://pastebin.com/Pd0GSNVS

-Aroma1997Core - version: 1.9.4-1.1.1.2
-Aroma1997s Dimensional World version: 1.9.4-1.2.0.6
-Forge version: 12.18.3.2254
-ToughAsNails version:  1.9.4-1.1.1

I did post with this crash on Aroma1997 issue tracker [here](https://bitbucket.org/Aroma1997/miningworld/issues/116/crash-when-i-used-dimensionchanger), but he said that on 90% it's ToughAsNails issue so I'm posting here too.

**Comment by tyler489** [comment]
Yeah its a tan issue might be related to this bit of code ```  @SubscribeEvent
    public void onItemUsed(PlayerInteractEvent event)
    {
        /* TODO: 1.9 if (event.action != Action.LEFT_CLICK_BLOCK)
        {
            ItemStack stack = event.entityPlayer.getHeldItem();
            Item item = stack != null ? stack.getItem() : null;
            EntityPlayer player = event.entityPlayer;
            //Gone Home
            if (item == BOPItems.enderporter)
            {
                player.addStat(BOPAchievements.use_enderporter);
            }
        }*/
    }
    ```

Just a guess

**Comment by deni500** [comment]
Fixed with new Aroma update.
