### ISSUE TITLE
Special armors do not affect body temperature

### ISSUE THREAD

**Issue by Twosiders** [Glitchfiend/ToughAsNails#225]
Jelled Slime Armor and Wool Armor do not decrease / increase the player's body temperature. I was wearing full slime armor yet I still overheated and died underground next to lava in about 3 seconds. I tested it, and it's as if I was wearing nothing at all!

**Comment by Adubbz** [comment]
That's completely intentional. Jelled Slime Armor and Wool Armor are not intended to prevent heating/cooling at all, but rather offset their effects.
