### ISSUE TITLE
Nighttime raises temperature instead of lowers

### ISSUE THREAD

**Issue by hanakocz** [Glitchfiend/ToughAsNails#234]
As title says, when it is nighttime, the temperature from "time" is positive, same as at day. It probably should be negative

![2017-05-01_18 48 11](https://cloud.githubusercontent.com/assets/8724169/25586284/ee877ebe-2e9e-11e7-83c9-c246873f59b4.png)

**Comment by CovertJaguar** [comment]
Ignore this, he's using our version.
