### ISSUE TITLE
[1.11.2] Rain Collectors from other Mods don't detect Rain

### ISSUE THREAD

**Issue by cyberpunkbln** [Glitchfiend/ToughAsNails#236]
Hello,

my Rain Tank from Forestry don't detect rain, when its raining. Without ToughAsNails all are good.

thx

Mod: ToughAsNails-1.11-2.0.5
Forge: forge-1.11.2-13.20.0.2286

PS: I deactivate all only Thirst in the configs, can it be that some code from temperatur or seasons will not be deactivated to run? I mean ENABLE_SEASONS? I can see that many many overwrites for the orginal weather system will not be triggered for the Var ENABLE_ ????

**Comment by Forstride** [comment]
This was likely related to this issue: https://github.com/Glitchfiend/ToughAsNails/issues/78

Which was fixed a few weeks ago, although there hasn't been an actual update released yet for it.

**Comment by cyberpunkbln** [comment]
Hi,
i see the commit is not in the cursforge 2.0.5 release. I have compiled the latest commits and now the bug is fixed. So the Solution is to compile the 1.11 branch with the latest commits. Thx for the tip. I think it is time for an actual curseforge release that other user that don't can compile, can use all commits.
Thx
