### ISSUE TITLE
temperature of hot spring water

### ISSUE THREAD

**Issue by FELITH** [Glitchfiend/ToughAsNails#237]
bop's hot spring water should give heat not cold.
ToughAsNails-1.11-2.0.5.jar
BiomesOPlenty-1.11.2-6.0.2.2157-universal.jar

**Comment by dcbartlett** [comment]
Duplicate of: https://github.com/Glitchfiend/ToughAsNails/issues/163

**Comment by Forstride** [comment]
Added this in the latest update to 1.12

**Comment by Woody-0w0** [comment]
Nicer to add config list for fluid block on which give heat
