### ISSUE TITLE
[1.11.2] [Suggestion] Configs for Drinks and Armours from Other Mods

### ISSUE THREAD

**Issue by Balketh** [Glitchfiend/ToughAsNails#240]
Would it be at all possible to add a way to configure drinks from other mods to restore configurable levels of thirst? Pam's and Cooking for Blockheads have a plethora of drinks (and foods, actually!) that should have a nice effect on Thirst, most of which are more mid-game crafting, and shouldn't invalidate the canteen, but allow for a more diverse set of survival choices.

In the same vein, would it be at all possible to add a way to configure armours from other mods to affect temperature? There are plenty of fire resist armours out there that should really allow us to work near lava sources and in the Nether, because as it stands with the Jellied Slime set, it's still really not enough to do extended lava work. Even if the config simply allows us to apply the Jellied Slime set hidden effect to other armours, this would be a great start. Tertiary suggestion addendum - fire resist enchants giving minor heat resist?

I wonder if it's possible to, rather than add/maintain configs for each item in each mod, include some kind of detection to generate configs based on armours and foods included in other mods?

Spitballing, but broad, gentle compatibility would be a lot better than hard-to-maintain specific mod compatibility, and much better than little to none.

Love the mod, many thanks for great improvements to the base game!

**Comment by Forstride** [comment]
There's already an issue for this: https://github.com/Glitchfiend/ToughAsNails/issues/9
