### ISSUE TITLE
Slow reflection in the API

### ISSUE THREAD

**Issue by Player3324** [Glitchfiend/ToughAsNails#245]
Frequently called methods like SeasonHelper.getSeasonData use reflection to lookup class + method references and invoke it, which is rather slow and causes significant performance impact overall.

There are 2 ways to fix this:

a) Cache the Method instance in a static final (!) field, just doing field.invoke() in getSeasonData. This is several orders of magnitude faster.

b) Change the API to use an interface and provide the reference to its implementation by setting a field from the core part of the mod.

For reference: http://files.player.to/tmp/tan-iswet.png

**Comment by Baylem** [comment]
<Nevermind>
