### ISSUE TITLE
[1.10] We need a temperature sensor...

### ISSUE THREAD

**Issue by Vectrobe** [Glitchfiend/ToughAsNails#247]
From what I've found so far in the particular biome I live in, you simply cannot rely on the season sensors alone to control your heating (or cooling) coil as you'll hit a midway where having a coil on will cook you, but leaving it off will freeze you or vice versa. Even with a complex timer loop, getting the timing right is far from simple...

**Comment by Forstride** [comment]
Duplicate Issue: https://github.com/Glitchfiend/ToughAsNails/issues/100

**Comment by Vectrobe** [comment]
Weird, why didn't I find that when searching for existing issues...
