### ISSUE TITLE
Heating coils have no effect

### ISSUE THREAD

**Issue by shivachirr** [Glitchfiend/ToughAsNails#248]
so i made house out of logs 2x2x2 space with one heating coil and as far as i can tell it has no effect. i am in a ice plains in winter but you think after a while in the box you should start warming up or stay warm when night drops another 7 points

**Comment by Adubbz** [comment]
This isn't how it works. Heating coils are not intended to provide a get-out-of-jail card for all cold situations. They instead offset the cold, making *most*, but not all, situations survivable. If you want to see if they're working, use a thermometer and see if it changes when you leave the house. Or, if you want exact numbers and don't mind cheating, use /tan tempinfo.

**Comment by shivachirr** [comment]
i know that but what im saying they are not heating my home and quickly getting hypothermal and dieing. the 2x2 box was a test

**Comment by Adubbz** [comment]
Yes, and what I'm saying is, that may not necessarily be incorrect behaviour. They may very well still be working, however the cold is to such an extreme extent that they will not heat you enough to prevent hypothermia.
