### ISSUE TITLE
Please add greedy option for bottles. (Consume the block of water)

### ISSUE THREAD

**Issue by Zaakjin** [Glitchfiend/ToughAsNails#249]

**Comment by Dominance** [comment]
https://minecraft.curseforge.com/projects/thirsty-bottles ?

**Comment by Adubbz** [comment]
This doesn't really make much sense. A bottle holds significantly less water than a bucket, and it can't place it back. Further, as water can be infinitely regenerated, there's just not much point for it to remove the block anyways.
