### ISSUE TITLE
Armour Suggestion

### ISSUE THREAD

**Issue by Ashonee75** [Glitchfiend/ToughAsNails#250]
Consider adding recipes to combine Jelled or Wool Armour with vanilla Armour pieces to create Chilled of Insulated versions.  IE combine wool chestpeice with iron chestplate for an insulated iron chestplate.

For balancing you could even make the chestplate somewhat less heating or cooling than the jelled or wool varient.

**Comment by shishketti** [comment]
If he does, he needs to do it though Enchantments / Meta, though shapeless crafting. Keeping mod armors in mind 😉.

**Comment by WolfieWaffle** [comment]
This would be good, maybe you could even have a special render override the glint and replace it with a fluffy or goey texture layer behind it that bleeds out of the edges, similar to TCon's dynamic textures. And have it be configurable percentage strength of the pure version.

**Comment by ghost** [comment]
Couldn't it be implemented as nbt data? Enchantments feel out of place to me. Lining armour with wool or pelts seems more fitting the theme. But that could just be me.
