### ISSUE TITLE
NoClassDefFoundError: net/minecraft/world/World

### ISSUE THREAD

**Issue by AlexCouch** [Glitchfiend/ToughAsNails#256]
Trying to use this mod as a dependency and when used, even installed in vanilla without any other mods, I get the following crash report:

https://pastebin.com/Xz0ZbqHf

Am I missing something? At first I thought it was the wrong version because I was using 1.11.2 so I ported to 1.11.0 but that didn't fix anything.

**Comment by Adubbz** [comment]
You are using TaN for 1.9.4 on 1.11.

**Comment by AlexCouch** [comment]
Yeah I'm no longer doing this, and this was back in may lol but thanks for the help anyways 😛

**Comment by Adubbz** [comment]
No worries, just going through some of the issue backlog right now

**Comment by AlexCouch** [comment]
Alright. Makes sense! ;P
