### ISSUE TITLE
Add config options

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#26]
Config options planned:

- Vanilla/TAN temperature values/rates for armor and other things
- Allowing additional health to reset upon death

A way to whitelist various things from other mods needs to be added as well:
- Modded armor temperature values
- Modded crops to die in winter

**Comment by Biochao** [comment]
As a modpack maker, it would be nice to have the ability to add drinks from other mods like Pam's Harvestcraft juices.

**Comment by Forstride** [comment]
Well, that's the idea.  We want to have an API so mods can just have compatibility automatically, but that would be good for any that don't.

We could also probably have it so any drinks that don't have a set value just give you like 2 thirst.

**Comment by darklordwonton** [comment]
It would also be nice to be able to change the amount of heat blocks produce, for instance if you wanted to make fire raise the temperature by 10 instead of by 1

**Comment by aliasless** [comment]
You should also add config options for the potion IDs used by the mod. I'm trying to create a modpack with this, but I need to change one of the potion IDs to prevent conflict with another.

(the other mod, btw, is IC2. I'm posting an issue on their issue tracker since their config option for the radiation potion ID doesn't do anything)

**Comment by WolfieWaffle** [comment]
I think config files like enviromine has would be useful. It allows you to specify the temperature value of any block, and the thirst/temperature/etc restored by any food. Depending on how your mod works, temperature might not be calculated with nearby blocks considered, but the ability to define any food item and the thirst it restores would be helpful.

I would also personally like the ability to disable the juices, in case there are juices already added, such as with harvestcraft. Not a priority, but it would help redundancy.

**Comment by Forstride** [comment]
Well, that's the plan for the config files.

As for disabling the juices, you can just not craft them...

**Comment by WesCook** [comment]
Would it be possible to allow seasons to have a configurable length?  In my case I find them far too short.  Winter would be much more devastating if it were 3-4 times longer, and required you actually live on reserves.
