### ISSUE TITLE
Thermometer Doesn't Work on Item Frame

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#260]
please fix this, thanks. 
used forge 2310, latest TAN

**Comment by HypnoPants** [comment]
I've tested this as well, I have minecolonies going and I've placed thermometers in the main square, along with season clocks and regular clocks.

The thermometers are the only ones that don't work in item frames.

**Comment by dcbartlett** [comment]
Also reporting as not working...If i get some time i'll try to get ti working and submit a PR.
