### ISSUE TITLE
No Ground Animals Spawning in Winter

### ISSUE THREAD

**Issue by saraminecraft** [Glitchfiend/ToughAsNails#261]
Hi! I am not sure what is causing this but when winter comes and I try and explore a new chunk there are no land animals (cows, pigs, sheeps, mod animals etc) spawning anywhere. Squids still spawn. Is this working as intended or do I have a possible mod conflict. I have disabled the temperature affecting players, lowered starting health, and the thirst features as I only wanted seasons. Please let me know if there is any additional information I can provide. Thank you so much for the amazing mod!!! <3 Sara

**Comment by saraminecraft** [comment]
Hi again:)  I tested this issue by removing your mod and running my server and animals spawn correctly when your mod is not installed. I think the problem is with the winter season as it is only during winter that ground animals stop spawning. Again is this working as intended?? If so I hate that feature because if i try to explore or do anything in winter there are no animals anywhere. If this is an intended feature can you possibly provide an option in the config file to still allow animals to spawn in winter? Let me know and thanks again for your time and effort!!!

**Comment by Adubbz** [comment]
This is indeed intentional, and is meant to encourage dealing with animals in the earlier seasons. I guess we can add a config option for it though
