### ISSUE TITLE
Configuration Issue? or is it a WIP? 

### ISSUE THREAD

**Issue by Baylem** [Glitchfiend/ToughAsNails#263]
So you guys seem to have a configuration:
https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/config/TANConfig.java

but the only one that gets generated is the Synced config, is there a specific reason?

**Comment by Adubbz** [comment]
Check the date of the commit versus the date of the latest release. We haven't made a new release yet because there are still temperature changes that need to be finished
