### ISSUE TITLE
Heat resistance potion recipe conflict

### ISSUE THREAD

**Issue by liach** [Glitchfiend/ToughAsNails#266]
Heat resistance potion's recipe conflicts with that of combustion potion from Not Enough Potions mod. On my case, the heat resistance potion win over the conflict. See https://github.com/Railcraft/RailcraftPatronServer/issues/48

**Comment by CovertJaguar** [comment]
This is because the fix from #253 hasn't been merged into 1.9/1.10

**Comment by liach** [comment]
Can be fixed in nep config
