### ISSUE TITLE
[Suggestion] Configure thirst values for other mod's foods

### ISSUE THREAD

**Issue by Luke616** [Glitchfiend/ToughAsNails#270]
Any way you guys could add a section in the configs to add thirst values to other mod's foods / edit existing thirst values? Playing with mods like Pam's that add drink items, and it feels silly to drink a smoothie and have it only refill hunger. Would love to be able to edit these values.

Thanks!

**Comment by Forstride** [comment]
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/9
