### ISSUE TITLE
Game Won't Start

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#271]
TAN build .35 is uncompatible with latest Forge 2344, game won't start.

**Comment by ghost** [comment]
[fml-client-latest.log.txt](https://github.com/Glitchfiend/ToughAsNails/files/1094682/fml-client-latest.log.txt)

**Comment by Adubbz** [comment]
Fixed with https://github.com/Glitchfiend/ToughAsNails/commit/e391a1349f3f6156373ed57fc537d0aae91b6948
