### ISSUE TITLE
Season temperatures are weird

### ISSUE THREAD

**Issue by axeladalidez78** [Glitchfiend/ToughAsNails#272]
This is a table of the temperatures of seasons according to the version "ToughAsNails-1.11.2-2.1.0.36-universal" by default.

Early_Spring 4 -> The temperature transition between late winter to early spring is too high.
Mid_Spring  6
Late_Spring  4 -> For some reason it lowered

Early_Summer -5 -> ????
Mid_Summer  0
Late_Summer 2

Early_Autumn 2
Mid_Autumn  0
Late_Autumn -3

Early_Winter   -7
Mid_Winter    -15
Late_Winter   -10

**Comment by Forstride** [comment]
Fixed for 1.12, and a fix for 1.11.2 will be coming shortly, although you can just swap the spring/summer temps in the meantime.

**Comment by axeladalidez78** [comment]
I have already done that but thanks!
