### ISSUE TITLE
Climatisation effect doesn't wear off

### ISSUE THREAD

**Issue by axeladalidez78** [Glitchfiend/ToughAsNails#273]
Hello again.

So I had a building that had a heating coil with a winter sensor. Then winter came and when I left my house, the effect was still there. I waited like 1 to 2 minutes and the effect was still there, I tried destroying the heating coil but the effect it's still there.
The only way I found how to fix it it's by dying.

**Comment by Adubbz** [comment]
Can reproduce this, thanks
