### ISSUE TITLE
Potion effect icons are broken in the latest version (1.1.1.19)

### ISSUE THREAD

**Issue by Dune-Jumper** [Glitchfiend/ToughAsNails#276]
For example when you drink dirty water the thirst debuff potion icon is just a black square. This is on the 1.10.2 version.

**Comment by Adubbz** [comment]
This would be something for @liach, since we're no longer working on 1.10

**Comment by liach** [comment]
Confirmed this issue. Originally I didn't even think that it's a bug...

**Comment by Forstride** [comment]
It's broken in 1.11.2 and 1.12 as well

**Comment by axeladalidez78** [comment]
Thought it was a minecraft vanilla problem, oh well.

**Comment by BuilderDan** [comment]
Guessing this'll be fixed soon.
