### ISSUE TITLE
Increasing day duration ticks in config doesn't appear to have any effect.

### ISSUE THREAD

**Issue by SwordShaman** [Glitchfiend/ToughAsNails#277]
I've attempted to extend the day/night cycle by increasing the seasons config "Day Duration" to both 48000 and 96000 and have tested it by recreating the world and waiting to see how long the cycle lasts.  It should be double and quadruple the amount of daytime, respectively.  I've found that it appears to have no effect.  This is the 1.11.2 version, specifically 2.1.0.39

With the recent updates you've made me a very happy man.  I've been really craving being able to play with the nuts and bolts of your mod for a while now.  Thank you for providing more config options!  It's greatly appreciated!

Hopefully we can sort out what's causing this issue.  Take care!

**Comment by Adubbz** [comment]
This actually is intentional, since it’s mainly intended to extend the day duration used by seasons as opposed to the days themselves. This was mainly intended for use in conjunction with some other mod that modified the day length. However, Forstride had the same initial reaction so I guess I’ll leave this open

**Comment by SwordShaman** [comment]
I see.  If you could manage to make it modify day length, that'd be amazing.  I've been waiting for anything on 1.11.2 but have come up empty handed at the moment.  The mod Hard Mode Tweaks used to provide a way to extend the day cycle but it hasn't been updated and I don't know of any others that do anything similar.  If you know of any, could you provide their names?  Thanks for the speedy reply!

**Comment by shootHug** [comment]
the mod Primal adds a config option for longer day/nights

**Comment by Tumlinh** [comment]
Stellar Sky provides an API for changing day length.
Otherwise I used to tinker with Minecraft physics, I can open a pull request if you want.
