### ISSUE TITLE
Player gets wet without reason (Even on snow?)

### ISSUE THREAD

**Issue by axeladalidez78** [Glitchfiend/ToughAsNails#278]
So, for some reason, my character gets wet on snow.
You see, that's not really normal but either weird, but then I realized it happened without any reason like this:
![2017-06-23_15 21 35](https://user-images.githubusercontent.com/6802783/27484095-3a5952ce-5828-11e7-8a9a-147fa0a21aeb.png)
![2017-06-23_15 21 31](https://user-images.githubusercontent.com/6802783/27484096-3a63513e-5828-11e7-83dd-c2d7b8db97ac.png)

By the way, I just moved my character one/two blocks. I think it has something to do with being under or next to a roof, noticed this effect really often next to trees.

**Comment by Forstride** [comment]
I've definitely seen this happen myself, so I can confirm it

**Comment by Baylem** [comment]
If I get time, I will address this in my PR I'm doing soon

**Comment by scigeotech** [comment]
wait a minute - isn't it snowing in your screenshot?
