### ISSUE TITLE
Important Need/Suggestion

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#279]
leather armor should keep warm such as wool armor. please add this or add config to add armors that will keep warm and also temperature modifier for them too. (for wool:1)
thanks.
MC 1.12

**Comment by Forstride** [comment]
Leather should not give as much heat as wool.  Leather does not keep you nearly as warm as wool does IRL.

As for the other suggestion, we already have multiple issues open for config options like that.
