### ISSUE TITLE
Charcoal filter is not craftable for me

### ISSUE THREAD

**Issue by Cherryxoxo** [Glitchfiend/ToughAsNails#291]
I have recently installed ToughAsNails mod version 1.12 and the only item that I cant craft is Charcoal Filter
I have the necessary ingredients and It doesn't seem to craft
I go on a different world that is creative and I can access the item only on Creative Mode but I need help with crafting this in survival

**Comment by Derpwarrior555** [comment]
Same here dude, Its quite annoying not being able to craft Charcoal Filters

**Comment by bob0bob** [comment]
That is weird, I"m using 3.0.0.62 and i can make filters with ppp ccc ppp.

**Comment by EPIICTHUNDERCAT** [comment]
has this been fixed? or still having issues

**Comment by EPIICTHUNDERCAT** [comment]
if its fixed this can be closed, according to bob0bob it is.

**Comment by Adubbz** [comment]
The recipe was updated but the wiki wasn't. This has been fixed now
