### ISSUE TITLE
In forest under the leaves are too hot in summer

### ISSUE THREAD

**Issue by DcNdrew** [Glitchfiend/ToughAsNails#297]
Do the shadows cause falling in temperature? Because if I go out in a forest IRL, under the leaves in summer, or even if I'm on the plains the temperature is lower than in the city.

**Comment by scigeotech** [comment]
shadows and temperature are two different things here. shadows are just to make MC look a lot better.

**Comment by DcNdrew** [comment]
No. Shadows means shadows. Where the Sun doesn't shine. Where the mob or block or player can't see the sky above.

**Comment by scigeotech** [comment]
no, look. the lighting system does NOT affect the mod at all. shadows were just added to make everything look good and it does not do anything to the mod. Clearly they are two different things and you should do some more research.

**Comment by DcNdrew** [comment]
Do you remember what happened in 1.7? There were red and yellow X-es on the floor. Red X-es meant there will always be shadows, doesn't matter if there is day or light. Yellow meant they are under light level 7 only at night.

https://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/net/minecraft/world/World.html#canSeeSky(net.minecraft.util.BlockPos)

So there is a way to say if you are under something or not. Enviromine could do the same. 

Do you understand what am I talking about?

**Comment by scigeotech** [comment]
but this is not an issue. TAN never added a feature where you could get under a block and cool down. so why was this even opened, without being labeled as a suggestion or whatsoever?

**Comment by DcNdrew** [comment]
Because I'm not a modder, I didn't read the code, I didn't know if it's a bug or just not implemented. I just found myself dying in a horrible burn in a quite comfy forest.

**Comment by Forstride** [comment]
It's not a bug, and it's not unimplemented.  Light levels are a bad way to control temperature, because the player likely isn't going to pick up on it.  Shadows don't really work the same way in Minecraft as they do in real life.
