### ISSUE TITLE
[1.11.2-2.1.0.51] World loading stuck on 0%

### ISSUE THREAD

**Issue by rinart73** [Glitchfiend/ToughAsNails#299]
So, it goes through "Building world", "Generating Terrain" and it's stuck on "0%" then.
No crash, no freeze, no extensive CPU or memory using. It's just stuck forever.

I tried "release" version (1.11.2-2.1.0.36) too. Same thing. I tried to load/create world without it and it works perfectly.

Here is my mod list:
[1.11]MoVillages-1.5.3.jar
Baubles-1.11-1.4.5.jar
BiblioCraft[v2.3.2][MC1.11.2].jar
BiomesOPlenty-1.11.2-6.2.0.2267-universal.jar
Botania r1.9-344.jar
CoralReef-1.4.jar
CraftTweaker-1.11.2-3.0.26.jar
CustomNPCs_1.11.2(25may17).jar
dailies-1.11.2-6.jar
embers-0.220.jar
gravestone-1.6.6.jar
InventoryTweaks-1.62.jar
ironchest-1.11.2-7.0.25.815.jar
jei_1.11.2-4.5.0.291.jar
liteloader-1.11.2-SNAPSHOT-release.jar
Mantle-1.11.2-1.2.0.26.jar
missing_pieces-1.11.2-4.3.0.jar
mod_voxelMap_1.6.23_for_1.11.2.litemod
MouseTweaks-2.8-mc1.11.2.jar
NaturesCompass-1.11.2-1.3.0.jar
NoMoreRecipeConflict-0.8(1.11).jar
OceanFloor-1.11-1.0.1.jar
OpenGlider-1.11.2-1.0.0.jar
OptiFine_1.11.2_HD_U_C3.jar
TConstruct-1.11.2-2.7.0.26.jar
Waila-1.7.1_1.11.2.jar
WailaHarvestability-mc1.11-1.1.10.jar
Wawla-1.11.2-2.4.0.231.jar

**Comment by Adubbz** [comment]
We need logs, also try without Optifine and liteloader
