### ISSUE TITLE
Wool armor is as good as leather armor - does not make sense at all

### ISSUE THREAD

**Issue by SamGunGraven** [Glitchfiend/ToughAsNails#303]
Currently a full set of wool armor is as good as a full set of leather armor for protection. This does not make sense at all. Either reduce the wool armor protection (f.ex. wool boots are better than leather boots) or make it configurable for modpack authors to do balancing.

**Comment by bob0bob** [comment]
I agree also.

**Comment by RoboMedZi** [comment]
Well, the wool in this game is pretty solid. It breaks as fast as dirt, so it actually does make sense.

**Comment by insanityseanboy** [comment]
I also noticed that the wool boots have a pretty solid armour rating -- only slightly worse than iron boots. The other wool options are significantly worse than their iron versions. I'm not sure I've ever made leather armour before getting enough iron to make iron armour. I think wool armour is balanced as is, and it's rather that leather armour is so low quality for how hard it is to acquire before it becomes obsolete.

If it's coming from a realism perspective, then think of wool armour less like a woollen jumper and more like a sheep hide jerkin; basically leather + insulation.
