### ISSUE TITLE
Juice Recipes

### ISSUE THREAD

**Issue by rckymtnrfc** [Glitchfiend/ToughAsNails#305]
I just noticed all the juices are requiring an "Uncraftable Potion" instead of a water bottle.  I'm assuming this is a bug since you can't craft an uncraftable potion.

Forge 
ToughAsNails-1.12-3.0.0.60-universal

Thank you,

**Comment by Forstride** [comment]
Any potion item should work.  At least, it did when I was testing it.  I couldn't find a way to actually make it require a water bottle with the new recipe system.

**Comment by rckymtnrfc** [comment]
Confirmed, it works with water.  I didn't think to test it, just saw the recipe in JEI was wrong.

Thanks
