### ISSUE TITLE
(suggestion) tiring system

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#308]
I really would want to see a tiring system added to TA. It would be a bar with beds which will decrease really slowly, and when reach 0 you get effect blindness, weakness, mining fatigue... and you start to loose health. Fore getting fine again it would need to sleep. It would give more importance to sleep system and make it make the game more realistic and complex. I think it's really the thing which misses to TAN for being perfect. It would be awesome if it was added.

**Comment by DcNdrew** [comment]
Better Sleeping actually does this. :)

**Comment by Forstride** [comment]
fatigue mechanics in most games are usually terrible and annoying, so i doubt i'd ever add this

**Comment by 0Navis0** [comment]
Better Sleeping actually doesn't work good. ^^'
It could be added as an option. ;)
