### ISSUE TITLE
GUI configuration

### ISSUE THREAD

**Issue by DerekS2** [Glitchfiend/ToughAsNails#309]
Is there a way to modify the temperature and thirst GUI?  I need to change the position on the screen in order to avoid overlap with another GUI mod (RPG-Hud).

If editing this in the configs is not possible, let this be a formal request for the feature.

**Comment by DerekS2** [comment]
A similar issue/request: ToughAsNails issue #183

**Comment by Forstride** [comment]
HUD issues should be fixed now.
