### ISSUE TITLE
Cyberware Compatibility Issue

### ISSUE THREAD

**Issue by Megafoan** [Glitchfiend/ToughAsNails#310]
Cyberware's cyberware that is meant to interact with Tough As Nails' temperature (the sweat glands and the blubber) does not appear to actually modify the temperature gain or loss to my knowledge, based on watching the /tan tempinfo. I am running Cyberware 0.2.10 and Tough As Nails 2.1.0.51.

**Comment by Forstride** [comment]
Report it to them

**Comment by Megafoan** [comment]
Right-o. My bad.
