### ISSUE TITLE
[Wiki] Wrong recipes for Charcoal Filter

### ISSUE THREAD

**Issue by Akzyra** [Glitchfiend/ToughAsNails#315]
86a21add1e695a6c8a4095819498c45cda09d799 changed it, Image in [Wiki ](https://github.com/Glitchfiend/ToughAsNails/wiki/Charcoal-Filter)is still the old one.

Explains issues like # #291

**Comment by MoonlightOwl** [comment]
Here is the new picture, btw.
![filter-recipe](https://user-images.githubusercontent.com/7950282/30021630-48d8f470-9168-11e7-9920-ef3b33763aee.png)

**Comment by Adubbz** [comment]
Updated it, thanks
