### ISSUE TITLE
crash with extra utilities and nether ex

### ISSUE THREAD

**Issue by cursinorock** [Glitchfiend/ToughAsNails#316]
Crash when laucher minecraft on version 1.11.2 
forge 1.11.2-forge1.11.2-13.20.1.2425

[crash-2017-07-29_13.19.57-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1185078/crash-2017-07-29_13.19.57-client.txt)

[crash-2017-07-29_13.17.51-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1185079/crash-2017-07-29_13.17.51-client.txt)

**Comment by 0Navis0** [comment]
I get the same crash. :(

**Comment by EPIICTHUNDERCAT** [comment]
was this fixed?

**Comment by Hypsellis** [comment]
No it's not, but it works on 1.12.1. The problem seems to come from TAN which do something wrong on 1.11.2
