### ISSUE TITLE
Installer doesn’t want to launch on OS X El Capitan

### ISSUE THREAD

**Issue by riddle** [Glitchfiend/ToughAsNails#32]
OS X 10.11.5 (15F34)
Running: Java 8 Update 71

I downloaded `ToughAsNails-1.0.1.jar` and opened it. It fails to launch and after a few tries the system tells me

<img width="532" alt="screen shot 2016-06-21 at 08 57 34" src="https://cloud.githubusercontent.com/assets/49703/16220618/35e95420-378e-11e6-8965-020472c2a159.png">

Nothing of interest is printed to console (I narrowed it searching for `java`).

I have a vanilla 1.9.4 profile which I opened at least once. It just doesn’t want to run properly. Is there any other way I can install the mod?

**Comment by Adubbz** [comment]
Huh? This is a Forge mod, not an installer. 

Here's a quick summary of what you need to do:
1. Download the latest version of Forge for 1.9.4 from http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.4.html and run Forge installer.
2. Create a brand new profile in the Minecraft launcher and change the version to  release 1.9.4-forge<numbers>, then run the game. 
3. A 'mods' folder in your game directory should be created where you can drop in the ToughAsNails jar file, run the game again, then you're all set!

**Comment by riddle** [comment]
I feel so dumb. Thank you for correcting me and sorry for wasting your time!

**Comment by Adubbz** [comment]
No worries :)
