### ISSUE TITLE
[Resource] es_MX / es_ES translation

### ISSUE THREAD

**Issue by Dorzar** [Glitchfiend/ToughAsNails#320]
//Translate by: Dorzar / VeryHardChamp
//Act.: 30/07/2017
achievement.thirst_quencher=Bebida refrescante
achievement.thirst_quencher.desc=Elaborar una cantina de cuero
achievement.thirst_ender=Sed de Ender
achievement.thirst_ender.desc=Hacer una Frasco de zumo de fruta refrescante
achievement.campfire_song=Canción de la hoguera
achievement.campfire_song.desc=¡Encienda una fogata hecha de troncos y adoquines!
achievement.into_ice=En el hielo
achievement.into_ice.desc=Convierte el hielo en un bonito palo
achievement.hot_or_cold=Caliente o frío
achievement.hot_or_cold.desc=Elabora un termómetro de diamantes y cuarzo
achievement.that_time_of_year=Esa época del año
achievement.that_time_of_year.desc=Elaborar un reloj de temporada con cuarzo y redstone
achievement.year_one=Año 1
achievement.year_one.desc=¡Sobrevive un año entero!
achievement.life_or_death=Vida o muerte
achievement.life_or_death.desc=¡Busca botines en las fortalezas del Nether para aumentar tu salud!

commands.toughasnails.usage=/toughasnails <tempinfo|settemp|setseason> [args]
commands.toughasnails.settemp.success=Set player temperature to %s
commands.toughasnails.settemp.disabled=Body Temperature is currently disabled!
commands.toughasnails.setseason.success=Set season to %s
commands.toughasnails.setseason.fail=Invalid season %s
commands.toughasnails.setseason.disabled=Seasons are currently disabled!

config.category.survivalSettings.title=Survival Settings

itemGroup.tabToughAsNails=Tough As Nails

tile.campfire.name=Hoguera
tile.dead_crops.name=Cultivos muertos
tile.rain_collector.name=Colector de lluvia
tile.temperature_coil.cooling_coil.name=Bobina de refrigeración
tile.temperature_coil.heating_coil.name=Bobina de calentamiento
tile.season_sensor_spring.name=Sensor de temporada
tile.season_sensor_summer.name=Sensor de temporada
tile.season_sensor_autumn.name=Sensor de temporada
tile.season_sensor_winter.name=Sensor de temporada
tile.torch_new.name=Antorcha

item.air_filter.name=Filtro de aire
item.bottle_of_blackdamp.name=Frasco de Blackdamp
item.bottle_of_whitedamp.name=Frasco de Whitedamp
item.bottle_of_firedamp.name=Frasco de Firedamp
item.bottle_of_stinkdamp.name=Frasco de Stinkdamp
item.clean_water_canteen.name=Cantina de agua limpia
item.charcoal_filter.name=Filtro de carbón
item.dirty_water_canteen.name=Cantina de agua sucia
item.dirty_water_bottle.name=Frasco de agua sucia
item.empty_canteen.name=Cantina
item.filtered_water_canteen.name=Cantina de agua filtrada
item.filtered_water_bottle.name=Frasco de agua filtrada
item.freeze_powder.name=Polvo de freeze
item.freeze_rod.name=Vara de freeze
item.ice_charge.name=Carga de hielo
item.ice_cube.name=Cubo de hielo
item.jelled_slime.name=Slime congelado
item.jelled_slime_helmet.name=Casco de slime congelado
item.jelled_slime_chestplate.name=Pechera de slime congelado
item.jelled_slime_leggings.name=Pantalones de slime congelado
item.jelled_slime_boots.name=Botas de slime congelado
item.juice_apple.name=Jugo de manzana
item.juice_beetroot.name=Jugo de remolacha
item.juice_cactus.name=Jugo de cactus
item.juice_carrot.name=Jugo de zanahoria
item.juice_chorus_fruit.name=Jugo de fruta de coral
item.juice_glistering_melon.name=Jugo de patilla reluciente
item.juice_golden_apple.name=Jugo de manzana dorada
item.juice_golden_carrot.name=Jugo de zamahoria dorada
item.juice_melon.name=Jugo de patilla
item.juice_pumpkin.name=Jugo de auyama
item.lifeblood_crystal.name=Corazòn de cristal
item.respirator.name=Respirador
item.season_clock.name=Reloj de la temporada
item.spawn_egg_freeze.name=Generar freeze
item.tan_icon.name=TAN Icon
item.thermometer.name=Termómetro
item.wool_helmet.name=Capucha de lana
item.wool_chestplate.name=Chaqueta de lana
item.wool_leggings.name=Pantalones de lana
item.wool_boots.name=Botas de lana

potion.hypothermia=Hipotermia
potion.hyperthermia=Hipertermia
potion.thirst=Sed
potion.cold_resistance=Resistencia al frío
potion.heat_resistance=Resistencia al calor

potion.effect.cold_resistance_type=Poción de resistencia al frío
potion.effect.long_cold_resistance_type=Poción de resistencia al frío
potion.effect.heat_resistance_type=Poción de resistencia al calor
potion.effect.long_heat_resistance_type=Poción de resistencia al calor

splash_potion.effect.cold_resistance_type=Poción de resistencia al frío arrojadiza
splash_potion.effect.long_cold_resistance_type=Poción de resistencia al frío arrojadiza
splash_potion.effect.heat_resistance_type=Poción de resistencia al calor arrojadiza
splash_potion.effect.long_heat_resistance_type=Poción de resistencia al calor arrojadiza

lingering_potion.effect.cold_resistance_type=Poción de resistencia al frío persistente
lingering_potion.effect.long_cold_resistance_type=Poción de resistencia al frío persistente
lingering_potion.effect.heat_resistance_type=Poción de resistencia al calor persistente
lingering_potion.effect.long_heat_resistance_type=Poción de resistencia al calor persistente

tipped_arrow.effect.cold_resistance_type=Flecha de resistencia al frío
tipped_arrow.effect.long_cold_resistance_type=Flecha de resistencia al frío
tipped_arrow.effect.heat_resistance_type=Flecha de resistencia al calor
tipped_arrow.effect.long_heat_resistance_type=Flecha de resistencia al calor

entity.freeze.name=Freeze

**Comment by EPIICTHUNDERCAT** [comment]
Hey, best way to do this is to submit a pull request. Just makes things easier for them and faster for you.

Para que ellos lo vean as un "Pull Request". esto lo hace mas facil para que ellos lo usen y tambien lo hacen mas rapido!

**Comment by Adubbz** [comment]
Yup, a pull request is the better way to go about this. Closing this
