### ISSUE TITLE
weird biome temperatures 

### ISSUE THREAD

**Issue by shootHug** [Glitchfiend/ToughAsNails#321]
Hey, thx to that realistic touch you give to Minecraft!
But I have some issues with temperatures in certain Biomes...
for example: I am in a forest and burn to death in the Summer??
I think that a forest should burn, when it's this hot.
So my request is:
Could you add a Option in the configs, where we can assign Biom-types to temperatures,
it would make the mod a lot better, I think.
Greetings 
shootHug

**Comment by DcNdrew** [comment]
This is exactly what I can't understand either. I suggested the leaves should cool you down if you are under them. The answer was a no, because the light level for calculating temperature is a wrong way.
