### ISSUE TITLE
1.12 - Crash on startup with Liteloader or Optifine

### ISSUE THREAD

**Issue by BitBlitObviMormon** [Glitchfiend/ToughAsNails#328]
When either Liteloader or Optifine is installed Tough As Nails crashes before Forge can initialize. No other mods are installed, and I suspect there may be a problem with one of the core transformers. Logs of each crash are kept below:

[fml-client-latest - Optifine.log](https://github.com/Glitchfiend/ToughAsNails/files/1266106/fml-client-latest.-.Optifine.txt)
[fml-client-latest - Liteloader.log](https://github.com/Glitchfiend/ToughAsNails/files/1266105/fml-client-latest.-.Liteloader.txt)

**Comment by Adubbz** [comment]
We don't support Liteloader or Optifine.
