### ISSUE TITLE
Tall Grass

### ISSUE THREAD

**Issue by HypnoPants** [Glitchfiend/ToughAsNails#331]
So I noticed when spring comes around, new grass and flowers grow... which is amazing, except for one problem... the tall grass remains thick and green during the winter and totally ruins the effect/feel of it.

Perhaps in Autumn the tall grass could turn to small grass (or just disappear) and in winter that small grass disappears.

I say all this because I destroyed all the tall grass last winter, and it came back...

**Comment by Adubbz** [comment]
I'm a bit confused... TaN doesn't have any mechanics for growing plants based on the season...? Are you sure it's not some other mod?

**Comment by HypnoPants** [comment]
It might be... but that confuses me more since the grass only grew back in the spring... I'll look into it.

**Comment by HypnoPants** [comment]
yeah it's terraqeuous... apparently, it may be a fluke, but the grass blocks seem to spawn tall grass which grows into double tall grass. And I think I thought it was spring causing it because the grass never really grew back until spring hit, but it grew back FAST.

**Comment by EPIICTHUNDERCAT** [comment]
Yep, This is terraqueous doing it @HypnoPants kinda annoying lol
