### ISSUE TITLE
Bug with mod interaction Dissolution

### ISSUE THREAD

**Issue by darkshadow543** [Glitchfiend/ToughAsNails#333]
When you use this mod with Dissolution, which makes you a ghost when you die, it shows the water and temperature meters when you have become a ghost.  Is there any way to fix this or add mod integration?
Mod Version:
Dissolution 0.4.3.2
Tough as Nails 2.1.0.36
MC Version: 1.12.1
Forge Version 14.22.0.69

**Comment by godemperoroftheworld** [comment]
Can confirm the issue still occurs with 1.12.2 and the latest version of both mods.

**Comment by koravel** [comment]
Found new bug - when you enter pigman body - you can die from hyperthermia. And similar behaviour with zombie and hypothermia.
