### ISSUE TITLE
Ridding Horse

### ISSUE THREAD

**Issue by bob0bob** [Glitchfiend/ToughAsNails#334]
When your on a horse your gauge for your temperature disappears?  I can't tell if it stops working altogether or not.

Was it intentional for the gauge to go away on a horse?

**Comment by EPIICTHUNDERCAT** [comment]
I think being on the horse takes away the hunger bar as well, may be intentional to fit that vanilla way.

**Comment by Adubbz** [comment]
Yes, this is intentional as it is what Vanilla does with hunger.
