### ISSUE TITLE
Multiple Temperature

### ISSUE THREAD

**Issue by bob0bob** [Glitchfiend/ToughAsNails#335]
The code should look for the highest or lowest temperature to figure out what is needed.   So if you say "Torch" level 4:   but a furnace level 20:.    If the search finds torch first.  It aborts but you are also beside furnace and your temperature adjustment is 4:.

So if you are standing on snow with a level -10:  but beside a furnace with a 20:.    It should average it or something.  Should keep a list of affects.   If blocks are negative and some are positive.  Then do an average.  If it is all positive or all negative.  Then select the largest.

I'm standing on mossy cobblestone,  which I gave it a -2: being cooler.   but standing beside netherrack on fire.  Fire material doesn't affect temperature since you found a block temperature.  At least that appears to happen.

**Comment by ghost** [comment]
I agree. I would think it should work much like sky/block light works. The heat radiates out say 15 blocks deminishing. The temp on a position would be: ambient temp + block level heat. This would allow for negative radiation temps and cumulative heatinf as well.
