### ISSUE TITLE
NPE ObjectProximityModifier.getBlockTemperature

### ISSUE THREAD

**Issue by flapee** [Glitchfiend/ToughAsNails#336]
ModPack Forever stranded 

detailed crash log
[2017-09-10-3.log.gz](https://github.com/Glitchfiend/ToughAsNails/files/1290585/2017-09-10-3.log.gz)

**Comment by flapee** [comment]
The older version (ToughAsNails-1.9.4-1.1.1) works just fine

**Comment by Adubbz** [comment]
Update the mod, the fix is included in 1.9.4-1.1.1.66 and later.
