### ISSUE TITLE
Campire collision takes entire block.

### ISSUE THREAD

**Issue by madhatr** [Glitchfiend/ToughAsNails#337]
Is it possible to fix the collision/ray detection of the campfire.  It is not possible to "see" past it with tools.  I've ruined them many times attempting to mine the blocks behind them in areas that should be see through but are registered as still on the campfire.

**Comment by WolfieWaffle** [comment]
The way MC works I think it would still have to be a solid cuboid, but they could definitely move it down so its just over the rocks.

**Comment by madhatr** [comment]
I don't believe so, there are blocks I am able to see through to mine to the block behind it.  The chest for example. I'll go in and confirm and report back later.  Playing Civ 6 atm.

**Comment by WolfieWaffle** [comment]
Yes, but only on the edges. You can't click through a hole in the middle of the chest. Now granted I have seen some mods that seem to have more complex block hitboxes, but for this I think it would be sufficient to just scale the box down on the y axis a bit.

**Comment by madhatr** [comment]
Oh okay, you guys are the wizards. :)  I never went into test, also got into GTA V online finally.

I like the idea of scaling the box down some.
