### ISSUE TITLE
Allow automated filtering and bottle filling

### ISSUE THREAD

**Issue by viveleroi** [Glitchfiend/ToughAsNails#339]
I would appreciate having some way of automating bottle filtering/filling. I didn't at first realize that I couldn't use the Immersive Engineering bottler so was disappointed.

This was somewhat mentioned by people in #40 and possibly relates to #268, but I didn't see any issue specifically addressing automation.

Ideally I'd like to be able to use other mod's machines to fill bottles  (even with just dirty water pumped from a water source), then use a machine to filter them (ideally with replaceable filters, but stronger ones with longer use), and then it's trivial to automate boiling them.

Thanks!

**Comment by Math321** [comment]
Any autocrafter can handle the filtering using charcoal filters. As for bottling the dirty water, you need something that can right click for you - an OpenComputers robot or a ComputerCraft turtle. So it's already possible to make clean water automatically, using various mods.

That said, I do agree with you - I'd like something from TAN that can do it, too. What do you think, Mr/Mrs/Ms Developer?

**Comment by Forstride** [comment]
TAN isn't a tech mod, so no, we're not adding a native automation process.  Now, if there's an issue preventing those things in other mods from working, that's another story.
