### ISSUE TITLE
season feature breaks certain maps

### ISSUE THREAD

**Issue by corbinite** [Glitchfiend/ToughAsNails#340]
I've noticed that the way the mod adjusts sapling drops depending on season breaks certain survival maps, like skyblock maps. If the map starts off on the wrong season you're pretty much out of luck. Could a config option be added to allow the sapling drop rates to remain at default vanilla values?

**Comment by Adubbz** [comment]
We definitely don't adjust sapling drops based on the season. This would be some other mod.
