### ISSUE TITLE
[1.11.2] World Stuck at StartUp - Bytecode?

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Glitchfiend/ToughAsNails#341]
This happens as I try to login to a single player world in Minecraft 1.11.2

https://pastebin.com/FFsT0UWH

You can see Versions of mod and forge in the crashlog if you'd like.

**Comment by Sunconure11** [comment]
I encountered something similar when I tried to pick up a coil from this mod using Carry On.

**Comment by Adubbz** [comment]
I believe this is an issue with RandomThingsCore, they had some dodgy ASM which I debugged with Tahg in IRC awhile back. We had a workaround in the past, however that broke other more important things like rain.  You're best off asking them to look into it.

**Comment by EPIICTHUNDERCAT** [comment]
@Adubbz was there a concluded fix? remove RandomThingsCore?

**Comment by Adubbz** [comment]
Removing it should fix it, yes.
