### ISSUE TITLE
[Suggestion] Water Stacking

### ISSUE THREAD

**Issue by Ankido** [Glitchfiend/ToughAsNails#346]
The most annoying thing is having bottles not stacking in your inventory.  Can you make it stack?

**Comment by Forstride** [comment]
no.  they don't stack in vanilla.  why would we make them stack in TAN?

**Comment by Ankido** [comment]
Who cares about vanilla.  The addon completely changes how minecraft is and you say no to stacking?  I'm confused.

**Comment by Forstride** [comment]
use a canteen.  allowing water bottles to stack would make the mod way too easy
