### ISSUE TITLE
Thirst not draining, despite not having it shut off

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/ToughAsNails#349]
Keep in mind this is happening on 1.11.2

Forge version used is 13.20.1.2476

**Comment by Sunconure11** [comment]
Config settings:

https://www.dropbox.com/s/c2rfr407lni7brz/config22s.zip?dl=0

**Comment by Adubbz** [comment]
What difficulty is the game set to? If it is peaceful then this is intentional

**Comment by Sunconure11** [comment]
I am legitimately not what caused this issue, but while it was not peaceful, the issue seems to have resolved itself.
