### ISSUE TITLE
[1.12.1][Mod Compat] Please oredict freeze rods with Thermal Expansion blizz rods (rodBlizz)

### ISSUE THREAD

**Issue by Alaberti** [Glitchfiend/ToughAsNails#353]
The relevant oredict entry is rodBlizz, it drops from the blizz mob which is functionally identical to the freeze. Thank you for your time.

![2017-09-21_10 00 42](https://user-images.githubusercontent.com/10929796/30702879-c3c6071a-9eb3-11e7-8c52-41ded6cedd63.png)

**Comment by KnightMiner** [comment]
Sounds like the same should be done with powders too
