### ISSUE TITLE
Crops not being affect by cold weather

### ISSUE THREAD

**Issue by bob0bob** [Glitchfiend/ToughAsNails#356]
Before anyone says it.  I have the following in the config:
    # Kill unheated crops during the winter [default: true]
    B:"Enable Winter Crop Death"=true

What I'm seeing if I use biome tweaker.   I created a world where it is cold and frozen all year around.  But Survivalist doesn't kill crop until winter comes around.  Even Vanilla crops.   Even if the temperature is set to .01  for the base biome.  Crops can grow until winter comes around.

Crop death should be based on temperature only not season.

**Comment by Forstride** [comment]
Closing this since we're moving seasons to a separate mod (https://github.com/Glitchfiend/SereneSeasons).
