### ISSUE TITLE
Mod needs better compatibility with other mods that allow for more health

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/ToughAsNails#357]
If a mod tries to add additional health, it will often spam a red particle effect around the health bar, almost like redstone. In addition, any GUI changes done by other mods are simply not picked up by this mod, even with changes to health off. While not the end of the world, it is annoying. The only mod I am aware of that is able to get around these changes is glass hearts.

**Comment by Adubbz** [comment]
We use Vanilla's existing mechanism for lowering the player's default health. Hence, I think it is reasonable to place the onus on other mods for supporting this.
