### ISSUE TITLE
Season sensor emit a wrong power with mid season

### ISSUE THREAD

**Issue by NeutronSelector** [Glitchfiend/ToughAsNails#358]
The season sensor emit a power of 11 on first stage of the mid season (winter, spring, summer and autumn) and emit a power of 10 on first stage of the late season. For me, the season sensor must emit a power of 6 on first stage of the mid season. 

It's so boring for automatizate a heating system in a home :/

**Comment by Adubbz** [comment]
This is expected. Season sensors operate based on the overall season, not whether it is early/mid/late summer/autumn/winter/spring.  Early/mid/late are just arbitrary segments we chose to divide the season into, not specific points in time. Hence, the mid season *includes* the middle of the season, as well as a bit of time before and after. Thus, it is entirely expected that at the beginning of the mid season segment the power would not be at its highest level.
