### ISSUE TITLE
[Enhancement] Base snow/rain off of temperature, not season

### ISSUE THREAD

**Issue by grundyboy34** [Glitchfiend/ToughAsNails#365]
Currently, snow only occurs either in biomes which are set to have snow, or when one has a low enough temperature during winter. I'd propose changing this, since other mods can change biome temperatures, such that snow depends on temperature only. Seasons would then play the role of causing temperature and precipitation fluctuations.

[Here's a case that made me think of this, as realistically, this should be snowing.](https://i.imgur.com/U7pPLaS.jpg)

**Comment by Forstride** [comment]
Closing this since we're moving seasons to a separate mod (https://github.com/Glitchfiend/SereneSeasons).

Also, this really isn't an issue.  Snow *is* based on the temperature of the biome.  The winter season just shifted the biome temperature, and if it was low enough, it'd snow.
