### ISSUE TITLE
Using campfires to cook your food.

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/ToughAsNails#37]
The title already mentioned it. Give campfires an extra purpose besides keeping you warm.

**Comment by Forstride** [comment]
I'm not a fan of this idea as it would likely be very, very unbalanced.  Campfires do not require any kind of fuel, and I don't want to implement some kind of fuel system for them, as they're just meant to be early-game heat sources.

**Comment by Quizer9O8** [comment]
Oh thats a shame. I really hoped that Campfires had another feature instead of only keeping you warm. Furnaces are also early game so why can't a Campfire be that too?
Im not a professional coder or something but is it really hard to code a fuel system?
In Terrafirmacraft you can use Campfires to cook some food too.
I'm sure you'll find a solution.

**Comment by Forstride** [comment]
Ok, so if furnaces are early game, why do you need both?  It just seems kind of redundant.  Also, I'm kind of tired of hearing the comparisons to Terrafirmacraft.  TFC is a complete overhaul mod.  TAN is meant to fit into vanilla properly.  Certain features and ideas will not work properly in TAN, nor do I want some of them regardless.

**Comment by Quizer9O8** [comment]
It doesn't matter what you make, there will always be people that like, dislike or want other things in it too. in my opinion i would rather use the campfire to cook my food instead of using a furnace. I suppose you know it isnt bad to take feedback from other people, even if they are comparing other mods with this mod. It's a learning curve. We want this mod to succeed dont we? so no hard feelings man.
