### ISSUE TITLE
Thirst compatibility "Rustic & Binnies" 

### ISSUE THREAD

**Issue by Krhymez** [Glitchfiend/ToughAsNails#378]
Is there any way to make liquids from these mods work with thirst?

Currently they do not effect thirst.

**Comment by katubug** [comment]
Same thing with Pam's Harvestcraft. The answer I got on reddit is that the other mod authors need to use the TaN API. They DID mention making a config option, but that was a year ago. I'd really appreciate this feature, as I think many others would as well.

**Comment by Adubbz** [comment]
Configurable drinks have been added to https://github.com/Glitchfiend/ToughAsNails/tree/TAN-1.12.x-3.x.x-WIP which will be released soon.

**Comment by katubug** [comment]
Hooray! Thank you!
