### ISSUE TITLE
[Question] Compat with 1.12.2?

### ISSUE THREAD

**Issue by InjuredWolf** [Glitchfiend/ToughAsNails#380]
Just wondering if the mod is currently compatible with MC 1.12.2 - the Twitch Client doesn't list it, so was just making sure

**Comment by Adubbz** [comment]
Yes, it is. All 1.12 mods should work fine on 1.12.1 and 1.12.2.

**Comment by InjuredWolf** [comment]
may want to update it on the curseforge page then. Twitch Client doesn't recognise it
