### ISSUE TITLE
Hypothermia activating while "warm"

### ISSUE THREAD

**Issue by Kraahkan** [Glitchfiend/ToughAsNails#382]
Hey, what information do you need to troubleshoot this?  I get hypo and take damage when my body temp reads as warm (the fire icon). Seems to go away if I'm at "full hunger" but as soon as I fall a couple points under I start taking damage ):

**Comment by Kraahkan** [comment]
Whoops, I guess this was hyperthermia, I didn't even know that was in here. Is there a way to disable this feature? 

Thanks

**Comment by Forstride** [comment]
No, there's no way to specifically disable hypo/hyperthermia, because it would make body temperature pointless otherwise, but you can disable the temperature feature altogether.
