### ISSUE TITLE
[1.12.2]Missing Savegame registries after mod uninstall

### ISSUE THREAD

**Issue by BibleBeliever** [Glitchfiend/ToughAsNails#385]
After trying this mod in my 1.12 savegame (running other 34 mods) with Tough as Nails, I realised that there's no way I'll enjoy this mod with the current mod compatibility, so - I uninstalled it. After uninstalling and trying to play again, Forge said that 52 registries are missing, listing all the elements (such as thirst and what not). The big issue is that im stuck with 3 hearts since I'm in hardcore mode. What am I supposed to do? What kind of mod is this really? I mean, I even uninstalled Minecraft entirely. Please assist me!

**Comment by BibleBeliever** [comment]
P. S.: By the way, I also have multiple savegame folder backups, dating 4 days back. None of them are working even after the Mc reinstall. You guys did something too deep and you should help me fix it.

**Comment by Adubbz** [comment]
Please see https://github.com/Glitchfiend/ToughAsNails/issues/35 which explains this issue and some options you have to fix it.
