### ISSUE TITLE
Clean water bypass with some fluid blocks.

### ISSUE THREAD

**Issue by Krhymez** [Glitchfiend/ToughAsNails#386]
There seems to be an issues with a few blocks. If i put a bucket of water in, i can take out clean water. This bypasses the need to filter water or set up a rain collector.

Animania- Cheese mold
Rustic- fluid barrel

Not sure if there are others yet, but it seems most fluid containers can do this. Is there any way to make "Any" water picked up with a bottle to be dirty?

**Comment by majijn** [comment]
tinkers construct tanks also does this
