### ISSUE TITLE
[Request] Campfire recipe compat with Survivalist mod

### ISSUE THREAD

**Issue by omega025** [Glitchfiend/ToughAsNails#387]
The Survivalist mod and Tough As Nails are fun to play together as they both add interesting challenges to early game survival.  However, playing both together makes it much more difficult to regulate the player's temperature at nights.

The reason is because the Survivalist mod adds some changes the process of obtaining cobblestone - breaking stone blocks drops rocks, which then must be crafted together with clay to produce cobble.  If players are playing in areas where clay is not readily available, then campfires (which require cobblestone blocks) aren't really an option, even if the player has an abundance of rocks.

I request additional options for the campfire crafting recipe, so that Survivalist mod rocks (including rocks dropped by breaking diorite, granite, andesite) can be used in place of cobblestone blocks to produce campfires.

**Comment by Forstride** [comment]
CraftTweaker and a variety of other mods can accomplish this.  Unless they have a simple ore dictionary name, it'd be more effort than it's worth to add it natively.

**Comment by omega025** [comment]
Thank you for the referral to CraftTweaker!
