### ISSUE TITLE
incompatibility with LiteLoader

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#39]
I create an issue here about this bug. For people who still doesn't what is this problem, ToughAsNails isn't loaded by Forge when LiteLoader is installed. It's pretty annoying since it prevents to play with both ToughAsNails and Matmos. Here is the log with only Forge, LiteLoader and ToughAsNails. http://pastebin.com/n1BSQfqR

**Comment by Drehverschluss** [comment]
Oh yea i really like to play with Matmos too

**Comment by Adubbz** [comment]
Have you tested with the standard Vanilla launcher out of curiosity? Or does Liteloader not provide any support for it?

**Comment by 0Navis0** [comment]
I should try, but I don't know if it will change something.

**Comment by Drehverschluss** [comment]
Well you know....its not just Matmos i want to use ;) LiteLoader is just a small part of my List.

**Comment by 0Navis0** [comment]
I confirm it doesn't work with the Vanilla launcher.
And sadly LiteLoader is required for Matmos.

**Comment by Adubbz** [comment]
Could I have the Vanilla launcher log as well? Perhaps it will be more helpful than MultiMC's

**Comment by 0Navis0** [comment]
Ah damn I didn't keep it.

**Comment by 0Navis0** [comment]
I doesn't seem to change anything http://pastebin.com/hJiEb6WR

**Comment by Adubbz** [comment]
Fixed with https://github.com/Glitchfiend/ToughAsNails/commit/e3ea9a3977cc331f1c041206129662e4db257076
