### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Preminenc3** [Glitchfiend/ToughAsNails#391]
Compatibility with the mod RPG_Hud would be great, and also an option to move the thirst meter around the screen thanks.

**Comment by Forstride** [comment]
We've fixed HUD issues with the Thirst meter overlapping other HUD elements from other mods (Assuming they also position it using Forge's GUI functions).

As for compatibility with RPG HUD, that's really not something that should be on our end.  There's probably a way for them to cancel our HUD rendering and add their own if they want to support it.
