### ISSUE TITLE
LiteLoader incompatibility [client-side]

### ISSUE THREAD

**Issue by Foxgreat** [Glitchfiend/ToughAsNails#393]
Hello! I have an issue for you, same as #299 

I have MC 1.12.2 with optifine HDUC6, forge 2529 and liteloader (on mods folder) TAN 70

In my modpack it loads with liteloader but i cant join single or multi player maps. By experimental drag and drop files i configured that LiteLoader and TAN wont launch game in one modpack.

It launches without optifine without liteloader
It launches with Optifine without liteloader
It wont launch without optifine with liteloader
It wont launch with optifine with liteloader

In console log i see how i triyng to join but Mumfey wont get me in with error:
local:E:5dfa68a5 lost connection: Internal Exception: java.lang.NoClassDefFoundError: com/mumfrey/liteloader/core/event/EventProxy$2

My FML and client logs.
[fml-junk-earlystartup.log](https://github.com/Glitchfiend/ToughAsNails/files/1495062/fml-junk-earlystartup.log)
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/1495063/latest.log)
[fml-client-latest.log](https://github.com/Glitchfiend/ToughAsNails/files/1495064/fml-client-latest.log)

I send this problem to Mumfey too so i hope you both can fix that conflict between your mods.

**Comment by danloona** [comment]
Soo, same here. 👍
