### ISSUE TITLE
Missing ingame body temperature config options

### ISSUE THREAD

**Issue by GreyWolf90** [Glitchfiend/ToughAsNails#394]
When I press the "config" button in the mod options menu, I can only set the max hearts range, disable or enable the thirst system  and enable/disable the starting health malus. 
How can I tweak the body temperature system or all the other stuff?

**Comment by Adubbz** [comment]
Please title your issues accurately. There's a significant difference between there being some certain config options not being present in game and there being "no configuration options whatsoever". 

The body temperature system can be tweaked from the standard text configuration files just as everything else can.

**Comment by GreyWolf90** [comment]
My bad, sorry. Thanks for your answer anyway.
So you mean the ".class" files in the config folder?

Edit: No ok just kidding, found them
