### ISSUE TITLE
Charcoal filter

### ISSUE THREAD

**Issue by sk1llzf0rg0d** [Glitchfiend/ToughAsNails#397]
![wqw](https://user-images.githubusercontent.com/34129169/33430764-b7ed1c44-d59f-11e7-92a5-134237402cbd.JPG)
Hi ! i've tried different way to craft it , but it doesnt seem to work , i tried every possible way and it doesnt work , minecraft : 1.11.2 , send help D:

**Comment by Forstride** [comment]
The recipe was changed.  Check the wiki to see the updated recipe: https://github.com/Glitchfiend/ToughAsNails/wiki
