### ISSUE TITLE
Water bottle mod interactions

### ISSUE THREAD

**Issue by BDweller** [Glitchfiend/ToughAsNails#40]
If vanilla water bottles are the end result of filtering/boiling mods that include tanks/bottlers bypass the cleaning by assuming a vanilla water+bottle = water bottle

I tested this with Ender IO for 1.9.4 3.0.0.alpha_43 and TaN 1.0.2 but I suppose any tank with right click functionality or bucket filling UI would do the same.

Both the UI and right clicking with an empty bottle return a regular water bottle.

EDIT: 
Personally I'm happy with thirst as an attribute alone.

**Comment by skruis** [comment]
Just wanted to comment - I would prefer that that mechanic be left in until a more automatable way of obtaining clean water is available...at least crafting an EnderIO tank is something of a minor accomplishment early game especially if it's sole purpose is to provide clean drinking water versus storing lava or other more critical liquids. Creating the filters and then processing individual bottles is fine for early game and yes, there are ways to automate that specific process but there should also be ways to create large amounts of drinkable water via some technological mechanic (machines) that makes more sense for mid to late game as well ... a filtering machine/block and a boiler/block. Maybe have a large carbon filter that has durability so it has to be replaced after so many mb's of water processing.

**Comment by pastellexists** [comment]
I've actually prototyped auto tree farms and cane farms, which the canes are turned into paper, and the wood turned into charcoal, the output charcoal is divided, half goes back into furnaces and half to crafting, and the crafter makes filters which then will cleanse my water if i put it into the system, but this thing takes up 6 chunk, so a high temperature boiling system was added it would be amazing.
