### ISSUE TITLE
Snow during the winter

### ISSUE THREAD

**Issue by ejektaflex** [Glitchfiend/ToughAsNails#401]
With temperature and thirst turned off (leaving on only crop death and seasons), it seems to rain in the winter. Minecraft 1.12.2, Forge 14.23.1.2560, TAN 3.0.0.72.

Could it be that you are still doing temperature checks with temperature disabled? I'd like it to snow in the plains and our server lives in the plains, but we have temperature turned off.

**Comment by Forstride** [comment]
The temperature shift that seasons use to determine which biomes can have snow in the winter is completely separate from body temperature.  I can't replicate this issue, so I'm just gonna close it.
