### ISSUE TITLE
Some strange behavior with charcoal filters and canteens

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/ToughAsNails#402]
I've noted that adding a charcoal filter to an empty canteen effectively acts as though you filled it with filtered water, without have actually put in fluid. Furthermore, I cannot add filters to a dirty water canteen at all.

I do have the addon slurp installed.

**Comment by Morbidcactus** [comment]
I'm experiencing the same behaviour, Tough Expansion and TAN Campfire Spit installed

1.12.2 with Forge 14.23.1.2560

**Comment by Nosrick** [comment]
Getting this same behaviour, however I have no addons installed.
1.12.2 with Forge 14.23.1.2583.

**Comment by Kendallfish** [comment]
I have this problem too

**Comment by Hitel98** [comment]
I have this too

**Comment by Forstride** [comment]
You can't filter canteens unless they're full.  I can't replicate the empty canteen filtering issue though.
