### ISSUE TITLE
New version prevents client logon, states NBT tag error

### ISSUE THREAD

**Issue by katubug** [Glitchfiend/ToughAsNails#405]
After trial and error, I found this error only goes away after reverting to the previous version of TaN. Please let me know what other information I should provide!

![ohdear](https://user-images.githubusercontent.com/20935286/34366892-fb1a110c-ea67-11e7-92e2-ff2792e93c4e.jpg)

**Comment by katubug** [comment]
Here's the server-side console log of the attempt: https://hastebin.com/xiqucugese.vbs

**Comment by Adubbz** [comment]
~~Could you please try uploading your log somewhere else (pastebin, github gist etc.). Hastebin just seems to show nothing when I click that link.~~ Nevermind - Seems to have worked on the fourth try. No idea what happened there.

Do you have a lot of temperature coils placed? Also are they covering a large area? I'm guessing this is probably to do with syncing the positions they regulate for particles, although I may be wrong

**Comment by Adubbz** [comment]
Also a copy of the world would be great too

**Comment by katubug** [comment]
Sorry for the delay, I was snowed in away from my PC.

We do have a lot of heating/cooling coils placed in our main base. It's probably a like... 30x15 area? So biggish but not huge. We probably have about ~18 total coils in the area (we live in a Highland Biome, rather high up, but are constantly overheating, haha).

Here is our world folder. I don't recall whether you need the whole thing or just the level.dat, but I thought I'd be thorough and I didn't want to accidentally exclude something you needed: 

https://www.dropbox.com/s/o322p71ox6vhq2p/world.zip?dl=0

**Comment by SSyl** [comment]
I had the same issue. I only had a single heating coil and as soon as I put a redstone torch down next to it I got the error. I had to MCEdit to remove the heating coil in order to log back into the world.

The heating coil was outside (I was just testing it out - I know it's not supposed to work outside), so is it possible that it was trying to select the entire outside world when calculating what to heat?

**Comment by BillyGalbreath** [comment]
I can confirm. Placed a cooling coil in a default villager house and was kicked as soon as I turned it on with a redstone torch. Was unable to log back in. Downgraded the mod and all is fine.

Broken version: ToughAsNails-1.12.2-3.1.0.73-universal.jar
Working version: ToughAsNails-1.12-3.0.0.68-universal.jar

Using Forge 1.12.2-14.23.2.2613 and SpongeForge 1.12.2-2586-7.1.0-BETA-2897
