### ISSUE TITLE
[1.12.2] Immersive Engineering hemp not dying in winter

### ISSUE THREAD

**Issue by SeriousCreeper** [Glitchfiend/ToughAsNails#409]
Heya,

i was just testing some crops in winter and noticed the IE hemp plants don't die in winter. Now i'm not sure if this is something TAN has to do or if IE needs to implement something for it (@BluSunrize). 
The Better With Mods hemp seems fine (also a 2 block tall flower). 

Cheers,
SC

**Comment by Forstride** [comment]
They'll need to add support using our API, namely implementing IDecayableCrop (https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/api/season/IDecayableCrop.java)
