### ISSUE TITLE
Breath Bubbles(in water) on Thirst Drops

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#410]
forge 2585, mc 1.12.2, ToughAsNails-1.12.2-3.1.0.73
![123](https://user-images.githubusercontent.com/24831406/34649528-1e9388f8-f3c2-11e7-8e7c-0e5fa2275a9d.PNG)

**Comment by Forstride** [comment]
HUD issues should be fixed now.
