### ISSUE TITLE
[FEATURE REQUEST] Campfires, when broken/burned out, create empty firepit ready to be fueled

### ISSUE THREAD

**Issue by GreyMario** [Glitchfiend/ToughAsNails#411]
I've been playing the ATLauncher Homestead (1.10.2) pack for a little while now and it bothers me that the pack creator made the decision to change the Campfire recipe to require an item (Immersive Craft Stones found scattered on the surface) that is itself made non-renewable.

[E: Don't chew on me for playing an old TAN version and making requests; I checked the latest code here and it's still not a thing that happens.]

This is a problem, because Homestead provides for Realistic Torches as well (which burn out over time), which in turn are only creatable at a Campfire... which, you guessed it, is a nonrenewable resource. I'm sorry, what? Torches are nonrenewable, despite basically being _burning wood?_

Of course, that's easy enough to fix on my end, I can re-add the old recipe. But it got me thinking.

### **Why is it we can't reuse our campfires?**
Rocks don't generally burn away, and ashes and wood debris can be cleared away in real life to support adding new, fresh, dry fuel to begin the fire anew. No need to create an "empty firepit" recipe unless you desperately want to decorate with them. Just let us reuse our firepit! Fuel, of course, would just be another four logs...

**Comment by ilvrak** [comment]
fully support previous speaker!
rocks dont burn. burned out firepit must be rendered without logs in it, but rightclicking with logs - adds logs to it, one by one, to four. and it ready to fire up with sticks again!
i very much ask to implement this.

**Comment by GreyMario** [comment]
Closing all existing issues doesn't make them go away. Resolve the issue or say "no".

**Comment by Forstride** [comment]
I mass closed them as we had the issues page disabled for over a year when the mod was in a state of being discontinued, and 99% of them are not relevant anymore with our rewrite of the mod for 1.16.4.  The campfire for example isn't even in the mod and won't be seeing as vanilla has its own now.  I'm pretty sure you can use context clues to figure out why it was closed, and if something ends up still being an issue in future versions, a new issue can be opened.
