### ISSUE TITLE
Manual season change

### ISSUE THREAD

**Issue by xhatz** [Glitchfiend/ToughAsNails#414]
Hello! This would be more of a suggestion rather than a bugfix... but I didn't know where to post, sorry!

On my public server, I would really like to make the seasons set manually so that they correspond to the real life current season, but that is not yet possible...
I've tried setting the duration of a season to the maximum, but it makes the game bug a lot, like if I was setting it to a low value or something.

My idea would be to just, for example, add a gamerule that allows the season to progress as the minecraft days go, so I could turn it off on my server, for example.

I am sorry if my message is not super well written, I am not native english, so I hope it is understandable at least well haha. Otherwise, thank you for your work, the mod itself is already once of my favorite mods so far!

**Comment by RiverC** [comment]
Question: if you set the minecraft day setting to a single day (68400 x 20 = 1368000 ticks) and the month (sub season) length to 30 does that work? You could just set the season to mid-winter every Jan 1 as it would be about 5 days off (360 days vs. 365)

**Comment by xhatz** [comment]
I'm scared that this solution would cause desynchronizations when the server stops and starts again because it wouldn't be set on the local time directly :/ but yeah that could possibly be a working solution, thanks =p!

**Comment by Forstride** [comment]
Closing this since we're moving seasons to a separate mod (https://github.com/Glitchfiend/SereneSeasons).
