### ISSUE TITLE
Heating coils don't work

### ISSUE THREAD

**Issue by Kendallfish** [Glitchfiend/ToughAsNails#415]
I can't say that I ever noticed my heating coils working in 1.12.2, but they definitely aren't now. My temperature drops to hypothermic levels while wearing all wool armor and with the heat coils on in my house.

**Comment by Adubbz** [comment]
Heating coils don't guarantee you won't get hypothermia. Also, we need much more information. We need the version of the mod (and you need to make sure it's up to date), and a screenshot of the output of /tan tempinfo. If you're using the latest version there should be particles in areas that are heated.

**Comment by Kendallfish** [comment]
I'm using 1.12.2-3.1.0.73 and there are particles in the house. This is the tan/tempinfo when it's off >
![2018-01-12_20 49 03](https://user-images.githubusercontent.com/35358021/34901677-72061754-f7db-11e7-9e6c-6c05b0adea0d.png) 
this is when the coils are on 
![2018-01-12_21 02 23](https://user-images.githubusercontent.com/35358021/34901713-036c6248-f7dc-11e7-9071-f8ef4b64b3d5.png)

**Comment by Adubbz** [comment]
It seems there's a cooling coil currently active, even when both of the ones you've shown are off. Are those two the only ones in your house? And if they are, try destroying them both and placing them down again, and take another screenshot.

**Comment by Kendallfish** [comment]
Okay i just switched their places and now the heating one works. however the temp info keeps rapidly jumping between this and this
![2018-01-12_21 32 02](https://user-images.githubusercontent.com/35358021/34901967-2a592ef0-f7e0-11e7-96f6-f4046513b17a.png)
![2018-01-12_21 32 04](https://user-images.githubusercontent.com/35358021/34901969-38b860e2-f7e0-11e7-8ac6-eed66f8b01e3.png)

Any idea why it didn't work before?

**Comment by Kendallfish** [comment]
okay I've figured out that if i destroy and replace them both, the one i use first is what they both do. if i turn on the cold and then the heat the heat coils will cool the space when the cold one is off.
