### ISSUE TITLE
Charcoal filters and boiling dirty water bottle not working

### ISSUE THREAD

**Issue by Zifiv** [Glitchfiend/ToughAsNails#416]
Hello,

The charcoal filter recipe is not working and the ability to boil dirty water bottle in furnace is not working.

I'm using :
- Minecraft V1.12.2
- Forge V14.23.1.2555
- Dynamic Surroundings V3.4.7.2
- Tough as Nails V3.1.0.73

**Comment by Kendallfish** [comment]
the filter recipe changed to 1 charcoal between two vertical papers, and you can only boil filtered water

**Comment by Zifiv** [comment]
OK thanks you. The wiki is not up to date it will be cool to update the wiki when there are modifications. I close the issue.
