### ISSUE TITLE
status icons still not fixed 

### ISSUE THREAD

**Issue by hologer** [Glitchfiend/ToughAsNails#417]
All the status icons are missing

**Comment by Adubbz** [comment]
What version of the mod are you using? They were fixed in 3.1.0

**Comment by hologer** [comment]
yes, i downloaded the latest one - ToughAsNails-1.12.2-3.1.0.73-universal.jar
still no icons
![default](https://user-images.githubusercontent.com/16763467/34946574-3cc1de34-fa29-11e7-9a56-2c7da0d47e68.png)

**Comment by Adubbz** [comment]
Could you please link your log file

**Comment by hologer** [comment]
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/1631938/latest.log)

**Comment by hologer** [comment]
it's working now, thanks!
