### ISSUE TITLE
[Important Issue-1.12.2] I can't filter Dirty Water Canteen.

### ISSUE THREAD

**Issue by AxolotlAccount** [Glitchfiend/ToughAsNails#419]
Instead of it, you can put a empty canteen and a charcoal filter together to make a Filtered Water Canteen with a water came out of nowhere!

My Configuration: I disabled low heart, seasons and body temperature. Only Thirst is enabled.

Tough As Nails Version: 1.12.2 - 3.1.0.73

**Comment by TheCodingGorilla** [comment]
I'm having the same issue on the same version

**Comment by GotoFinal** [comment]
Same issue ;/ but normal configuration with everything enabled.

**Comment by Forstride** [comment]
You can't filter it if it's not full.  I can't replicate the empty canteen filtering issue though.
