### ISSUE TITLE
Fix health bar rendering after entering a different dimension

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#42]
Health bar rendering gets messed up upon entering a different dimension.  May or may not be caused by vanilla

**Comment by erindal** [comment]
I can confirm this. The bug is visual only, relogging fixes the issue.

**Comment by Adubbz** [comment]
I think this likely is a Vanilla issue. I suspect our heart outline is still rendering, however it's not visible because it blends in with the Vanilla hearts. It may be possible to add some kind of workaround on our end, but I haven't looked into that yet.

**Comment by erindal** [comment]
Could you maybe force some sort of reload of the hud rendering when someone changes dimensions? It's a bit of a round about way of doing it though.

**Comment by ghost** [comment]
Except it's not visual, did some tests and it's not

**Comment by Forstride** [comment]
I've removed the Lowered Starting Health feature, so this issue can be closed.
