### ISSUE TITLE
[1.12.2 Bug]: ToughAsNails items are in every creative tabs

### ISSUE THREAD

**Issue by MilchLos** [Glitchfiend/ToughAsNails#420]
Some items of your mod are shown in almost every creative tab. I used your latest TAN version + latest Glitchcore version with Forge 14.23.1.2590. No other mods.

![2018-01-17_15 48 34](https://user-images.githubusercontent.com/18751835/35049156-614ac12c-fb9f-11e7-9400-78a9149590e6.png)
![2018-01-17_15 48 37](https://user-images.githubusercontent.com/18751835/35049163-6640915c-fb9f-11e7-88e1-22d4ca1e74c8.png)
![2018-01-17_15 48 39](https://user-images.githubusercontent.com/18751835/35049169-6a181660-fb9f-11e7-9a97-bc72a5cbb1ea.png)
![2018-01-17_15 57 29](https://user-images.githubusercontent.com/18751835/35049173-6c9c0c48-fb9f-11e7-88e8-fea105e0516d.png)

**Comment by KnightMiner** [comment]
This is probably caused by getSubItems now being called by all tabs. Vanilla calls a function in their methods to check the tab.

**Comment by ghost** [comment]
I have the same problem
