### ISSUE TITLE
[FEATURE REQUEST] Restore by eating apples or watermelons directly.

### ISSUE THREAD

**Issue by NoRealityAdult** [Glitchfiend/ToughAsNails#421]
Please add features. Restore by eating apples or watermelons directly.

Make the game easier at the beginning.

Thank you.

**Comment by Lordician** [comment]
With the new drinks configuration options you can do this yourself as well:
`
  {
    "item": {
      "name": "minecraft:mushroom_stew",
      "metadata": 0
    },
    "thirst": 4,
    "hydration": 0.5,
    "poisonChance": 0.1
  },
  {
    "item": {
      "name": "minecraft:rabbit_stew",
      "metadata": 0
    },
    "thirst": 4,
    "hydration": 0.5,
    "poisonChance": 0.0
  },
  {
    "item": {
      "name": "minecraft:beetroot_soup",
      "metadata": 0
    },
    "thirst": 4,
    "hydration": 0.5,
    "poisonChance": 0.0
  },
{
    "item": {
      "name": "minecraft:melon",
      "metadata": 0
    },
    "thirst": 2,
    "hydration": 0.2,
    "poisonChance": 0.0
  },
  {
    "item": {
      "name": "minecraft:apple",
      "metadata": 0
    },
    "thirst": 1,
    "hydration": 0.1,
    "poisonChance": 0.0
  }
`
Be sure to put a , after the last entry in drink_stats.json currently and then paste this.
And/or check the final result in a JSON checker.

**Comment by NoRealityAdult** [comment]
Thank you!
