### ISSUE TITLE
Missing class crash in 4.0.0

### ISSUE THREAD

**Issue by Gabrielcmf** [Glitchfiend/ToughAsNails#422]
The game crashes on startup with TAN-1.x.x-4.0.0

https://pastebin.com/eKeuUvDp

Strangely, the class can be found inside the mods files, however the game doesn't seem to recognize it.

**Comment by Adubbz** [comment]
See https://github.com/Glitchfiend/ToughAsNails/issues/418, you're missing GlitchCore.

**Comment by Gabrielcmf** [comment]
I have glichtcore installed, as you can see in line 179 of the crash log I posted.
I'm using the 1.12.2-1.0.0 version.

**Comment by Adubbz** [comment]
Huh, it seems you're right, my apologies. It looks like the exact same crash as someone who didn't have it installed oddly enough. I'll have a look at it

**Comment by AxolotlAccount** [comment]
The same crash happens to me too. Using 1.12.2-1.0.0 GlitchCore

**Comment by katubug** [comment]
I'm also having the same crash, and I also have GlitchCore 1.0.0 installed.

[crash-2018-01-20_12.06.17-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1649109/crash-2018-01-20_12.06.17-client.txt)

**Comment by QAngelusQ** [comment]
The issue seems to be with Forestry (im using - "forestry_1.12.2-5.7.0.236") 

After comparing my recent additions of mods with Gabrielcmf's list,
Removing Forestry seems to get me to the main menu instead of crashing, hope this helps.

**Comment by Morpheus1101** [comment]
Im also getting the exact same crash, however forestry is an integral part of my pack, so unf removing it is not an option.  However downgrading TAN did solve the issue for now

Forge *.601
TAN v4.0.0
Forestry v5.7.0.236

**Comment by Sang-bin** [comment]
Me too, set up forestry and have the same log.

**Comment by benjaminkimball** [comment]
[Comforts v1.1.0.1](https://minecraft.curseforge.com/projects/comforts/files/2523141) seems to cause the crash similar to Forestry.  I can get to the menu once  I remove it from the `mods` folder

[crash-2018-01-28_10.12.09-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1671328/crash-2018-01-28_10.12.09-client.txt)

**Comment by alexgurrola** [comment]
I'm having the same issue, and downgrading does solve the issue, but the particle effect of the SnowFlake on the Cooling Coil causes my server to build packets that are too large and my client dies, claiming there's an overflow for that variable's byte allocation.  I don't have a crash log, since it's a locked disconnect on that block, so after I remove the lever providing redstone to the coil in MCEdit, I should be able to give you more information.
