### ISSUE TITLE
[ENHANCEMENT] Warmer/cooler armor items depending on the body surface being covered

### ISSUE THREAD

**Issue by Tumlinh** [Glitchfiend/ToughAsNails#429]
Chestplates and legs would provide a biggest temperature bonus (e.g. +/- 2) than helmets and boots (+/- 1).

**Comment by Forstride** [comment]
Not really a fan of this idea.  The current way is much more simplistic.  Also, I'd argue that keeping your head and feet warm is much more important IRL, but this is a game, so ¯\_(ツ)_/¯
