### ISSUE TITLE
[FEATURE REQUEST] Jumping warms up

### ISSUE THREAD

**Issue by Tumlinh** [Glitchfiend/ToughAsNails#432]
Sprinting increases the body temperature, why not jumping?
Each jump could increase temperature by 0.1° for example.

**Comment by Forstride** [comment]
Kind of pointless, as it really wouldn't have much of an effect, and jumping literally lasts a single second

**Comment by Tumlinh** [comment]
It would have a significant effect if you're climbing a mountain.
