### ISSUE TITLE
Suggestion: Config option to retrieve vanilla water bottles from source blocks

### ISSUE THREAD

**Issue by WrongWeekend** [Glitchfiend/ToughAsNails#433]
Players should be able to have to deal with thirst without the need to purify the water, as many mods aren't balanced properly with this gameplay mechanic (such as objects that provide clean water when they logically shouldn't, or a very large number of recipes that require "clean" water when dirty water should work fine) and others make sugarcane a resource limited to certain climates. For the canteen it's not as important, but for the sake of consistency it could apply to that too. I think this is a much simpler solution than trying to create compatibility with every mod that uses water bottles in machines and recipes.

Alternatively, make the vanilla water bottle the lowest quality water bottle, with filtered and purified water quenching more thirst and eliminating the risk of the thirst modifier.

**Comment by WolfieWaffle** [comment]
I like the idea of making regular water the lowest level. I think things should be designed to kind of "branch off" vanilla rather than overruling it if possible, making the default water that all mods use the lowest tier ensures compatibility with any other mod that doesn't also provide its own special water. 

Another example is the stumps in Better With Mods, they longer have a stump specific block and just test for upwards facing wood above dirt, meaning it now works automatically with all logs.

**Comment by KnightMiner** [comment]
I think the issue with just replacing the vanilla bottles is potions no longer require filtering the water. Potions can easily be cheaper than the filtering ingredients by brewing recipes with no effect.

**Comment by Shivaxi** [comment]
This might also fix the bug where you try to scoop a potion out of a cauldron with an empty bottle and end up getting dirty water instead of the potion back.  breaks an entire mechanic of minecraft right there, along with any mods that have you mixing potions to create new potions in a cauldron

**Comment by KnightMiner** [comment]
You know potions in cauldrons is not a vanilla mechanic? I add it in Inspirations, but I specifically coded it there to work with TAN's water bottles.

**Comment by Shivaxi** [comment]
uh, it is a vanila mechanic?  It has been since 1.9.  It's how you maked tipped arrows:

https://minecraft.gamepedia.com/Arrow#Tipped_arrows

"Added tipped arrows, which are made by using cauldrons filled with potions."

**Comment by KnightMiner** [comment]
Read the header in the history, pocket edition

**Comment by WrongWeekend** [comment]
>I think the issue with just replacing the vanilla bottles is potions no longer require filtering the water. Potions can easily be cheaper than the filtering ingredients by brewing recipes with no effect.

Blaze rods and blaze powder are much more difficult to obtain than charcoal and paper. Other mods may make it easier but they are almost universally rarer and more valuable. 

The potion brewing process could also be an alternative purification method in its own right, at least from regular to purified water.

>"Added tipped arrows, which are made by using cauldrons filled with potions."

This only applies to the Bedrock/Pocket editions, not the Java version.

>Tipped arrows can be obtained by using arrows on cauldrons that have potions.[Bedrock and Legacy >Console editions only]

https://minecraft.gamepedia.com/Arrow#Cauldrons

**Comment by Shivaxi** [comment]
The potion extension mod I have must add that mechanic back then.  But yeah either way, it breaks this potion mod and probably other mods that allow you to put different liquids perhaps into cauldrons.  What's weird is that this potion extension mod adds a new type of cauldron called a mixing cauldron, for mixing potions and stirring...and even using an empty water bottle on that new cauldron gives a dirty water bottle...which is bizarre considering its an entirely new block?

**Comment by MLMII** [comment]
If I may make a suggestion, wouldn't it solve the issue fairly realistically to simply allow people to "boil" dirty water in the furnace?  ...  I remember that the "thrist mod" in 1.7.10 had that as an option and I was shocked when I couldn't boil water in Tough as Nails.

Just to clarify, what I'm suggesting is allow a furnace to boil  Dirty Water => Filtered Water, so to get Clean Water you'd have to boil it twice.

**Comment by piber20** [comment]
Adding this config option would be a welcome addition. It would make things more compatible and would be great for those who prefer simpler gameplay.

I came here looking for a thirst mod, and I think the mod is great at what it does, but needing to purify the water kind of throws me off a bit. I can understand why that was needed considering how easy you can get water in the game, but it just doesn't feel very "minecrafty" to me. Though the mod is still brilliantly done. I'm not trying to discredit the creator or anything.

Perhaps with this conceptual config setting active, vanilla water would quench less thirst to balance it out?

**Comment by WrongWeekend** [comment]
Yes, in that case vanilla water would be the "dirty" water, and filtered/purified water would be safer to drink.
