### ISSUE TITLE
Coils are broken and send extremely large packets that crashes map

### ISSUE THREAD

**Issue by GotoFinal** [Glitchfiend/ToughAsNails#435]
https://github.com/Glitchfiend/ToughAsNails/blob/TAN-4.x.x/src/main/java/toughasnails/tileentity/TileEntityTemperatureSpread.java#L44-L47

All this data for some reason is also send to all clients, for large rooms it is just huge amount of data - often larger than packet limit size so it just crashes and then you need to remove the coil using mcedit or other external software.

**Comment by kreezxil** [comment]
I got this too! :(

maybe there could a be a config to turn off the coils.
