### ISSUE TITLE
Crash when using "Robotic Parts" cyberware to regulate body temp.

### ISSUE THREAD

**Issue by MLMII** [Glitchfiend/ToughAsNails#436]
CORRECTION ...  the mod in question is   "Robotic Parts"  ( https://minecraft.curseforge.com/projects/roboticparts?gameCategorySlug=mc-mods&projectID=283377 )  NOT "Rewired".   Sorry for any confusion. 

.......
.......
.......

I posted the crash report on the "Rewired" (  https://minecraft.curseforge.com/projects/rewired  ) page as well but figured that you might want to know about it as well.

*Original Post*

I ran into a crash that I believe was caused by installing the two temperature regulators  (to regulat body temp from Tough as Nails) as my game crashed within seconds of stepping outside on a spring night with the above report.
 
If it matters, my cyberbatts were fairly low.

*/Original Post*

Here is the crash report in question.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.12.2-3.1.0.73-universal.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  offlineskins (OfflineSkins-1.12.2-v3a-core.jar)
  ISCore (ImprovableSkills_1.12.2-3.1.5r.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/13/18 1:16 AM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at toughasnails.temperature.TemperatureHandler.update(TemperatureHandler.java:79)
	at toughasnails.handler.ExtendedStatHandler.onPlayerTick(ExtendedStatHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_674_ExtendedStatHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at toughasnails.temperature.TemperatureHandler.update(TemperatureHandler.java:79)
	at toughasnails.handler.ExtendedStatHandler.onPlayerTick(ExtendedStatHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_674_ExtendedStatHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1371
	Entity Name: MLMII
	Entity's Exact location: -168.96, 69.00, -13.58
	Entity's Block location: World: (-169,69,-14), Chunk: (at 7,4,2 in -11,-1; contains blocks -176,0,-16 to -161,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@57f0fcca
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3589568480 bytes (3423 MB) / 6174015488 bytes (5888 MB) up to 25769803776 bytes (24576 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2615 Optifine OptiFine_1.12.2_HD_U_C8 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version                | Source                                      | Signature                                |
	|:--------- |:--------------------- |:---------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2                 | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp                   | 9.42                   | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99              | forge-1.12.2-14.23.2.2615.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.2.2615           | forge-1.12.2-14.23.2.2615.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater     | 1.0                    | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | jei                   | 4.8.5.151              | jei_1.12.2-4.8.5.151.jar                    | None                                     |
	| UCHIJAAAA | abyssalcraft          | 1.9.4.3                | AbyssalCraft-1.12.2-1.9.4.3.jar             | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | mantle                | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                    | None                                     |
	| UCHIJAAAA | tinkersextras         | 1.12.2-1.0.2           | TinkersExtras-1.12.2-1.0.2.jar              | None                                     |
	| UCHIJAAAA | tweakersconstruct     | 1.12.2-1.2.0           | tweakersconstruct-1.12.2-1.2.0.jar          | None                                     |
	| UCHIJAAAA | tconstruct            | 1.12.2-2.9.1.65        | TConstruct-1.12.2-2.9.1.65.jar              | None                                     |
	| UCHIJAAAA | acintegration         | 1.6.2                  | AbyssalCraft+Integration-1.12.2-1.6.2.jar   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | akashictome           | 1.2-10                 | AkashicTome-1.2-10.jar                      | None                                     |
	| UCHIJAAAA | amidst-forge          | 0.1                    | amidst-forge-1.12.2-0.4.0.jar               | None                                     |
	| UCHIJAAAA | tammodized            | 0.15.3                 | TamModized-1.12.1-0.15.3.jar                | None                                     |
	| UCHIJAAAA | aov                   | 0.8.6                  | AoV-1.12-0.8.6.jar                          | None                                     |
	| UCHIJAAAA | astralsorcery         | 1.8.5                  | astralsorcery-1.12.2-1.8.5.jar              | None                                     |
	| UCHIJAAAA | psi                   | r1.1-59                | Psi-r1.1-59.jar                             | None                                     |
	| UCHIJAAAA | autoreglib            | 1.3-15                 | AutoRegLib-1.3-15.jar                       | None                                     |
	| UCHIJAAAA | autowalk              | 1.1                    | autowalk-1.12.2-1.0.jar                     | None                                     |
	| UCHIJAAAA | baubles               | 1.5.2                  | Baubles-1.12-1.5.2.jar                      | None                                     |
	| UCHIJAAAA | betteradvancements    | 0.0.5.17               | BetterAdvancements-1.12.2-0.0.5.17.jar      | None                                     |
	| UCHIJAAAA | birdsnests            | 2.1.0                  | BirdsNests1.12.2-2.1.0.jar                  | None                                     |
	| UCHIJAAAA | bloodmoon             | 1.5.2                  | Bloodmoon-MC1.12.2-1.5.2.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | botania               | r1.10-353              | Botania+r1.10-353.jar                       | None                                     |
	| UCHIJAAAA | nibbler               | 0.4.1                  | nibbler-1.12.2-0.4.1.jar                    | None                                     |
	| UCHIJAAAA | botaunomy             | 0.2.1                  | botaunomy-1.12.2-0.2.1.jar                  | None                                     |
	| UCHIJAAAA | btg                   | 1.0.1                  | By+The+Gods-1.12.2-1.0.1.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | cleanview             | 1.12.2-v1              | CleanView-1.12.2-v1.jar                     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | clienttweaks          | 3.1.2                  | ClientTweaks_1.12-3.1.2.jar                 | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked | 1.12.2-v1              | CosmeticArmorReworked-1.12.2-v1.jar         | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | craftablesaddles      | 1.3                    | Craftable+Saddles[1.12]-1.3.jar             | None                                     |
	| UCHIJAAAA | forgecreeperheal      | 1.3.0                  | creeperheal-1.12-1.3.1.jar                  | None                                     |
	| UCHIJAAAA | cyberware             | 0.2.10.8               | cyberware-1.12.2-0.2.10.8.jar               | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAA | cyclopscore           | 0.11.4                 | CyclopsCore-1.12.2-0.11.4.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | energyconverters      | 1.0.1.2                | energyconverters_1.12.1-1.0.1.2.jar         | None                                     |
	| UCHIJAAAA | everlastingabilities  | 1.3.9                  | EverlastingAbilities-1.12.2-1.3.9.jar       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | fl                    | 2.11.1                 | fl-2.11.1.jar                               | None                                     |
	| UCHIJAAAA | ic2                   | 2.8.53-ex112           | industrialcraft-2-2.8.53-ex112.jar          | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | redstoneflux          | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar     | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | sonarcore             | 5.0.5                  | sonarcore-1.12.2-5.0.5.jar                  | None                                     |
	| UCHIJAAAA | fluxnetworks          | 3.0.3                  | fluxnetworks-1.12.2-3.0.3.jar               | None                                     |
	| UCHIJAAAA | geneticsreborn        | 1.08                   | geneticsreborn-1.12-1.08.jar                | None                                     |
	| UCHIJAAAA | guideapi              | 1.12-2.1.4-57          | Guide-API-1.12-2.1.4-57.jar                 | None                                     |
	| UCHIJAAAA | hammercore            | 1.9.6.5                | HammerCore-1.12.2-1.9.6.5.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | herdcraft             | L1.0                   | herdcraft-1.12-L1.jar                       | None                                     |
	| UCHIJAAAA | hud                   | 1.3.9                  | hud-1.3.9-1.12.jar                          | None                                     |
	| UCHIJAAAA | improvableskills      | 3.1.5r                 | ImprovableSkills_1.12.2-3.1.5r.jar          | None                                     |
	| UCHIJAAAA | infinitic             | 1.12-0.1.42            | Infini-TiC-1.12-0.1.42.jar                  | None                                     |
	| UCHIJAAAA | iskalliumreactors     | 0.5.15                 | iskalliumreactors-1.12.2-0.5.15.jar         | None                                     |
	| UCHIJAAAA | levelup2              | ${version}             | Level+Up!+2-1.1.15-1.12.jar                 | None                                     |
	| UCHIJAAAA | lycanitesmobs         | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | arcticmobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | demonmobs             | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | desertmobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | elementalmobs         | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | forestmobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | freshwatermobs        | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | infernomobs           | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | junglemobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | mountainmobs          | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | plainsmobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | saltwatermobs         | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | shadowmobs            | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | swampmobs             | 1.19.0.4 - MC 1.12.2   | LycanitesMobsComplete+1.19.0.4+[1.12.2].jar | None                                     |
	| UCHIJAAAA | magipsi               | 1.3                    | MagicalPsi-1.3.jar                          | None                                     |
	| UCHIJAAAA | radixcore             | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar        | None                                     |
	| UCHIJAAAA | mca                   | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar              | None                                     |
	| UCHIJAAAA | natural_absorption    | 1.3.0                  | natural_absorption-1.12.2-1.3.0.jar         | None                                     |
	| UCHIJAAAA | torotraits            | 1.12-1                 | torotraits-1.12-1.jar                       | None                                     |
	| UCHIJAAAA | nemesissystem         | 1.12.1-2               | nemesissystem-1.12.1-2.jar                  | None                                     |
	| UCHIJAAAA | neid                  | 1.5.4.2                | NotEnoughIDs-1.5.4.2.jar                    | None                                     |
	| UCHIJAAAA | offlineskins          | 1.12.2-v3a             | OfflineSkins-1.12.2-v3a.jar                 | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | p455w0rdslib          | 2.0.28                 | p455w0rdslib-1.12-2.0.28.jar                | None                                     |
	| UCHIJAAAA | squidmilking          | 1.12.2a                | Pam's+Squid+Milking+1.12.2a.jar             | None                                     |
	| UCHIJAAAA | plustic               | 6.3.6.2                | plustic-6.3.6.2.jar                         | None                                     |
	| UCHIJAAAA | potionfingers         | r1.0-2                 | PotionFingers-r1.0-2.jar                    | None                                     |
	| UCHIJAAAA | rewired               | 1.12.2                 | ReWIRED-1.0.3.jar                           | None                                     |
	| UCHIJAAAA | sgcraft               | 1.13.2                 | SGCraft-0.3-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | toughasnails          | 3.1.0.73               | ToughAsNails-1.12.2-3.1.0.73-universal.jar  | None                                     |
	| UCHIJAAAA | tanspit               | 1.12-1.0               | tanspit-1.12.2-1.0.jar                      | None                                     |
	| UCHIJAAAA | thebetweenlands       | 3.3.0                  | TheBetweenlands-3.3.0-universal.jar         | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAA | tinkersaddons         | 1.0.7                  | Tinkers'+Addons-1.12.1-1.0.7.jar            | None                                     |
	| UCHIJAAAA | tcomplement           | ${version}             | TinkersComplement-1.12.1-0.2.2b.jar         | None                                     |
	| UCHIJAAAA | tinkertoolleveling    | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar           | None                                     |
	| UCHIJAAAA | torohealthmod         | 1.12.2-11              | torohealth-1.12.2-11.jar                    | None                                     |
	| UCHIJAAAA | toroquest             | 1.12.2-5.2             | toroquest-1.12.2-5.2.jar                    | None                                     |
	| UCHIJAAAA | totemdefender         | 1.2.8                  | TotemDefender-1.12.2-1.2.8.jar              | None                                     |
	| UCHIJAAAA | tanaddons             | 3.2.10                 | ToughExpansion-1.12-3.2.10.jar              | None                                     |
	| UCHIJAAAA | ui-tweaks             | 1.0                    | ui-tweaks-1.0.jar                           | None                                     |
	| UCHIJAAAA | waystones             | 4.0.20                 | Waystones_1.12.2-4.0.20.jar                 | None                                     |

	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.12.2-3.1.0.73-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
offlineskins (OfflineSkins-1.12.2-v3a-core.jar)
  lain.mods.skins.asm.ASMTransformer
ISCore (ImprovableSkills_1.12.2-3.1.5r.jar)
  com.endie.is.asm.ImprovableSkillsTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MLMII'/1371, l='New World', x=-168.96, y=69.00, z=-13.58]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 390.77
	OpenGlRenderer: GeForce GTX TITAN/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by MLMII** [comment]
The world is unloadable in its current state.

**Comment by mallrat208** [comment]
This issue is completely on Robotic Parts/Cyberware and will require an update to that mod, there's nothing that can be done from Tough as Nails.

**Comment by mallrat208** [comment]
On that note, the latest version of Cyberware fixes this issue.
