### ISSUE TITLE
Crash in dev environment with EntityRenderer transformer

### ISSUE THREAD

**Issue by OreCruncher** [Glitchfiend/ToughAsNails#437]
TaN: 1.12.2-3.1.0.73
Forge: 2615

Caused by: java.lang.RuntimeException: No method instruction node found matching net/minecraft/world/biome/Biome getTemperature (Lnet/minecraft/util/math/BlockPos;)F

The transformer is looking for "getTemperature" inside of addRainParticles() when it should be looking for "getFloatTemperature" (if I am understanding the intent of the transformer).

**Comment by mallrat208** [comment]
I ran into this issue as well, you need to update your MCP mappings, TaN uses snapshot_20171220

**Comment by OreCruncher** [comment]
*Cries*  I hate moving snapshots...  Thanks for the info - I will take a look.

EDIT:  I moved forward to the snapshot @mallrat208 mentioned and it is working.  Closing.
