### ISSUE TITLE
[Suggestion] Effect: Quench

### ISSUE THREAD

**Issue by QAngelusQ** [Glitchfiend/ToughAsNails#439]
Currently there is a Thirst potion effect that can be accessed with the /effect command

Would it be possible to add an opposite effect like "Quenched" ? 

Almost like Saturation with respect to Vanilla Hunger?

**Comment by Forstride** [comment]
The Saturation potion effect in vanilla isn't actually used by anything.  I guess this could be added for map makers or whatever though
