### ISSUE TITLE
Nerf beds (?)

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#44]
Add "block requirements" for sleeping, so that players can't easily make a bed on the first day and completely skip nighttime.

Maybe require the player to have bookshelves, flower pots, and other decorative items nearby before they can sleep.  Wouldn't be entirely foolproof, but it'd be better than nothing.

**Comment by Drehverschluss** [comment]
Allright i like the ideas of changing the bed mechanic.

Here are my ideas.
Recipe Change - > On my opinion i would fit better if the first and the secound woolblock would be carpets instead. Would look more like a bed than.

Another idea - Maby doing a new Item for the **pillow**. Crafting recipe could be like 
- Carpet - String - Carpet -
- Feather - Feather - Feather-
- Carpet - String - Carpet -

Just some thoughts.

**Comment by WolfieWaffle** [comment]
The hardmodetweaks mod adds an option to have a timeout for beds, by default you have to wait 3 days before a bed can be slept in (per bed, not global or player based). I would suggest that as long as having both installed would not break things.

**Comment by Forstride** [comment]
That idea doesn't really make sense.  Why do you have to wait 3 days to sleep?  In late-game, that would just be a hindrance, hence why I want to have something that makes beds unusable in early-game, but accessible mid/late-game.

We already decided that we're gonna go with the Potion of Dreaming idea anyway.  I think it's a cool idea that allows us to do what I just said above.

**Comment by WolfieWaffle** [comment]
I suppose it doesn't make much sense, but from a game balance perspective it allows you to sleep once you've been in an area for a few days. But I can see that it may be annoying if you want to move around.

If you are going to do the dream potion idea, I would request a config option to not require the potion, as I personally prefer using the other mod.

**Comment by pi4t** [comment]
Why not have two versions of the bed, to perform the two different functions? Perhaps a fairly early game bed frame, or uncomfortable bed, or something, which allows you to set your spawn? That would remove the incentive to just build your house around/near the natural spawn, limiting creativity and preventing you from using the terrain to make interesting builds. A mid/late game addition adding comfort could then allow you to skip the night.

**Comment by WolfieWaffle** [comment]
I like the idea of always being able to set your spawn, but in that case why not just have the dream potion allow you to skip the night and trying to sleep without it just sets your spawn?

**Comment by Forstride** [comment]
I guess the Potion of Dreaming could get old after a while.  Having a different type of bed would make more sense, but I'm not really sure what it would be made of.

**Comment by WolfieWaffle** [comment]
Hay Bales :P

**Comment by Forstride** [comment]
I'm pretty sure a wool bed would be a lot more comfortable than a hay bed though

**Comment by WolfieWaffle** [comment]
ah, I meant for the first bed, but wool is easier to get. Maybe some sort of mattress/pillow item that requires wool and some more expensive items?

**Comment by UndeadZeratul** [comment]
You could add an earlier, lower tier bed that doesn't let you skip the night, similar to how TFC did theirs.  They required you to place down two blocks of hay and lay on a rawhide over the top to work as a makeshift bed that only set your spawn.  The vanilla bed was still used to set the player's spawn, but it was obviously a bit harder to acquire.  TAN could implement a similar system wherein the player crafts a makeshift bed (hay bales or whatever else sounds good, really) that only sets the spawn, and possibly nerf the vanilla bed crafting recipe.

I don't like the idea of the potion, it just seems too arbitrary to me, but having a "less comfortable but workable" bed that can be used to set the player's spawn early on would be helpful, while also delaying the ability to skip the night.

**Comment by WolfieWaffle** [comment]
Or you could do both, and toggle with a config option. Kind of weird to do something like that though, I haven't really seen that in other mods.

**Comment by pastellexists** [comment]
This may be putting the bar a bit high, but I have a brilliant(probably) idea. Modular beds. You can upgrade a few things,
bed leg - can be any kind of wood, and can have an interior of metal - decreases chance of bed breaking when sleeping on it.
pillow - can be made of wool string or other soft substances, and can be covered in leather or cloth, which would be made from wool. - increases chance of passing night
headboard - can be any kind of wood, and can have an interior of metal - increases chance of setting spawn
footboard -  can be any kind of wood, and can have an interior of metal - increases chance of setting spawn
boxspring - made with metal springs, which would be a zig zag in the crafting table, and cloth and covered with leather - increases chance of passing night
mattress - made with wool hay etc and covered with cloth or leather - increases chance of passing night
sheets - made with cloth leather or leaves - increases chance of passing night - makes temperature coller upon waking up, which makes it a mid game alternative to cooling coils -
blanket - made with cloth leather or leaves - increases chance of passing night - makes temperature higher upon waking up, which makes it a mid game alternative to campfires or heating coils.

One would craft a bed panel. which would be

plank - plank - plank
stick - stick - stick
plank - plank -plank
you place this down, which doesn't do anything until you add a mattress, and then add upgrades from there on.

**Comment by WolfieWaffle** [comment]
Could be an interesting idea for a mod, but seems a bit large in scope for a small feature in the main mod.

**Comment by pastellexists** [comment]
Perhaps as an addon? Or optional modular.

**Comment by CorneliusCornbread** [comment]
Here's an idea, we could do an insomnia type deal where we have slept just speed up the sim speed and if there are too many mobs nearby the player (x radius) you could kick them out of bed to force them to sit in your house for the rest of the night or kill the mobs and go back to bed.
