### ISSUE TITLE
[SUGGESTION] More gradual altitude modifier

### ISSUE THREAD

**Issue by Tumlinh** [Glitchfiend/ToughAsNails#444]
Though a setting is available to configure the altitude modifier coefficient, temperature is modified every 64 blocks high, which makes the altitude modifier too sudden in my opinion.
That height should be configurable.

**Comment by MegahNevel** [comment]
`  # The maximum to increase/decrease temperature by depending on the altitude [range: 0 ~ 2147483647, default: 3]
    I:"Altitude Modifier"=3`
setting this to a hgher value doesnt work?

**Comment by Tumlinh** [comment]
This setting is the coefficient I was talking about. It doesn't allow you to configure the height between two successive values returned by the altitude modifier.
Actually the altitude modifier is quite unusual:
+ from 0 to 128 blocks high: -1°
+ from 128 to 192 blocks high: -2°
+ from 192 to 256 blocks high: -5°
+ from 256 to 320 blocks high: -8°
+ etc.

The expected result should be something like:
`altitudeModifier = -(MathHelper.floor((pos.getY() / heightStep) * temperatureStep)) + temperatureOffset;` with:
+ heightStep: the height between two successive changes
+ temperatureStep: the temperature step between two successive changes
+ temperatureOffset: if you want a positive modifier at some height

**Comment by dashkal16** [comment]
+1 to this.  I was hoping it would be possible to set the temperatures more or less by height so as to use temperature as a soft gate.
Basically, make <32 very hot, 32-96 sane, 96+ cold.
