### ISSUE TITLE
[Feature Request] Dynamic Day/Night system

### ISSUE THREAD

**Issue by MegahNevel** [Glitchfiend/ToughAsNails#445]
So I saw that other mods have the option to change the ammount of ticks of the day and night, I think this is a good feature to set longer days on summer and shorter on winter (aswell as longer night on winter and shorter ones on summer)
So time currently pass this way:
10 minutes of day
1.5 minutes dusk
7 minutes night
1.5 minutes dawn

I think maybe could be (dusk and dawn never changes)

Summer:
Default
Autumn
9min day and 8min night
Winter
7min day and 10 night (reverse default)
Spring
8min day and 9min night (reverse Autumn)

this can be made at each sub-season to make more realistic, but just having it at every "big" season would be really nice!

**Comment by Tumlinh** [comment]
This feature has just been merged a few days ago, have a look at #438 :)
