### ISSUE TITLE
[Bug] Biomes o'Plenty Liquids

### ISSUE THREAD

**Issue by MegahNevel** [Glitchfiend/ToughAsNails#446]
So i first met BOP cause i wanted more variety of biomes, and then i met TAN (at the download page)

Nowadays I play both mods, and one thing that i think is quite annoyning is when you get poison and it turns in dirty water, This also works for blood and i think (not tested) this works for quicksand and thermal water too

Why didnt get Blood (or nothing) from blood
Poison (or nothing) from poison (this can be displayed as dirty water, but inflicting hunger and poison aswell thirsty [all amplified])
nothing from Quicksand
And clean water from Thermal water

Also, being inside of blood actually triggers "wet" and cause you to get -7 temperature (maybe Wet on nether reverse the temperature, granting +7 instead?)

**Comment by scigeotech** [comment]
TAN does not add blood bottles or poison bottles, so that is not a bug (please change title).
