### ISSUE TITLE
Possible bug with Morpheus and this mod

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/ToughAsNails#447]
As of the latest updates to this mod, it appears Morpheus is not compatible with this mod. As Morpheus adds a system to sleep vote, and make it day. Your mod changes the length of the day, as a result, it spams the vote to make it day.

![screenshot 2018-02-27 20 01 08](https://user-images.githubusercontent.com/5614902/36764093-03d1bd64-1bf9-11e8-97f5-35f3bdea2262.png)

**Comment by Tumlinh** [comment]
As a workaround you can disable this feature in `seasons.cfg`.
When players wake up, the world time is set to the next MC day (0 % 24000), which doesn't necessarily correspond to the next sunrise, now that it depends on seasons.
