### ISSUE TITLE
Armor not cooling for warming player.

### ISSUE THREAD

**Issue by MastrPancake** [Glitchfiend/ToughAsNails#448]
When testing in creative and switching to survival the player temp does not change with wool armor on or off.

**Comment by MegahNevel** [comment]
im using latest version and it seems to be normal
use the command `/tan tempinfo` to check it out
sometimes temperature is so cold that even with a full set of wool armor you can get hypothermia

Also in the config files you can change how many temperature each piece of wool armor grants to you

**Comment by MastrPancake** [comment]
I actually changed the value to 10 to see if that would make a difference and still nothing. I removed all my mods to see if it was something conflicting and that wasn't the problem either.

**Comment by MastrPancake** [comment]
used temp info and it is working made my assumption on the UI up arrow. Was not sure why i did not see a different when changing the config the first time but all is well!

**Comment by MastrPancake** [comment]
Turns out i was right at first. Seems to be a conflict PrimalCore. I'll try to find a fix in the config.

**Comment by MastrPancake** [comment]
Sadly could not fine a config option for it. Left a post on the Primal Core bug page.
