### ISSUE TITLE
(1.12.2) New Worlds Start During Night-time

### ISSUE THREAD

**Issue by TechnoMysterio** [Glitchfiend/ToughAsNails#449]
New worlds always start at night-time, which isn't very good to allow players to gather resources and build a shelter, as monsters will spawn. This is due to the recent changes related to day length in the season system, so since the game starts in early spring, the added length of the night means that the game starts at night.

Perhaps it would be wiser to start the game in late spring instead, as the days are long enough to allow the game to start in the morning then.

TAN: 3.1.0.75
MC: 1.12.2
Forge: 14.23.2.2619

**Comment by Tumlinh** [comment]
#440 will correct that.
Solstices will be on early winter/summer, which means that equinoxes will be on early spring/autumn.

**Comment by Forstride** [comment]
I've removed the seasonal daytime feature for the time being, so this can be closed.
