### ISSUE TITLE
Suggestion: Config for warming/cooling equipment

### ISSUE THREAD

**Issue by RiverC** [Glitchfiend/ToughAsNails#451]
At the moment we have a json file where we can add items with their block temperature, for example, but what we don't have is a config for giving arbitrary items warming/cooling effects when worn, held, in inventory, etc. 

Right now we're limited to adjusting the value of the wool and/or slime armors per-piece in the main temperature config, whereas it would be wonderful to be able to not only adjust them by piece (i.e. making the chest piece give more body heat than the boots, etc) but allow us to give other items heating/cooling effects without those mod authors needing to write integrations.

As for the "while held / while in inventory" effect, that's an additional idea. A very quick example of "gives heat when held in hand" would be a lit torch. A good use case for "gives heat when in inventory" would be a bucket of lava. 

On the other hand, carrying a bunch of ice would probably lower your body temperature. Opens up a bunch of resourceful tricks for players in extreme environments (i.e. ice mountains, nether, deserts etc)

**Comment by Forstride** [comment]
The thing with inventory items affecting heat is that it's not really "obvious."  The inventory doesn't affect gameplay in any other way, and there are already enough things that can affect temperature as it is.  We want the things that affect the temperature system to feel obvious and make sense gameplay-wise, even if it's not "realistic."

As for armor temperature configs, that's another story, and there are already multiple issues open for that.
