### ISSUE TITLE
[Suggestion] Config option to tweak loot rate of Lifeblood Crystals in Nether Forteress

### ISSUE THREAD

**Issue by alxcool** [Glitchfiend/ToughAsNails#460]
Have you ever tried to learn 3 mods at the same time?
Right now I am playing 1.12.2 (Forge 2624) In solo player with
-ToughAsNails-1.12.2-3.1.0.87-universal
-PrimalCore-1.12.2-0.6. (V38 or 39)
-Survivalist-1.12.2-2.1.4
-Natura with extra mobs / clouds enabled.

My suggestion would be to allow the player to increase the probability to find "Lifeblood Crystals". I've read somewhere that in order to gain or regain my starting health (10 hearth) I have to loot chests inside nether Fortress. Just to say I have completely looted 4 fortress so far (average 6 chests). There was no items related to ToughAsNails.

So I guess you get my point. I could try to find some fun by increasing game's difficulty in early game, but over a certain point it become more pain than fun!

If you have ever tried in early game to travel through the nether, without armor because you have to wear the slime armor at all time, by having, only 5 hearth and an increased mob's spawning as difficulties its almost depressing! Furthermore completing the exploration of a full nether fortress without reaching your goal is quite discouraging.

This might be a bug, I should make some test in order to learn if this is possible, or not to complete the starter's hearth's quest, or if "Lifeblood Crystals" just won't be included inside nether's fortress's chests as loots.

Either-way, today, I've dl v.94 to try again and I would like to suggest to leave a config option who allow players to increase / reduce the spawn rate of those "Lifeblood Crystals" in the nether!

**Comment by Lurmey** [comment]
It would be handy to have a config option to adjust the spawn rate, yeah. The current rate is 1.4% to spawn 1 in each chest of a nether fortress. You can increase that with the luck potion effect, which if you want to you can give to yourself permanently using the command "/effect @p minecraft:luck 1000000 [power] true" where [power] would be a number from 1-255 denoting how strong you want the luck effect to be.

**Comment by Forstride** [comment]
I've removed the Lowered Starting Health feature, so this issue can be closed.

**Comment by alxcool** [comment]
Thk and sorry it took me so long to reply
