### ISSUE TITLE
[Suggestion] Support block variants in configuration

### ISSUE THREAD

**Issue by ddelaparte** [Glitchfiend/ToughAsNails#461]
Currently the block_temperatures.json offers no way to configure block variants. This would be helpful in cases such as supporting Primal Core's torches which have both a lit and an unlit state which are denoted by variant types of the same block.

Not sure what all would be entailed in adding support - Use of the meta id would be preferable since variant name is not always apparent or applicable. I'd looked through another mod's (Minestrappolation 5) block code and couldn't find variant names for their blocks, just references to meta id.

**Comment by Forstride** [comment]
Yes it does.  The default config contains an example showing campfires that give heat when their "burning" property is set to true.

"Variants" are just another property that blocks use.

**Comment by ddelaparte** [comment]
Aha! Thank you. It's working now. Not the clearest documentation though as I thought "properties" represented a property you wanted to give the block, not a property required for finding it. Now that I see the json basically represents the blockstate that makes a lot more sense.
