### ISSUE TITLE
[Mod Compatibility] Simulated Nights

### ISSUE THREAD

**Issue by ddelaparte** [Glitchfiend/ToughAsNails#462]
TAN almost works with Simulated Nights. Actually, it does work with some tweaking.

The issue is that with the default configuration seasons are changing like 10 times in a single night when sleeping. I had to increase "Sub Season Duration" to 120 to basically get what the default config does without Simulated Nights installed.

Not sure if this is a real issue since there's a workaround, but if you could maybe detect Simulated Nights being installed and adjust internally so no config is necessary, that'd be ideal.

**Comment by Forstride** [comment]
Closing this since we're moving seasons to a separate mod (https://github.com/Glitchfiend/SereneSeasons).
