### ISSUE TITLE
Add some randomness

### ISSUE THREAD

**Issue by Tumlinh** [Glitchfiend/ToughAsNails#464]
Vanilla weather is random but doesn't affect temperature, except if the player is wandering in the rain.
A random modifier could simulate wind, hot/cold spell, etc., and would have a small chance to spawn every tick with its own random duration (e.g. 1000−20000 ticks) and amplitude (+/- 5°).

**Comment by Forstride** [comment]
We used to have a random temperature offset that would change every day, and I thought about bringing it back, but it would be pretty hard to balance without making the effect less noticeable.

Having a completely random temperature change through the day is definitely not something we want though.

Also, rain and snow *should* affect temperature.  If it doesn't, that's another issue.
