### ISSUE TITLE
Incompatible with the 1.9.4 FTB Unstable pack 

### ISSUE THREAD

**Issue by jamzam90** [Glitchfiend/ToughAsNails#47]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.3.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  LoadingPlugin (Quark-beta-28.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  IC2core (industrialcraft-2-2.5.46-ex19.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/25/16 6:05 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z @53: ifeq
  Reason:
    Type 'toughasnails/api/season/Season' (current frame, stack[3]) is not assignable to integer
  Current Frame:
    bci: @53
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season' }
    stack: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season', 'toughasnails/api/season/Season' }
  Bytecode:
    0x0000000: 2ab6 096d 9a00 0503 ac2a 2bb6 02cc 9a00
    0x0000010: 0503 ac2a 2bb6 096f b601 782b b601 78a4
    0x0000020: 0005 03ac 2ab8 0794 b907 9a01 00b6 07a0
    0x0000030: 4d2a 2b2c 5999 0009 572a 2bb8 0972 b809
    0x0000040: 76ac  
  Stackmap Table:
    same_frame(@9)
    same_frame(@19)
    same_frame(@36)

```
at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:555)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z @53: ifeq
  Reason:
    Type 'toughasnails/api/season/Season' (current frame, stack[3]) is not assignable to integer
  Current Frame:
    bci: @53
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season' }
    stack: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season', 'toughasnails/api/season/Season' }
  Bytecode:
    0x0000000: 2ab6 096d 9a00 0503 ac2a 2bb6 02cc 9a00
    0x0000010: 0503 ac2a 2bb6 096f b601 782b b601 78a4
    0x0000020: 0005 03ac 2ab8 0794 b907 9a01 00b6 07a0
    0x0000030: 4d2a 2b2c 5999 0009 572a 2bb8 0972 b809
    0x0000040: 76ac  
  Stackmap Table:
    same_frame(@9)
    same_frame(@19)
    same_frame(@36)

```
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
at java.lang.Class.getMethod0(Class.java:3010)
at java.lang.Class.getMethod(Class.java:1776)
at com.rwtema.extrautils2.ExtraUtils2.<clinit>(ExtraUtils2.java:76)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:344)
at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:474)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:524)
... 10 more
```
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 331876256 bytes (316 MB) / 1388838912 bytes (1324 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1987 72 mods loaded, 72 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1987.jar) 
    UC  Forge{12.17.0.1987} [Minecraft Forge](forge-1.9.4-12.17.0.1987.jar) 
    UC  autopackager{1.6.3} [AutoPackager](autopackager-1.6.3.jar) 
    UC  bagginses{2.4.2d} [Bagginses](Bagginses-1.9.4-2.4.2d.jar) 
    UC  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UC  bdlib{1.11.0.1} [BD Lib](bdlib-1.11.0.1-mc1.9.4.jar) 
    UC  betterbuilderswands{0.6.2} [Better Builder's Wands](BetterBuildersWands-0.6.2-1.9.4r132+a2243db.jar) 
    UE  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UC  JEI{3.6.7.216} [Just Enough Items](jei_1.9.4-3.6.7.216.jar) 
    UC  BloodMagic{1.9.4-2.0.1-44} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.1-44.jar) 
    UC  Botania{r1.8-310} [Botania](Botania-unofficial.r1.8-310.jar) 
    UC  Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UC  CharsetLib{0.3.0-pre8} [?](Charset-mc1.9.4-0.3.0-pre8-4229a612686b6881.jar) 
    UC  CharsetTweaks{0.3.0-pre8} [*](Charset-mc1.9.4-0.3.0-pre8-4229a612686b6881.jar) 
    UC  CharsetStorage{0.3.0-pre8} [#](Charset-mc1.9.4-0.3.0-pre8-4229a612686b6881.jar) 
    UC  CharsetDecoration{0.3.0-pre8} [^](Charset-mc1.9.4-0.3.0-pre8-4229a612686b6881.jar) 
    UC  CharsetWrench{0.3.0-pre8} [/](Charset-mc1.9.4-0.3.0-pre8-4229a612686b6881.jar) 
    UC  chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.27.jar) 
    UC  chiselsandbits{10.7} [Chisels & Bits](chiselsandbits-10.7.jar) 
    UC  combathelp{1.0.3} [Combat Help](combathelp-1.9.4-1.0.3.jar) 
    UC  compactstorage{v2.0.0a} [CompactStorage](compactstorage-2.1-1.9.4.jar) 
    UC  compasscoords{1.9.4-3.1.4} [Compass Co-ords](CompassCoords-1.9.4-3.1.4.jar) 
    UC  cookingforblockheads{3.1.26} [Cooking for Blockheads](CookingForBlockheads-mc1.9.4-3.1.26.jar) 
    UC  CustomMainMenu{2.0.1} [Custom Main Menu](CustomMainMenu-MC1.9.4-2.0.1.jar) 
    UC  ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UC  deepresonance{1.2.0beta34} [DeepResonance](deepresonance-1.9.4-1.2.0beta34.jar) 
    UC  endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UC  EnderIO{1.9.4-3.0.0.43_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.43_alpha.jar) 
    UC  shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UC  endertanks{1.3.5} [EnderTanks](endertanks-1.9.4-1.3.5.jar) 
    UC  fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-MC1.9.4-1.7.jar) 
    UC  flatcoloredblocks{mc1.9.4-v3.1} [Flat Colored Blocks](flatcoloredblocks-mc1.9.4-v3.1.jar) 
    UC  IC2{2.5.46-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.46-ex19.jar) 
    UC  forestry{5.0.20.167} [Forestry](forestry_1.9.4-5.0.20.167.jar) 
    UC  forgeanalytics{0.0.0.16} [Forge Analytics](ForgeAnalytics-1.9-0.0.0.16.jar) 
    UC  ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre1.jar) 
    UC  ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre1.jar) 
    UC  advgenerators{0.9.20.1} [Advanced Generators](generators-0.9.20.1-mc1.9.4.jar) 
    UC  gravestone{1.3.0} [Gravestone](Gravestone Mod 1.3.0.jar) 
    UC  inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks](InventoryTweaks-1.61-beta-54.jar) 
    UC  IronChest{6.0.145.787} [Iron Chest](ironchest-1.9.4-6.0.145.787.jar) 
    UC  itemscroller{0.5.1} [Item Scroller](itemscroller-1.9.4-0.5.1.jar) 
    UC  journeymap{1.9.4-5.2.3} [JourneyMap](journeymap-1.9.4-5.2.3-unlimited.jar) 
    UC  jeresources{0.4.6.35} [Just Enough Resources](JustEnoughResources-1.9.4-0.4.6.35.jar) 
    UC  mantle{1.9.4-0.10.2.jenkins149} [Mantle](Mantle-1.9.4-0.10.2.jar) 
    UC  testdummy{1.10} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UC  moreoverlays{1.4} [MoreOverlays](moreoverlays-1.4-mc1.9.4.jar) 
    UC  Morpheus{1.9.4-3.1.5} [Morpheus](Morpheus-1.9.4-3.1.5.jar) 
    UC  MouseTweaks{2.6.3} [Mouse Tweaks](MouseTweaks-2.6.3-mc1.9.4.jar) 
    UC  netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UC  notenoughwands{1.3.5} [Not Enough Wands](notenoughwands-1.9.4-1.3.5.jar) 
    UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4b.jar) 
    UC  progressiveautomation{1.6.46} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.46.jar) 
    UC  Psi{r1.0-35} [Psi](Psi-r1.0-35.jar) 
    UC  Quark{beta-28} [Quark](Quark-beta-28.jar) 
    UC  randomthings{3.7.3} [Random Things](RandomThings-MC1.9.4-3.7.3.jar) 
    UC  StorageDrawers{1.9-3.1.8} [Storage Drawers](StorageDrawers-1.9-3.1.8.jar) 
    UC  refinedstorage{0.7.16} [Refined Storage](refinedstorage-0.7.16.jar) 
    UC  xreliquary{1.9.4-1.3.2.390} [Reliquary](Reliquary-1.9.4-1.3.2.390.jar) 
    UC  ResourceLoader{1.5.1} [Resource Loader](ResourceLoader-MC1.9.4-1.5.1.jar) 
    UC  rftools{4.64} [RFTools](rftools-1.9.4-4.64.jar) 
    UC  rftoolsdim{4.30beta43} [RFTools Dimensions](rftoolsdim-1.9.4-4.30beta43.jar) 
    UC  simpleretrogen{3.0.1+6} [Simple Retrogen](simpleretrogen-1.9.4-3.0.1+6.jar) 
    UC  soulshardstow{1.9.4-2.4.4-32} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.4-32.jar) 
    UC  tconstruct{1.9.4-2.3.2.jenkins255} [Tinkers' Construct](TConstruct-1.9.4-2.3.2.jar) 
    UC  theoneprobe{1.0.10} [The One Probe](theoneprobe-1.9.4-1.0.10.jar) 
    UC  ToughAsNails{1.0.3} [Tough As Nails](ToughAsNails-1.9.4-1.0.3.jar) 
    UC  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UC  ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9.4-2.2.1.192.jar) 
    UC  wawla{2.2.1.188} [What Are We Looking At](Wawla-1.9.4-2.2.1.192.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  lumien.custommainmenu.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.3.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-beta-28.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.5.46-ex19.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 960/PCIe/SSE2'
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - chiselsandbitsIntegration (Enabled/Not Forced)
    - WailaIntegration (Enabled/Not Forced)
```

**Comment by Adubbz** [comment]
I need more details than just a crash... I need the fml-client-latest.log as well as the circumstances under which this happened

**Comment by jamzam90** [comment]
All i did was add it to the FTB Unstable pack

http://pastebin.com/hdLCwSQ0

**Comment by Adubbz** [comment]
This looks like an incompatibility with RandomThingCore, and looking at their code, i'm honestly not sure if there is any way around it. We both try to inject code into isRainingAt which simply cannot be avoided.

If this is 'fixed' from our end, it will simply be loading after it, and destroying any code that isn't what we want, ultimately breaking whatever functionality RandomThingsCore is trying to provide. I think whichever approach we take, RandomThingsCore still isn't going to work properly with TAN.

**Comment by Adubbz** [comment]
Hrm, actually, I have one idea for potentially fixing it... I'll have to see how it goes

**Comment by Adubbz** [comment]
From my initial testing things seem to work fine with the two mods now, although I'll have to see if that stays the case
