### ISSUE TITLE
Crashing? 

### ISSUE THREAD

**Issue by Kurdaneva** [Glitchfiend/ToughAsNails#471]
I've been trying to use this mod for a while and I always end up crashing. I've found plenty of mods that it doesn't seem to work with, but I'm slightly frustrated because I ran it recently and it worked fine, however I had to remove BoP due to lag and now I can't even open MC. It just keeps giving me this error.

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)" While I know this doesn't give much information, if someone could help me find a way to learn WHY it keeps crashing, I'd be really happy.. I really do love this mod and the fact I can't play it sucks.

**Comment by Lurmey** [comment]
Head to your installation and drag the most recent file in the "crash-reports" folder into here on Github. That'll help.

**Comment by Kurdaneva** [comment]
[crash-2018-04-02_20.04.11-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1886176/crash-2018-04-02_20.04.11-client.txt)
 
Tell me if i've done this correctly and thank you for your help.

**Comment by Lurmey** [comment]
That's right, thank you. I can't help you any further but hopefully, someone else can read that report and fix the problem for you. Good luck c:
