### ISSUE TITLE
Heating Coils Buggy When Off

### ISSUE THREAD

**Issue by talayawhite** [Glitchfiend/ToughAsNails#473]
There have been a few topics about the heating coils, but they all seem to be... not quite accurate? Confusing? Dismissed?
Anyway. I'll try to explain as best as I can.

Heating Coil When Off:
Does Not support crops. √
Does Not seem to check for floodfill/indoor/space parameters?
Heats indiscriminately.
Dimmed Appearance. √
All this means that if the heating coil is placed but OFF, crops die, but player overheats in winter, whether they are inside or outside.

Heating Coil When On:
Supports Crops. √
Keeps building warm in winter, but not hot. √
Makes building HOT in summer. √
Outside it's cold. √
Bright Appearance. √
So it seems like it works exactly as it should when it's on. The problem comes in when it's summer and you want it off, you have to break the block and pick it up to stop it heating, and heating, and heating.

**Comment by Lurmey** [comment]
I've had this issue too, breaking and replacing the coil seems to fix it temporarily but it's really annoying overheating outside in the dead of winter.

**Comment by talayawhite** [comment]
@Lurmey, I think maybe it seems like it's "temporarily fixed" because there's a wonky feedback loop which gets reset when you break the block. It's still broken, but it seems like it's fixed for a minute because it takes a while to heat back up again.
