### ISSUE TITLE
[Suggestion] Replace water liquid with new dirty water

### ISSUE THREAD

**Issue by Lurmey** [Glitchfiend/ToughAsNails#475]
I'd like to suggest the idea of replacing the entirety of all of the natural water spawning in the world with a new liquid that looks and acts identical to water, "Dirty water", which can't be used for recipes with mods. It can be purified industrially somehow, or clean water can be acquired using the rain collector. Infinite water sources from mods do break this idea, but they can very easily be disabled in modpacks.

It would make providing water for machinery, drinking and cooking alike more difficult and realistic. Having proper plumbing in your base or town sounds really cool to me. I'd love to build a water tower and have that provide for my water needs. I can do that now, but there are easier sources of water in my modpack such as just pumping water from the ocean or using an aqueous accumulator from Thermal Expansion.

Side note; being able to simply right-click on a water source in the world to drink it would be very handy in the early-game.

**Comment by Forstride** [comment]
We were going to do this at one point, but it likely would've just caused way too many issues with mod compatibility.  Plus, if you removed the mod from a world, it would get completely fucked up.  Invasive world gen like that is something we want to avoid with TAN.

As for drinking straight from water sources, that's something I want to add, but I need Adubbz's help for it, and he hasn't been around much lately.

**Comment by Lurmey** [comment]
Ah, okay. Good point. Perhaps it would be easier and more compatibility friendly to do it the other way around, make a new liquid which is the cleaned water, and treat vanilla water as dirty water without changing it. You'd have to somehow override other mods crafting recipes and such so they need to use the clean water instead, but perhaps modpack authors can just do that using mods such as CraftTweaker.
