### ISSUE TITLE
Are Tough as Nails and Serene Seasons not compatable? 

### ISSUE THREAD

**Issue by StarlightDaemon** [Glitchfiend/ToughAsNails#476]
Forge 14.23.2.2654
Forge 14.23.2.2611
Tough as Nails 3.1.0
Serene Seasons 1.0.0

**Comment by Forstride** [comment]
For now, no.  @Adubbz still has to remove the seasons from TAN and add support for Serene Seasons.  Just uninstall SS for now.

**Comment by StarlightDaemon** [comment]
Thanks for the fast update and info 👍

**Comment by Forstride** [comment]
Just letting you know that seasons have been removed, and support has been added for Serene Seasons in the latest build.
