### ISSUE TITLE
Water Hole Chunk Bug.

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/ToughAsNails#48]
A strange bug causes to spawn this weird chunks in your world with water starting always at Y: 63
It seems like a ocean tried to generate after the terrain itself was already done.
I can confirm this also happens without BOP.

![2016-06-25_20 16 12](https://cloud.githubusercontent.com/assets/19509275/16358482/e767ee54-3b13-11e6-9518-0fdced1efccf.png)
![2016-06-25_20 16 16](https://cloud.githubusercontent.com/assets/19509275/16358485/e7806f92-3b13-11e6-941e-b181f5e245e0.png)
![2016-06-25_20 16 27](https://cloud.githubusercontent.com/assets/19509275/16358483/e76824e6-3b13-11e6-8f52-7d3f50924a4f.png)
![2016-06-25_20 18 40](https://cloud.githubusercontent.com/assets/19509275/16358484/e76cd91e-3b13-11e6-935c-8b81eb346e95.png)

**Comment by Adubbz** [comment]
I can't seem to reproduce this at all. Does this occur with TAN on its own?

**Comment by Quizer9O8** [comment]
Yes, the latest version to be precise

**Comment by Forstride** [comment]
And did you test it without TAN?

**Comment by Quizer9O8** [comment]
yes, i did. I also used the same seed to make sure if it was gone and it was.

**Comment by Adubbz** [comment]
What is the seed you used?

**Comment by Quizer9O8** [comment]
For BOP I used -78688046
The location: X -87 Z 292

This bug seems to happen in any world type no matter what if you use TAN.

**Comment by Adubbz** [comment]
http://i.imgur.com/K0RHo1V.jpg

With Forge 1.9.4 - 12.17.0.1976, Biomes O' Plenty 1.9.4 - 4.1.0-2033 and Tough As Nails 1.0.3. All outside of eclipse. Would you be able to link your fml-client-latest.log file for when TAN is just on its own?

**Comment by Adubbz** [comment]
Also if you haven't already, update Forge

**Comment by Quizer9O8** [comment]
With BOP and TAN: http://pastebin.com/Ge59fT5q
With Other mods included: http://pastebin.com/tTby1Q5Q
TAN on its own: http://pastebin.com/gW4ky6jK

After changing the preferred Release type from Beta  to Release in Curse, the problem seems to be fixed on it own somehow.

**Comment by Quizer9O8** [comment]
I spoke too soon...

![2016-06-26_20 04 41](https://cloud.githubusercontent.com/assets/19509275/16363902/4e7b4364-3bd9-11e6-9215-8bad5e26d4d1.png)

**Comment by Adubbz** [comment]
The only other thing I could think of in that case then is try using the standard Vanilla launcher (Not the Curse launcher), with just TAN and Forge. Aside from that, there's nothing that stands out as out of the ordinary in those logs... I'm really not sure what to say here... Neither Forstride nor I can get this to happen which makes fixing it nigh impossible, especially since TAN doesn't touch terrain generation at all :(
