### ISSUE TITLE
[suggestion] right click empty handed on water source will drink water

### ISSUE THREAD

**Issue by winsrp** [Glitchfiend/ToughAsNails#483]
So doing around in a hardcore map I spawed in a cold biome with deers all over the place that turns out dont spawn leather... so with no way to pick up or drink water after running around for a day an a half I died..... sad story.

So how about, when you are empty handed over a water source block it will drink a little bit of dirty water?

**Comment by Forstride** [comment]
Already have an issue for this: https://github.com/Glitchfiend/ToughAsNails/issues/204
