### ISSUE TITLE
Crashing API-Issue with Season Helper in Build 1.12.2-3.1.0.97 and above (Serene Seasons)

### ISSUE THREAD

**Issue by courseofra** [Glitchfiend/ToughAsNails#489]
Hi dear team,

[crash-2018-04-20_18.54.21-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1934184/crash-2018-04-20_18.54.21-client.txt)

Best regards
Christian

**Comment by Forstride** [comment]
You need to wait for Dynamic Surroundings to update
