### ISSUE TITLE
[suggestion] config option to disable dirty water mechanic but not thirst

### ISSUE THREAD

**Issue by xkforce** [Glitchfiend/ToughAsNails#490]
I like the thirst mechanic itself but I wish that the dirty water mechanic were separated from it so that the player had to drink occasionally but didn't have to deal with the dirty water mechanic on top of it.  As far as I know, the only way to disable the dirty water mechanic is to disable thirst as well.

**Comment by Forstride** [comment]
Probably not gonna happen.  I just recently changed the dirty water mechanic though so by default, you get normal water (Which still has a high chance of giving the thirst effect) when using empty bottles/canteens on source blocks, but filtering/boiling it gives you purified water.  So the additional "filtered water" step is removed, making things much more streamlined.
