### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jonarlin** [Glitchfiend/ToughAsNails#497]
[crash-2018-04-24_20.21.44-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1943885/crash-2018-04-24_20.21.44-client.txt)

Using version 3.1.0.113
Tried with and without Serene Seasons (the crash report seemed to say it was related to season handler), no apparent effect

**Comment by xkforce** [comment]
I am also having a crash but it isn't consistently reproducible with TAN by itself.  I am also crossposting this @ serene seasons.

Minecraft log: https://pastebin.com/tiA3484p

**Comment by Forstride** [comment]
You need to wait for Dynamic Surroundings to update

**Comment by xkforce** [comment]
Is dynamic surroundings a dependency now?  Because there does not appear to be any mention of this on the mod page on curse or the wiki if it is.  If it isn't, then this crash is still happening with just TAN and serene seasons.

**Comment by Forstride** [comment]
No.  They just haven't updated their mod to remove old season support for TAN and change it to support SS.

As for crashing with TAN and SS, that's a different issue, and there's already one open for it.
