### ISSUE TITLE
Chests wont open. 

### ISSUE THREAD

**Issue by rjohnson98126** [Glitchfiend/ToughAsNails#498]
MC 1.12.2 (Forge 14.23.3.2655)
TAN 1.12 (v 3.0.0.68)

chests can be crafted and placed, single or double as expected, but will not open for anyone including the player who placed them.   destroy, replace, no change.

please let me know if i'm missing some config setting, this makes no sense as the rest of the mod works as expected, crafting recipes work as expected

**Comment by Forstride** [comment]
Not being able to open chests is generally due to server lag, and that could be caused by a variety of things.  Gonna need a bit more info like a log file or something, otherwise we can't help you.

**Comment by KnightMiner** [comment]
This does sound like a bug with Optifine that people keep reporting to other mods. If you have Optifine, either remove it or try updating it.

**Comment by rjohnson98126** [comment]
thanks for the hint.  i had forgotten about this as I havent looked at it
since then, because it's not playable if nobody can open any chests.   and
this was on three separate installs (two linux and one windows)

but we are all using Optifine, so i'll take another look, and start by
removing optifine and try again.  since this is now closed, i'll open a new
issue with more info if it still happens.

**Comment by rjohnson98126** [comment]
just fyi,i can tell you it wasn't lag.   playing on a lan with no noticable
lag and high individual FPS.   But i'll run it on my tower's dedicated
server that shows 20.00 TPS, just to make sure.
