### ISSUE TITLE
[SUGGESTION] Making the now removed Lowered Starting Health Feature as a seperate Mod like Serene Seasons.

### ISSUE THREAD

**Issue by TripleTomTv** [Glitchfiend/ToughAsNails#502]
I don't know the exact reason behind the removal of this feature, (Maybe most users just didn't use it at all or didn't like it?) , but i actually found this feature to be very useful for me and for modpack makers who want more of a vanilla gameplay style in their modpacks.
It offered great configuration while still being extremely simple. It even allowed customizable max health like 20 hearts instead of 10 by using the Lifeblood Crystals.
It was perfect for what it was in my opinion and now i'm sad that it got removed entirely.
I really hope this feature won't just fall into oblivion and instead will be released as it's own mod in the future.

**Comment by Forstride** [comment]
There are other mods that can do this already AFAIK, and better than we did.  That's one of the main reasons it was removed.
