### ISSUE TITLE
[Suggestion] Player gets tired if he doesn't sleep

### ISSUE THREAD

**Issue by Telknub** [Glitchfiend/ToughAsNails#505]
Adds an option in the mod that if the player doesn't sleep too often he starts to get tired and have side effects like slowness and mining fatigue pretty much like better sleeping did in the past

**Comment by Forstride** [comment]
Ehh, not a huge fan of this idea.  Plus Mojang is implementing the Phantoms in 1.13 that deal with not sleeping in a different way.
