### ISSUE TITLE
In survival mode, bottles occasionally create "uncraftable potion" when filling

### ISSUE THREAD

**Issue by ttamttamS** [Glitchfiend/ToughAsNails#507]
Title says it all, gameplay wise it changes surprisingly little, but I figured I'd report it.

**Comment by Forstride** [comment]
Are you using the latest version of the mod?  We don't override bottle filling anymore, so water bottles should just give normal water now.  If the issue is occurring on the latest version, it might be caused by another mod.

**Comment by ttamttamS** [comment]
I think I'm one version behind, I didn't notice anything in the change log mentioning bottle filling. I'll do some more testing and if it's not on your end I'll just override it with scavenge. Thanks!

**Comment by Forstride** [comment]
1.12.2-3.1.0.104 is when the change was made.  Although I accidentally put "vanilla water blocks" instead of "vanilla water bottles" in the commit

**Comment by ttamttamS** [comment]
My bad, it seems like the mod "thirsty bottles" is doing this, or something else changed that fixed it, thanks for the support!
