### ISSUE TITLE
crash with dynamic surroundings

### ISSUE THREAD

**Issue by GEGNA** [Glitchfiend/ToughAsNails#508]
i just updated to latest TAN.
[crash-2018-04-28_20.37.05-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1957487/crash-2018-04-28_20.37.05-client.txt)

i also crashed with fps reducer
[crash-2018-04-28_19.03.02-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1957488/crash-2018-04-28_19.03.02-client.txt)

**Comment by Adubbz** [comment]
You need to wait for Dynamic Surroundings to support the new TaN.
