### ISSUE TITLE
Changing items texture (128x128)

### ISSUE THREAD

**Issue by gosthrider** [Glitchfiend/ToughAsNails#509]
Hi there!
I've drawn some new textures for TAN items, so it will look better with higher resolution ressource packs.
But now I don't know what to do with them!
I tryied to put them in my texture pack, doesn't work.
So I opened the TAN .jar file with winrar, put the new textures in it and repack it, but after that the mod is not launching...

So, the problem is pretty simple, any help ?

**Comment by Forstride** [comment]
It's the same as any texture pack support for a mod would be.

Inside the texture pack ZIP, you'd have the assets folder, and then inside that would be a folder called toughasnails.  And then you have the folders for textures, models, etc.
