### ISSUE TITLE
Crash on connection to server or new single player game.

### ISSUE THREAD

**Issue by madhatr** [Glitchfiend/ToughAsNails#511]
MC 1.12.2
TaN 1.12.2-3.1.0.116

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: toughasnails/api/season/SeasonHelper
Multi-
[crash-2018-05-06_15.21.04-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1977908/crash-2018-05-06_15.21.04-client.txt)
Single-
[crash-2018-05-06_15.30.26-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1977909/crash-2018-05-06_15.30.26-client.txt)

I had just upgraded from ToughAsNails-1.12-3.0.0.67-universal to ToughAsNails-1.12.2-3.1.0.116-universal.

**Comment by Forstride** [comment]
Update Dynamic Surroundings
