### ISSUE TITLE
Cold and Heat Resistance

### ISSUE THREAD

**Issue by Beta-Carotene** [Glitchfiend/ToughAsNails#516]
Cold and Heat Resistance are registered as bad effects. This can cause unintended things, like Potion Core's cure, to interact with them.

**Comment by Forstride** [comment]
Unless there's something I'm missing, there's no other kind of variable I can change for them, and AFAIK, cold/heat resistance appears on the same bar that other positive effects do.

Are you sure you're on the latest version of the mod?

**Comment by KnightMiner** [comment]
[This line](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/potion/PotionColdResistance.java#L11), the true means `isBadEffect`.
