### ISSUE TITLE
[Suggestion] A config setting for players needing purified water to drink

### ISSUE THREAD

**Issue by GreatestFool** [Glitchfiend/ToughAsNails#519]
While I'd say normally it would work fine as is, for packs with themes like post apocalyptic settings or the like I feel being able to pick up glowing green water without purifying it is a little sketchy. This isn't your fault though.

What I wanted to ask was if it is possible to add a config setting that makes players need to drink purified water for any effect.

And if it isn't to much work, a secondary config option that has a chance to give the player a status effect like hunger or something if you drink a normal water bottle.

**Comment by GreatestFool** [comment]
Why was this closed?

**Comment by Forstride** [comment]
Because the mod has been completely rewritten and mostly existing issues are likely irrelevant at this point.  Also, this is a nearly 3 year old issue, and I'm not gonna cherry pick what may or may not be relevant still.
