### ISSUE TITLE
strange crash with ExtraUtils (1.9.4)

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#52]
I get this strange crash when both ToughAsNails and ExtraUtils are installed http://pastebin.com/mWTsNtsT

**Comment by Adubbz** [comment]
Seems that link is invalid...

**Comment by Hypsellis** [comment]
I seems that Pastebin is inacessible for the time.

**Comment by 0Navis0** [comment]
Oh yeah it didn't copy well, anyway here is the crash report http://pastebin.com/mWTsNtsT

**Comment by Adubbz** [comment]
Please update the mod to 1.0.4, this looks like the same issue that was fixed for RandomThingsCore

**Comment by 0Navis0** [comment]
I passed to the 1.10 for the both mods, and yeah it seems to solve the problem. ;)
