### ISSUE TITLE
Climatisation effect doesn't disappear under a specific condition

### ISSUE THREAD

**Issue by Nullga** [Glitchfiend/ToughAsNails#520]
TAN 1.12.2-3.1.0.118
Forge 2689
No sponge

Place two redstone torches on both a side and the top of a heat coil at where all the other sides of the heat coil filled with any blocks at two block heights will cause climatisation effect to be kept even leaving to far away from the setup. I tested this setup in a brand new world inside a building with a ceiling but no walls between inside to outside. Not sure if there are other conditions to reproduce this.

**Comment by Nullga** [comment]
Actually this seems to happen not always but sometimes. I'm attaching screenshots. If there are no blocks around the coil, it extends climatisation effect but eventually gone after minutes past. If there are blocks around it, it keeps nearly forever until when getting close to the coil again.
https://imgur.com/a/nljDU7k

**Comment by dannydjdk** [comment]
I am also able to reproduce this bug. Both the heating and cooling coil climatisation affect extend a long distance even with no roof overhead. The climatisation affect for the heating coil persists long after the redstone signal is turned of and/or the block is removed.
In my test setup, I had a single lever next to the coil.
This can be reproduced in 3.1.0.120 with Forge 2705. It could not be reproduced in 3.1.0.115. I haven't tested all the versions in between, but it appears to have been introduced somewhere from 116-118.
