### ISSUE TITLE
Thirst Effect Bug?

### ISSUE THREAD

**Issue by Vivid-Nightmare** [Glitchfiend/ToughAsNails#522]
When i drink dirty water, the thirst effect persists even after 30 seconds. The Thirst bar is still green and the effect is still there, saying "Thirst: 0:00"

**Comment by Forstride** [comment]
Need a bit more info than that.  What version of the mod and Forge are you using?

**Comment by Vivid-Nightmare** [comment]
Last available version for both Forge and TAN.

**Comment by erindal** [comment]
I can confirm this bug,
Forge: 14.23.4.2708
TAN: 3.1.0.115

Relog seems to fix the bug (I'm wondering if it's visual).

**Comment by captcookie** [comment]
is there a way to lower the thirst debuff to less seconds?
