### ISSUE TITLE
Thirsty consuming all the saturation when not full

### ISSUE THREAD

**Issue by vrork** [Glitchfiend/ToughAsNails#526]
When you are not "full of water" (aka, all your pips of water arent complet, not matter how much saturation you have, they will very quickly disappear.

By saturation i mean, the extra contour on the food pips.

**Comment by dannydjdk** [comment]
This is most likely a bug with Tough Expansion and not Tough As Nails. See #527

**Comment by dannydjdk** [comment]
Just reported this on Tough Expansion bug tracker: https://github.com/p455w0rd/ToughExpansion/issues/35
