### ISSUE TITLE
Thirst status effect is pointless

### ISSUE THREAD

**Issue by Kalmeira** [Glitchfiend/ToughAsNails#528]
The thirst status effect seems completely pointless. Water being infinite, you can just keep drinking until your bar is filled and the effect will go away leaving you with plenty of water left. One option to fix this is to have the thirst effect prevent you from drinking and make sure the thirst effect takes off more water than you restore from drinking the bad water, or replace it with other status effects like long duration nausea, slowness, etc. representing that you are getting sick off of the water.

**Comment by Forstride** [comment]
It works the same as the vanilla Hunger effect that you get from eating raw chicken/rotten flesh.  There are issues with it on older versions (Before 1.12.2) though, where the effect didn't work properly.
