### ISSUE TITLE
Thirst

### ISSUE THREAD

**Issue by SkippyMitch** [Glitchfiend/ToughAsNails#529]
In my humble opinion,
It would be easier (more immersive) for the starting "nomadic" player to be able to quench his thirst without smelting up a glass bottle to drink from at first. 
For example; crafting a piece of cobblestone into a scoop or water dish, if you will. It would be slow to quench the players thirst, and 100% guaranteed thirst debuff effect, but at least something to keep you alive until you decide to make glassware. Or maybe we could simply do this with a wooden bowl? 

Just my .02

thanks for reading

**Comment by seasonedfish** [comment]
Perhaps you'll be interested in the [Slurp](https://minecraft.curseforge.com/projects/slurp?gameCategorySlug=mc-mods&projectID=272781) add-on. It might be not quite what you are looking for, but it's a similar concept.
