### ISSUE TITLE
[feature suggestion] new sleeping system

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#53]
I come with this idea to add a sleeping bar wich decreases slowly with the time, and descreases quicker when the player run or do an action. When the bar comes to 0, the player feels bad effect like confusion, blindness, weakness. And after a little time, he will begin to loose life. The player can sleep when he wants if his bar isn't to the max and will stay in the bad the time the sleeping bar rise to the max.
This idea comes from the mod better sleeping http://minecraft.curseforge.com/projects/better-sleeping?gameCategorySlug=mc-mods&projectID=227114
I know that it will probably not happen, but maybe ToughAsNails and BetterSleeping could merge since the two mods do aproximately the same thing.

**Comment by Forstride** [comment]
I'm not a fan of exhaustion mechanics in games like Harvest Moon and whatnot.

**Comment by 0Navis0** [comment]
Ah it's not matter, I understand. Anyway BetterSleeping is already here, and it fits pretty well with ToughAsNails. ;)

**Comment by 0Navis0** [comment]
I come back with this idea because I think it would be really interesting feature to add to Tough As Nails, it's for me one the thing it misses the most. After why not add it as an option you can activate through config if you aren't really fan from exhaustion mechanic ?
