### ISSUE TITLE
Canteen Bug

### ISSUE THREAD

**Issue by LamePos** [Glitchfiend/ToughAsNails#539]
The canteen doesn't seem to work as intended. Filling it up brings its durability to 2/3, after one use, it drops to -2/3, after a second use it drops to -6/3. Using it a third time will return it to its empty state.

Canteens also can't be boiled in furnaces.

This bug seems to go back atleast one release.

**Comment by KnightMiner** [comment]
From what I have tested, filling the canteens was working correctly, but the durability display tag is broken. It seems it is displaying the damages at it would on a tool (higher metadata is more damage) rather than an item with both fill values and variants.

**Comment by Forstride** [comment]
Not sure about the first issue, but canteens are intentionally not able to be boiled.  It wouldn't exactly make sense to put something made of leather in a furnace, and it's also there for balancing purposes, as canteens are early game items that let you carry a decent amount of water.

You'll have to use a rain collector, or boil water in a bucket, place it down, and then collect it with the canteen (I think that should work?  I remember having issues with it, but I don't remember if I ever actually fixed it or not).

**Comment by LamePos** [comment]
The Rain Collectors seem to work, though there's a similar aesthetic bug with the durability tooltip. It fills up to 1/3 and each successive sip reduces the durability by 4 to -3/3 and then -7/3. But it stills works.

The only problem with the rain collector is you can continue to deplete the rain collector when the canteen is full, at 1/3, but obvious the canteen will not fill up anymore and the rain collector will drain, wasting water.

Also, canteens don't fill up from Purified water sources. I've sat in the water source and near it and the canteen simply doesn't fill up.

Version : 1.12.2-3.1.0.124
