### ISSUE TITLE
[Suggestion] Visual effects based on actual outside temperature, not current body temperature.

### ISSUE THREAD

**Issue by Zunlite** [Glitchfiend/ToughAsNails#541]
If you were to go outside in the extreme cold/hot real life you dont feel fine then suddenly start snapping to cold, freezing, then death. or the same for hot. You will instantly feel that it is very cold and THEN will later start dying to it.

What im saying is that you know how when your temp is at certain levels the screen is tinted blue or orange? Instead of having it like that how about having screen tints based on what your temperature is shifting to. If its hot outside then instant orange tint no matter how hot your character actually is. Same for the opposite. Its also much easier to notice compared to the simple arrow animation occasionally appearing.

**Comment by Forstride** [comment]
It's a video game.  The overlay is just meant to be an additional warning for when you're getting close to dangerous temperature levels.
