### ISSUE TITLE
Purified water bucket creates stone

### ISSUE THREAD

**Issue by Ademonjh** [Glitchfiend/ToughAsNails#543]
If I dump purified water out of a bucket and it overflows into a natural water source (river) then it "freezes" the top layer of the normal water into normal stone. It looks similar to how when water touches lave source blocks it creates obsidian...except in this case its creating stone out of water.
Using Build 1.12.2-3.1.0.124

**Comment by Forstride** [comment]
This is intentional.  Fluids need to have "mixing" interactions, because if two fluids are directly touching, it looks buggy.
