### ISSUE TITLE
Purified water doesn't work in Brewing stand

### ISSUE THREAD

**Issue by Ademonjh** [Glitchfiend/ToughAsNails#546]
Not sure if this is a bug or not, but should Purified water work in a brewing stand?
Build 1.12.2-3.1.0.124

**Comment by Forstride** [comment]
I really don't see why that would be needed.  Purified water takes an additional step to create, which would make it pointless to use for potions, and in general, potions are kind of seen as a "dirty" item (Seeing as the base uses nether wart), so it wouldn't make sense to use purified water for that.
