### ISSUE TITLE
Season Clock and Sensors unclear

### ISSUE THREAD

**Issue by Biochao** [Glitchfiend/ToughAsNails#55]
Currently the Season Clock shows the seasons as various colors related to the seasons temperature. That can be unclear to someone who doesn't know what colors relate to what season. Especially the colors for summer and fall being so similar.

My suggestions are to have the Season Clock print the current season in chat when right clicked and have the Season Sensor update the item name so it shows the currently selected season in WAILA.

**Comment by Forstride** [comment]
I disagree about the season clock being unclear.  The season sensor, maybe, but it's not really hard to tell which season it is...
