### ISSUE TITLE
[BUG] Heating/Cooling Coils not working

### ISSUE THREAD

**Issue by Vivid-Nightmare** [Glitchfiend/ToughAsNails#552]
![2018-07-16_09 45 02](https://user-images.githubusercontent.com/37781902/42760765-c754d864-890b-11e8-9126-acaacaef9d09.png)
(I'm a little warm because I was using lava to warm up) They don't work at all, both of the coils. I'm using the latest version of TAN, I have tried updating the Forge Version but the issue does not go away.

**Comment by TheLoneTec** [comment]
i too have this issue, but its also in a huge modpack, so there could be many issues, but without error logs, cant find out why :)

**Comment by ilvrak** [comment]
[1.12.2-3.1.0.141] my heaters work. they just need opaque blocks above them and heat spreads through them. coolers the same
