### ISSUE TITLE
Crash when adding Immersive Engineering multiblocks to block_temperature.json

### ISSUE THREAD

**Issue by copygirl** [Glitchfiend/ToughAsNails#556]
When adding multiblock machines such as the Coke Oven from Immersive Engineering to the `block_temperature.json` config file, the game crashes with the following exception:

```
java.lang.ClassCastException: com.google.common.collect.RegularImmutableList cannot be cast to com.google.common.collect.ImmutableSet
	at toughasnails.util.BlockStateUtils.getPropertyValueByName(BlockStateUtils.java:119)
	at toughasnails.config.json.BlockStatePredicate.apply(BlockStatePredicate.java:62)
	at toughasnails.temperature.modifier.ObjectProximityModifier.getBlockTemperature(ObjectProximityModifier.java:75)
	[...]
```

I add entries similar to the following to the config file:

```js
{
  "state": {
    "block": "immersiveengineering:stone_device",
    "properties": {
      "type": "coke_oven",
      "_0multiblockslave": "false", // false = this is the master block
      "boolean0": "true"            // true = the machine is currently running
    }
  },
  "temperature": 6.0
}
```

[Here's a link](https://gist.github.com/copygirl/b541ec1385b5c068fd1f1e4b3bbde98d) to all the entries I add to the config file as well as the full crash report, if needed.

**Tough As Nails:** `3.1.0.126`
**Immersive Engineering:** `0.12-82`

**Comment by IdrisQe** [comment]
IE: 0.12.85
TAN: 3.1.0.129

Same issue here. I was going mad trying to figure out what was causing the crash, running my code through JSON validators, triple checking I had the right values and names...
and it turns out it's just some incompatability. There's like 2 hours wasted.

**Comment by serialtasted** [comment]
Have you ever figured this out? It seems the devs from this mod don't give any answers about this topic
