### ISSUE TITLE
Minecraft lags and doesn't save progress when a cooling coil is used in the nether.

### ISSUE THREAD

**Issue by Rufflikerex** [Glitchfiend/ToughAsNails#558]
To combat the heat in the nether without slime access I decided to build a cooling coil to place into my nether base. However, whenever I hook up redstone to the cooling coil the entire nether lags. If I were to exit the nether or quit the game while leaving the redstone current connected to the cooling coil, any blocks I broke and the redstone itself would disappear as if it were never placed.
![example_of_issue](https://user-images.githubusercontent.com/41883741/43425333-4a6ca884-9420-11e8-93b3-9db9d7b79b08.png)

**Comment by James-Fire** [comment]
I have a similar issue.

Whenever I leave the area my cooling coil is in, it disappears, without fail. Load the game? It's gone. Go exploring then come back? Gone. Go mining, below its location? Come back and it's gone!

It really doesn't like me.
