### ISSUE TITLE
[Suggestion] Purified Water Buckets

### ISSUE THREAD

**Issue by vanwertusername** [Glitchfiend/ToughAsNails#560]
So made my self a PWB just to figure out you can't throw it in a cauldron... What is its use if you can't fill bottles and canteens up using the cauldron and you can't use it while its placed it the world? I'd really like it if it could be placed it cauldrons and used to refill containers. I know on the wiki you can use it when placed in the world for balancing but I'm sure we all know cauldrons are limited.

**Comment by KnightMiner** [comment]
A bit of shameless self promotion, but my mod [Inspirations](https://minecraft.curseforge.com/projects/inspirations) extends cauldron behavior, and one of the features it is filling a cauldron with a purified water bucket to get purified water bottles.
