### ISSUE TITLE
Tough as nails crashes on my LAN world

### ISSUE THREAD

**Issue by LustrousBlue** [Glitchfiend/ToughAsNails#561]
The mod causes the game to crash after a period of being unable to interact with anything, I like the mod and I don't want to have to delete it.

Crash Report:

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present: SSLoadingPlugin (SereneSeasons-1.12.2-1.2.5-universal.jar) ImprovedMobs/ASM (ImprovedMobs-1.2.2[1.12.2].jar) llibrary (llibrary-core-1.0.6-1.12.2.jar)Contact their authors BEFORE contacting forge
// Ouch. That hurt :(
Time: 8/1/18 7:52 PMDescription: There was a severe problem during mod loading that has caused the game to fail
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)Caused by: java.lang.NullPointerException at toughasnails.init.ModConfig.lambda$init$0(ModConfig.java:64) at toughasnails.init.ModConfig$$Lambda$310/991549626.apply(Unknown Source) at toughasnails.init.ModConfig.populateDataMap(ModConfig.java:92) at toughasnails.init.ModConfig.init(ModConfig.java:64) at toughasnails.core.ToughAsNails.init(ToughAsNails.java:83) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 226547040 bytes (216 MB) / 788529152 bytes (752 MB) up to 1073741824 bytes (1024 MB) JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.4.2707 Optifine OptiFine_1.12.2_HD_U_D2 43 mods loaded, 43 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
| State | ID | Version | Source | Signature | |:----- |:-------------------- |:--------------- |:---------------------------------------------- |:---------------------------------------- | | UCHI | minecraft | 1.12.2 | minecraft.jar | None | | UCHI | mcp | 9.42 | minecraft.jar | None | | UCHI | FML | 8.0.99.99 | forge-1.12.2-14.23.4.2707.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHI | forge | 14.23.4.2707 | forge-1.12.2-14.23.4.2707.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHI | adventurepack | 1.5.0 | Adventure-Tools-Mod-1.12.2.jar | None | | UCHI | aquaculture | 1.6.1 | Aquaculture-Mod-1.12.2.jar | None | | UCHI | micsiege | 1.0.2 | Brutal-Zombie-Siege- Mod-1.12.2.jar | None | | UCHI | demonology | 0.01 | Demonology-Mod-1.12.2.jar | None | | UCHI | dldungeonsjdg | 1.9.3 | Doomlike-Dungeons-Mod-1.12.2.jar | None | | UCHI | dynamictrees | 1.12.2-0.7.6 | Dynamic-Trees-Mod-1.12.2.jar | None | | UCHI | endreborn | 0.1.6 | EndReborn+[0.1.6].jar | None | | UCHI | minegems | 1.2.4 | ExtraGems+1.12.2++(v.1.2.4).jar | None | | UCHI | familiarfauna | 1.0.10 | FamiliarFauna-1.12.2-1.0.10.jar | None | | UCHI | gottschcore | 1.4.0 | GottschCore-mc1.12.2-f14.23.4.2705-v1.4.0.jar | None | | UCHI | grue | 1.3.5 | Grue-1.12-1.3.5.jar | None | | UCHI | llibrary | 1.7.14 | llibrary-1.7.14-1.12.2.jar | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec | | UCHI | iceandfire | 1.3.1 | Ice-and-Fire-Mod-1.12.2.jar | None | | UCHI | ichunutil | 7.1.4 | iChun-Util-Mod-1.12.2.jar | None | | UCHI | improvedmobs | 1.2.2[1.12.2] | ImprovedMobs-1.2.2[1.12.2].jar | None | | UCHI | infernalmobs | 1.7.5 | InfernalMobs-1.12.2.jar | None | | UCHI | jei | 4.9.1.168 | jei_1.12.2-4.9.1.168.jar | None | | UCHI | lavadynamics | 1.12.2-4.1.21 | lavadynamics-1.12.2-4.1.21.jar | None | | UCHI | magicarsenal | MC1.12_ver1.2.1 | MagicArsenal-MC1.12_ver1.2.1.jar | None | | UCHI | mimic | 1.5.0 | Mimic-Mod-1.12.2.jar | None | | UCHI | mobamputation | 7.0.0 | Mob-Amputation-Mod-1.12.2.jar | None | | UCHI | monsterswarm | 2.0.1 | MonsterSwarm-2.0.1.jar | None | | UCHI | notenoughroofs | 0.6.1.0 | Not-Enough-Roofs-Mod-1.12.2.jar | None | | UCHI | omlib | 3.0.0-138 | OMLib-1.12.2.jar | None | | UCHI | raiders | 3.0.0 | Raiders-Mod-1.12.2.jar | None | | UCHI | rwg | 1.0.1 | Realistic-World-Generation-Mod-1.12.2.jar | None | | UCHI | ruins | 16.9 | Ruins-Mod-1.12.1.jar | None | | UCHI | sereneseasons | 1.2.5 | SereneSeasons-1.12.2-1.2.5-universal.jar | None | | UCHI | simplecore | 1.6.0.6 | SimpleCore-API-1.12.2.jar | None | | UCHI | simpleores | 1.11.1.9 | simpleores-1.12.2-1.11.1.9.jar | None | | UCHI | structpro | 4.0 | Structpro-1.12.2.jar | None | | UCHI | terra | 1.0 | Terra+1.12.2+-+2.0.jar | None | | UCHI | theeightfabledblades | 1.0.0 | The-Eight-Fabled-Blades-Mod-1.12.2.jar | None | | UCHI | toroquest | 1.12.2-5.2 | ToroQuest-Mod-1.12.2.jar | None | | UCHEE | toughasnails | 3.1.0.127 | ToughAsNails-1.12.2-3.1.0.127-universal.jar | None | | UCH | treasure2 | 0.7.0 | Treasure2-mc1.12.2-f14.23.4.2705-beta0.7.0.jar | None | | UCH | tor | 4.2.16 | Troll-Ores-Reborn-Mod-1.12.2.jar | None | | UCH | waypoints | 1.12-1.2.4 | Waypoints-Mod-1.12.jar | None | | UCH | winterwonderland | 1.2.2 | Winter-WonderLand-Mod-1.12.2.jar | None |
Loaded coremods (and transformers): SSLoadingPlugin (SereneSeasons-1.12.2-1.2.5-universal.jar) sereneseasons.asm.transformer.EntityRendererTransformer sereneseasons.asm.transformer.WorldTransformerImprovedMobs/ASM (ImprovedMobs-1.2.2[1.12.2].jar) com.flemmli97.improvedmobs.asm.ASMTransformerllibrary (llibrary-core-1.0.6-1.12.2.jar) net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 630'

**Comment by krisztian08** [comment]
dont wait for replies,they'll never come.
