### ISSUE TITLE
[Feature Suggestion] Purified Water Config

### ISSUE THREAD

**Issue by UnlimatedStone9** [Glitchfiend/ToughAsNails#563]
A configuration to remove the purifying of water through furnaces would be useful as I would like to implement other means of producing it through crafttweaker and not have the simple water bucket in furnace feature, Thanks        -UnlimatedStone9

**Comment by Forstride** [comment]
Can you not just change this with CraftTweaker too?  Really don't see why we need to add a config option for this.

**Comment by UnlimatedStone9** [comment]
There is no way I can see what the name of the bucket is
