### ISSUE TITLE
Nether problems! Thirst desync

### ISSUE THREAD

**Issue by xhatz** [Glitchfiend/ToughAsNails#568]
Hello!

I have found a bug, I think. When entering in the nether through a portal and while my thirst bar is full, or not, it gets reduced a lot instantly (directly after having crossed the portal). The same happens when crossing the portal from nether to overworld...

I don't know if this is intended, I am using the latest version of the mod, and forge 2757.

Thank you!

**Comment by naqaden** [comment]
I have a hunch this is due to x,z coordinates changing drastically, fooling the thirst system into thinking we've traveled far, which costs a lot of thirst.

**Comment by xhatz** [comment]
Oh... I hope they will fix that... it just basically makes the mod unusable on regular Minecraft :c

**Comment by naqaden** [comment]
Yeah, [here](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/thirst/ThirstHandler.java#L46) is the problem area. It's comparing previous and current coordinates without considering dimension changes or [teleports](https://github.com/Glitchfiend/ToughAsNails/issues/472).

**Comment by Shivaxi** [comment]
was about to report this myself, should be based on time rather than distance.  I mean hunger doesn't have this issue.  It makes riding a Minecart too traveling fast make you lose thirst quickly which makes no sense, very inaccurate way of doing it.

**Comment by naqaden** [comment]
Good point about the minecart. There should be an exception when riding, Otherwise the idea is to drain more thirst when sprinting vs walking vs sneaking vs standing, which I like in theory. Tracking time instead of distance would result in the same thirst drain whether you sprinted all day or stood still.

**Comment by Shivaxi** [comment]
ah very true.  Then yeah why not a combination both?  Make it time based like hunger is with whatever saturation, but then a modifier when sprinting/walking/sneaking that'll increase the drain slightly, only while doing those things.  Kinda like how temperature works when sprinting, giving you a +3 modifier.
