### ISSUE TITLE
Placing purified water into regular water turns it into stone

### ISSUE THREAD

**Issue by bxn0x21** [Glitchfiend/ToughAsNails#570]
Using a purified water bucket to place a purified water block inside a water pool will turn it into stone.

**Comment by Forstride** [comment]
This isn't a bug.  Liquids need to have touching interactions, because if two different liquids are touching without a block forming between them, it can look a bit glitchy

**Comment by bxn0x21** [comment]
It is still weird that stone forms. The purified water could atleast turn
into regular water.
