### ISSUE TITLE
[Suggestion] Add sweating/shivering temperature modifiers

### ISSUE THREAD

**Issue by joeslazaro** [Glitchfiend/ToughAsNails#575]
People do not freeze to death or burn up when the temperature is a few degrees too cold or hot. Our bodies can adapt to some extent.

When you are hot and well-hydrated, then you should get a **sweating** modifier that adds a temperature modifier up to -3 (to offset sprinting) and consume your thirst at an increased rate. This effect could be reduced to -2 and -1 if the player has less than 2/3 and 1/3 of their water bar remaining.

When you are cold and well-fed, then you should get a **shivering** modifier that causes your body to burn more calories to generate heat and consume your hunger at an increased rate. 

These changes would make the game flow more smoothly and not make you stop what you are doing so often to deal with your temperature. It's also more realistic.

**Comment by paulgb434** [comment]
[SchopCraft](https://minecraft.curseforge.com/projects/schopcraft) for 1.12.2 adds features similar to the ones you mentioned. You still freeze to death and burn up like in Tough as Nails on default settings, but this can be easily configured to be more realistic (unlike Tough as Nails, where you can't control Minimum and Maximum temperature).

**Comment by CorneliaXaos** [comment]
I like this..  It would make far more sense for the Hypothermia and Hyperthermia effects to do this instead of causing direct damage.  Direct damage could be a last resort that only happens after prolonged hypo / hyperthermia and your food or thirst bar has been drained.
