### ISSUE TITLE
Purified Water Bottle Wants Uncraftable Potion

### ISSUE THREAD

**Issue by KenyMylankca** [Glitchfiend/ToughAsNails#576]
![asdasd](https://user-images.githubusercontent.com/41585837/45267513-d788af80-b476-11e8-9f56-42c90cb5c7d6.PNG)
used ToughAsNails-1.12.2-3.1.0.129-universal

**Comment by paulgb434** [comment]
JEI is showing the wrong recipe, but it seems to craft properly.
![image](https://user-images.githubusercontent.com/32685848/45990193-f8dbc500-c04c-11e8-91ca-564492129156.png)

**Comment by KenyMylankca** [comment]
oh... should we report it to JEI ?

**Comment by KnightMiner** [comment]
No, JEI just shows the recipe it's told to display. This is a side effect of how potion are stored so technically any potion would work I assume. Should probably switch to an NBT sensitive ingredient
