### ISSUE TITLE
Incompatible with Improvable Skills 3

### ISSUE THREAD

**Issue by SeanChengN** [Glitchfiend/ToughAsNails#583]
The cold/hot screen will cover the skill page.
IMAGE:
1. Normal (Temperature balance)
![2018-10-20_13 18 53](https://user-images.githubusercontent.com/20624068/47251793-7687ca80-d46b-11e8-852c-8cb7965c3939.png)

2. Cold
![2018-10-20_13 13 14](https://user-images.githubusercontent.com/20624068/47251802-a59e3c00-d46b-11e8-8879-0c5703b8b356.png)
Skill page
![2018-10-20_13 13 18](https://user-images.githubusercontent.com/20624068/47251804-a931c300-d46b-11e8-85b1-f756c019e2d0.png)

3. Hot
![2018-10-20_13 20 01](https://user-images.githubusercontent.com/20624068/47251810-c5cdfb00-d46b-11e8-8656-6264f9cbd0c7.png)
Skill page
![2018-10-20_13 20 03](https://user-images.githubusercontent.com/20624068/47251812-cb2b4580-d46b-11e8-9ff3-69c620909288.png)

Could u fix this?

Forge: 1.12.2-forge1.12.2-14.23.5.2768
ToughAsNails: 3.1.0.129
Improvable Skills: 3.5.5r https://minecraft.curseforge.com/projects/improvable-skills/files

**Comment by Forstride** [comment]
This is *not* the vignette that we use for temperatures.  Either some other mod is interfering with how it renders, or Improvable Skills isn't rendering their GUI properly.

**Comment by SeanChengN** [comment]
> This is _not_ the vignette that we use for temperatures. Either some other mod is interfering with how it renders, or Improvable Skills isn't rendering their GUI properly.

Oh, I know, May be a problem with EnhancedVisuals. Anyway, thanks!
