### ISSUE TITLE
Cooling coil keeps disappearing.

### ISSUE THREAD

**Issue by James-Fire** [Glitchfiend/ToughAsNails#584]
Whenever I leave the area my cooling coil is in, it disappears, without fail. Load the game? It's gone. Go exploring then come back? Gone. Go mining, below its location? Come back and it's gone!

It even extends to those coils in chests. I have not checked for certain if it affects those in my inventory, but I think it does.

What's going on here?

**Comment by James-Fire** [comment]
Yeah,.. the issue seems to extend to the game just not saving anything after a cooling coil is put into it.

**Comment by SwordShaman** [comment]
Same issue here.  Upon placing a cooling coil, the world doesn't save any changes made thereafter.
