### ISSUE TITLE
Crash loading a modpack.

### ISSUE THREAD

**Issue by BomberCost** [Glitchfiend/ToughAsNails#588]
Hi. I write for a crash while loading a modpack. I'm developing the "King Mammoth" for 1.12.2. From august to today, I had no problems with the mod. But now it give me this crash. Tell me if u can help or update the mod fixing the issue. Thanks.
[crash-2018-11-20_23.21.25-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/2601847/crash-2018-11-20_23.21.25-client.txt)

**Comment by Forstride** [comment]
That seems to be a crash that just randomly happens sometimes.  I'm not entirely sure what causes it, but we've had multiple reports in the past, and they all seem to be fixed the next time you load the game.

We'll be looking into it when we update to 1.13 though.
