### ISSUE TITLE
No canteen recipe

### ISSUE THREAD

**Issue by Sorrieah** [Glitchfiend/ToughAsNails#591]
There's no recipe to create an empty canteen anymore. The item appears in JEI as "Canteen" rather than "Empty Canteen" (from my last functional mod setup) and when viewed only shows enchantment recipes. No crafting recipe shown by JEI and attempting to craft with leather gives no results.

Tested both in a full modded setup and without any other mods.

Versions: Forge-14.23.5.2768, ToughAsNails-1.12.2-3.1.0.132
Last seen working: Forge-14.23.4.2739, ToughAsNails-1.12.2-3.1.0.115

**Comment by Forstride** [comment]
Oops.  Fixed.

Also, I just renamed the "Empty Canteen" to "Canteen," so don't worry about that

**Comment by FellowEsin** [comment]
This problem is back in 1.21.1 Fabric
