### ISSUE TITLE
Crash when loading Minecraft with TAN, Apple Juice Skin & Food Funk

### ISSUE THREAD

**Issue by Dalorbi** [Glitchfiend/ToughAsNails#592]
TAN Version[s]: 1.12.2-3.1.0.132, 1.12.2-3.1.0.133, 1.12.2-3.1.0.135
Apple Juice Skin Version: 1.12.2-1.0.0.4
Food Funk: 1.12.2-4.9.5
WumpleUtil: 1.12.2-2.12.6

Note: Configs are unedited
Issue: Before Minecraft can completely load it crashes

Crash Log: https://pastebin.com/Cb48A0mn
Latest Log: https://pastebin.com/ZEreaKUM

**Comment by ghost** [comment]
Hello, I'm the author of Apple Juice Skin. Unfortunately, this is an issue on my end, but you can (hopefully) expect it to be fixed in the next release.
