### ISSUE TITLE
Climatisation when outside

### ISSUE THREAD

**Issue by nick-johnson** [Glitchfiend/ToughAsNails#593]
The climatisation effect from the heating coils seems to extend outside of buildings (even in open sky) and persists until you are far away from the heat source.

![image](https://user-images.githubusercontent.com/1663959/48982938-ce42d280-f0b6-11e8-8050-d2b65561790c.png)

Heating coil is on in the brick building in the picture, but climatisation persists well outside of the building/chunk.

**Comment by jvaldelamar7** [comment]
I’m not a contributor, but if I can ask what mod are you using that gives you all that information?

**Comment by nick-johnson** [comment]
It's a command that's included with TaN.

"/tan tempinfo" will show/hide the information
