### ISSUE TITLE
Cannot drink directly from a water block.

### ISSUE THREAD

**Issue by CrypticBacon** [Glitchfiend/ToughAsNails#594]
I am not able to drink directly from a water source. I have tried crouching + right clicking but I cannot drink.

**Comment by Forstride** [comment]
There's a certain distance you have to be from it, and it's not very lenient.  Make sure you're right next to the block you're trying to drink from

**Comment by enbyminer** [comment]
I am also having this problem, and I have tried drinking from next to, far away from, on top of, and standing in a water source.  I am using other mods with it, so there might be some conflict there, but I can't for the life of me figure out what might be causing it.  

Edit: Problem fixed.  I had an old version that didn't have this yet.  *facepalm*
