### ISSUE TITLE
Internal server error after adding armor to config + serene seasons client crash

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [Glitchfiend/ToughAsNails#597]
[tan internal server error armor modifiers.txt](https://github.com/Glitchfiend/ToughAsNails/files/2635218/tan.internal.server.error.armor.modifiers.txt)
[serene_seasons_crash.log](https://github.com/Glitchfiend/ToughAsNails/files/2635220/serene_seasons_crash.log)
[internal server error tan modifiers.txt](https://github.com/Glitchfiend/ToughAsNails/files/2635225/internal.server.error.tan.modifiers.txt)

**Comment by Forstride** [comment]
For your Serene Seasons crash, you need to update Dynamic Surroundings.  As for the armor modifier crash, I'm not entirely sure what's causing it.  TAN is kind of a mess right now, and we likely won't be fixing anything until 1.13
