### ISSUE TITLE
Lack of Wiki info

### ISSUE THREAD

**Issue by JWTHDYTWA** [Glitchfiend/ToughAsNails#598]
Please add wiki page that will contain information about configuration (especially block temp). Like how to specify block's meta ID and some other capabilities to configure, maybe NBT.

**Comment by serialtasted** [comment]
Have you found out how to add blocks with their meta id?
I've tried this:
```
{
    "state": {
      "block": "primal:hibachi",
      "properties": {
		"meta": 9
	  }
    },
    "temperature": 3.0
  }
```

And also tried adding in front of the block name but it crashes my game

**Comment by ilvrak** [comment]
I just discovered that the properties of the blocks can be viewed in F3 debug info, in right side.
but unfortunately they do not always work correctly in TAN config.
e.g. my
`{"state": {"block": "tconstruct:smeltery_controller", "properties": {"active": "true"}}, "temperature": 3.0},`
not working

**Comment by ilvrak** [comment]
e.g. my
`{"state": {"block": "tconstruct:smeltery_controller", "properties": {"active": "true"}}, "temperature": 3.0},`
not working
