### ISSUE TITLE
Black bar behind thirst?

### ISSUE THREAD

**Issue by ivygod1** [Glitchfiend/ToughAsNails#606]
A black bar keeps appearing behind my thirst. It wasn’t there before and hadn’t appeared until recently. Any fix?

**Comment by ivygod1** [comment]
Note: the black bar goes away when I put something in my offhand but returns when i move it

**Comment by CREEATION** [comment]
This happens to me while being in a boat.

**Comment by gnomed-by-steve** [comment]
It's just optifine bein a snarky betch

**Comment by CREEATION** [comment]
> It's just optifine bein a snarky betch

I don't use OptiFine.
