### ISSUE TITLE
Temperature GUI uses whatever the previous openGL draw color was

### ISSUE THREAD

**Issue by Laike-Endaril** [Glitchfiend/ToughAsNails#607]
The draw color is not set before drawing the temperature bulb.  This sometimes causes it to be drawn in other colors if another mod is changing the draw color.

Posting due to [an issue someone posted on my own project](https://github.com/Laike-Endaril/Dynamic-Stealth/issues/4), which is caused by this issue.

**Comment by Laike-Endaril** [comment]
In TemperatureOverlayHandler, changing this:

```java
if (minecraft.playerController.gameIsSurvivalOrAdventure())
{
    drawTemperature(width, height, temperature);
}
```

...to this:

```java
if (minecraft.playerController.gameIsSurvivalOrAdventure())
{
    GL11.glColor4f(1, 1, 1, 1);
    drawTemperature(width, height, temperature);
}
```

...would fix the issue.

**Comment by CREEATION** [comment]
You should open a pull request instead.
