### ISSUE TITLE
[Suggestion] Reusable Campfire

### ISSUE THREAD

**Issue by nick-johnson** [Glitchfiend/ToughAsNails#608]
Current behavior:
Campfire burns out and must be destroyed. Campfires are single use.

Suggested behavior:
Campfire burns out and logs are removed from the model, stones stay
Can add new logs to the campfire and relight
Could add new logs to the campfire while it is burning to extend time up to a maximum number of logs (4 based on the current model), and the number of logs remaining in the fire is a good visual indicator of the remaining duration of the fire

**Comment by Forstride** [comment]
This has already been added.  The logs burn individually now, and can be replaced by right clicking on the campfire with a log.

**Comment by nick-johnson** [comment]
Ah! My apologies! The wiki should probably be updated then. :) Thanks!
