### ISSUE TITLE
Issues related to drinks with NBT values

### ISSUE THREAD

**Issue by Luke616** [Glitchfiend/ToughAsNails#609]
Hey team! I've noticed two issues related to drinks with NBT values that are present in version 3.1.0.139 for 1.12.2
-  Vanilla potions now apply the thirst debuff just like bottles of (unpurified) water.
-  Drinks added to the drink_stats.json which have NBT data will not work unless their NBT data is specified. [This post](https://github.com/Glitchfiend/ToughAsNails/issues/517#issuecomment-448011498) implies that it should be optional, and leaving out the NBT parameter should provide stats for any item with that ID. This bug makes it so that for items like rustic elixirs, every possible elixir NBT value must be specified in order to give them custom thirst values. For example, the code below will not provide thirst for any of the rustic drinks since NBT is unspecified.
``` 
{
    "item": {
      "name": "rustic:fluid_bottle",
      "metadata": 0
    },
    "thirst": 8,
    "hydration": 0.7,
    "poisonChance": 0.0
  },
  {
    "item": {
      "name": "rustic:elixir",
      "metadata": 0
    },
    "thirst": 6,
    "hydration": 0.7,
    "poisonChance": 0.0
  }
```
I suspect these issues may be related, as the both have to do with the system having trouble distinguishing between drinks with and without NBT data.

Testing was done with the following versions:
Minecraft 1.12.2
TAN 3.1.0.139
Forge 14.23.5.2796

Thanks!

**Comment by Sunconure11** [comment]
This issue, while being related to another mod, is connected as well, due to said mod applying NBT Data to stuff in order to make it rot.

https://github.com/Glitchfiend/ToughAsNails/issues/616

**Comment by Xorbah** [comment]
So does this have a workaround? I am attempting to resolve the issue on my end as well.

**Comment by Luke616** [comment]
My workaround has been to use version 3.1.0.129 which I believe is the latest that doesn't have the second of these issues. The first issue is still present unfortunately. Not sure what any of the later updates have added anyway, as there aren't any detailed changelogs on curse.
