### ISSUE TITLE
The game crashed whilst unexpected error

### ISSUE THREAD

**Issue by geryyyyyyyyyyy** [Glitchfiend/ToughAsNails#612]
https://pastebin.com/XFks3ra4

My problem is getting start a minecraft and i wanna join in the but it is writes Internal server closed after that crashing a minecraft. It is writes me: The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: toughasnails/api/season/SeasonHelper
 Can you help me?

**Comment by Forstride** [comment]
Your mods are insanely outdated
