### ISSUE TITLE
[1.10] [Death Message Change Suggestion]  When die from Thirst/Cold/Heat

### ISSUE THREAD

**Issue by Morpheus1101** [Glitchfiend/ToughAsNails#62]
When you die from thirst, the death message sais you starved to death, which you didnt, if anything it could say you "Died of Thirst" and if from to cold, possibly something like "Died of Hypothermia"  ... heat "Died of Heat Exhaustion"

**Comment by Forstride** [comment]
Already marked as an issue here: https://github.com/Glitchfiend/ToughAsNails/issues/46
