### ISSUE TITLE
Game crashed on load (config problems?)

### ISSUE THREAD

**Issue by politespectre** [Glitchfiend/ToughAsNails#627]
[crash-2019-03-14_20.54.50-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/2965816/crash-2019-03-14_20.54.50-client.txt)

Crashed when starting the game, fixed after deleting configs for TAN

**Comment by politespectre** [comment]
Fixed after deleting configs for TAN

**Comment by Jackiecrazy** [comment]
Seconded. Please make the crashes more descriptive as to what is wrong, because I'm sure I did literally everything correctly and it still wouldn't launch for whatever unholy reason ಠ_ಠ

**Comment by zack-emmert** [comment]
I'm gonna go ahead and third this. The lack of descriptive errors makes it a complete nightmare when attempting to integrate the truly immense number of Pam's Harvestcraft drinks into TaN.
