### ISSUE TITLE
Coal Ore/Block Of Coal ignite when lit on fire

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/ToughAsNails#63]
If one of those those blocks get lit on fire, their burning time will be similair when being used as fuel inside a furnace.

Burning coal wil produce Sulfur dioxide (SO2) in the proccess

**Comment by Forstride** [comment]
I don't want to mess with the properties of blocks like that.  Also, we're not adding a bunch of different gases.  Just the ones listed here (Minus Afterdamp): https://en.wikipedia.org/wiki/Damp_(mining)
