### ISSUE TITLE
Issue with Farming Valley

### ISSUE THREAD

**Issue by dmtryzhkv** [Glitchfiend/ToughAsNails#631]
Hello guys. I've been sent over from atlauncher discord to here. problem seems like caused by this mod so here is the crash log. https://pastebin.com/wxiDjJ1r

thank you for your help.

**Comment by Forstride** [comment]
This is on 1.10.2, and we do not support older versions of Minecraft

**Comment by dmtryzhkv** [comment]
lovely. thank you for the response.
