### ISSUE TITLE
Can't Get Warm

### ISSUE THREAD

**Issue by KenyMylankca** [Glitchfiend/ToughAsNails#632]
it looks like campfire does nothin, becus i could get warm near the lava blocks.
![aaa](https://user-images.githubusercontent.com/41585837/56881960-c4107000-6a6a-11e9-9a5a-39e6b9c16875.png)
Using TAN 3.1.0.140 with Forge 2836. (1.12.2)
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/3126320/latest.log)
https://drive.google.com/open?id=1Ib8vPwoBqcOMdLN7kdB1UpROKW-U12R8

**Comment by KenyMylankca** [comment]
btw the biome is Ice Mountains, i think that causes a bit xD

**Comment by ilvrak** [comment]
use `/tan tempinfo` and see temperature.
campfire only add +5, and this dont stacks, it's no use to place multiple heat sources
lava block add +15

**Comment by KenyMylankca** [comment]
LOL, why the hell it doesn't stack? what's the point? more fire=more heatness, so?...
