### ISSUE TITLE
Can't Fill Canteen From/With Purified Water Block?

### ISSUE THREAD

**Issue by KenyMylankca** [Glitchfiend/ToughAsNails#635]
is it supposed to be like this? i can fill canteen with normal water but purified water block... please fix this :C

**Comment by IceT2** [comment]
Just tried the latest 'ToughAsNails-1.12.2-3.1.0.141-universal' version. I'm still unable to do this, but I'd like to of possible please. At the moment, I am unable to find a use for putting purified water into the world. I am unable to fill a canteen from a purified water source block, If I fill a glass bottle, I just get a water bottle from it (not purified). If I put purified water into a tank (i.e. Thermal Expansion portable tank), I am unable to fill any bottles, only a bucket, which is how I got it into the tank in the first place. Makes it difficult to find a use for it.

**Comment by KnightMiner** [comment]
Shameless plug: if you install my mod [Inspirations](https://minecraft.curseforge.com/projects/inspirations), it extends the cauldron allowing you to place liquids such as purified water in there. You can then fill bottles from it.

**Comment by IceT2** [comment]
Appreciated KnightMiner - I tried your Inspirations mod and it does indeed allow you to fill a bottle from a cauldron if there's purified water in it, and you do get a purified water bottle (also works with the T.A.N. canteen). I was hoping not to add any more mods, but for the time being, it at least gives me a small use for purified water in the world, so 'Shameless plug' for the win !

**Comment by KenyMylankca** [comment]
i can put anything to anywhere, i don't have problems like that. but all i want is filling the canteen from the purified water fluid block.
