### ISSUE TITLE
[Bug] Custom armor temperature doesn't work

### ISSUE THREAD

**Issue by JWTHDYTWA** [Glitchfiend/ToughAsNails#637]
Adding custon entries to `armor_temp_modifiers.json` is not working if that armor has default internal data, such as enchantments (like Yeti armor from TwilightForest). Or ANY armor crafted by player with Iblis mod, which dynamically defines items stats based on player's crafting skills.

How to reproduce? Try TwilightForest and Iblis.

**Comment by ilvrak** [comment]
it seems to any enchanted armors cancel it heat property.
e.g. i set leather armor to +1. but enchanted leather armor add nothing.
colored variant - nothing too.
write NBTs in tan config - not working
