### ISSUE TITLE
mod crashes dedicated server

### ISSUE THREAD

**Issue by HuseyunReis** [Glitchfiend/ToughAsNails#639]
i installed TAN and Serene Seasons on a dedicated server, and it always crashes.
i tried:
changing the forge version,
changing the TAN's version,
nothing changed.
crash report: https://pastebin.com/5buGR0Y8

**Comment by Forstride** [comment]
You're using an incredibly old version of Tough As Nails.  You're going to have to update to Minecraft 1.12.2, as we don't support regular 1.12

**Comment by HuseyunReis** [comment]
i also tried the most new version and the same error occured. Sorry i didn't mention about it.

**Comment by HuseyunReis** [comment]
https://pastebin.com/WLj1PWZz
crashes even in the latest version of forge and TAN.

**Comment by Forstride** [comment]
Have you tried just making a new world?

**Comment by HuseyunReis** [comment]
i reinstalled hundreds of times, trying new worlds and new versions but it didn't work.

**Comment by HuseyunReis** [comment]
it crashes before it creates a new world file.

**Comment by HuseyunReis** [comment]
i dont know if this information would help or not, but i play in turkish language, and maybe 'ı' letter* is what's causing the problem

**Comment by Forstride** [comment]
Oh, yeah, I see the weird "i" letter that it's trying to set the property as.  I'm not really sure if there's anything we can do to fix that on our end though, as it seems to be something more at the operating system level.

**Comment by HuseyunReis** [comment]
well, it seems like me and my friend are going to play vanilla. its weird that it works on my client but crashes on server. anyways, thanks man.

**Comment by HuseyunReis** [comment]
it was because of my language. i researched a bit more and found out that this mod was fixing the turkish language problem: https://minecraft.curseforge.com/projects/localefixer
problem is fixed. i appreciate for your help.
