### ISSUE TITLE
Tinkers'

### ISSUE THREAD

**Issue by Draemonaurious** [Glitchfiend/ToughAsNails#643]
I am liking this mod very much. It is difficult to keep warm and the nether seems overly hot but those are not issues. What I want to suggest is to make a recipe for a lining that can be added to Tinkers' armory and to Tinkers' Compendium armor sets. This would make TAN alot more useful in keeping warm/cool while still wearing epic Tinker armor or even regular armor. I haven't seen anyone suggest this but I'm sure someone has and I would like this very much. Thank you for this mod.

**Comment by tgstyle** [comment]
https://minecraft.curseforge.com/projects/tinkersurvival
