### ISSUE TITLE
Purified water bucket is totally useless

### ISSUE THREAD

**Issue by varappdev** [Glitchfiend/ToughAsNails#644]
It is not drinkable, it does support the mB system but you can't drink it, you can't transfer purified water from a container to a glass bottle. And if you put the liquid down and right click with a glass bottle it gives you normal water bottle. Why you added it if its totally useless?

**Comment by CIosure** [comment]
I totally agree and this should be fixed asap, I'm using traveller's backpack and this is a real issue, I converted a lot of water to purified only to realize that it's useless, please fix.

**Comment by varappdev** [comment]
I use traveller's backpack too.
[Insert surprised Pikachu here]

**Comment by CIosure** [comment]
**TEMPORARY FIX:**
https://www.curseforge.com/minecraft/mc-mods/inspirations

This mod lets you put buckets of purified water into cauldrons, then use bottles on the cauldrons to get purified water bottles!
