### ISSUE TITLE
AppleSkin and Quark Compatability

### ISSUE THREAD

**Issue by IdrisQe** [Glitchfiend/ToughAsNails#646]
There used to be a mod that did this, called AppleJuiceSkin, but it's disappeared from the internet for unknown reasons. AppleSkin shows saturation and exhaustion levels for food as well as an overlay that shows how much food/saturation a held item would restore, and shows tooltips indicating the same under an item's name in the inventory. Having all of these available for thirst would be great.

Quark adds a stripped-down version of this too, just showing the amount of food an item would restore in its tooltip. Again, no thirst support natively.

It's been suggested that it would be far easier for TAN to implement on your end, so consideration of such would be appreciated.
squeek502/AppleSkin/issues/45

**Comment by Forstride** [comment]
We're not adding this on our end.  If someone wants to make a compatibility mod, they're more than welcome, but adding it on our end would essentially be adding on an entirely new mod, and that's just not gonna happen.
