### ISSUE TITLE
Altered Day-Length Support

### ISSUE THREAD

**Issue by Exsolutus** [Glitchfiend/ToughAsNails#647]
While SereneSeasons has support for mods which change the length of the in-game day, ToughAsNails does not. This results in strange temperature behaviors when TAN thinks it is late night or noon when in fact it is not.

A simple day-length-in-ticks style config option similar to SereneSeasons would resolve this issue.

**Comment by SwordShaman** [comment]
I'd also love for the ability to have a config option to match my day length!   I'm currently using OpticManager with a longer day/night cycle, and an option to match the day length in TAN would resolve the last issue I've got with my current build.  Thanks for the great mod!
