### ISSUE TITLE
Glass bottles cannot collect Dragon's Breath, canteens return dirty water bottles when used on cauldrons

### ISSUE THREAD

**Issue by Explodncheez** [Glitchfiend/ToughAsNails#65]
As of version 1.0.4, right clicking with a canteen on a filled cauldron turns it into a (dirty) water bottle.

**Comment by Forstride** [comment]
Can confirm.  Thanks for the report

**Comment by Explodncheez** [comment]
The same thing appears to happen when trying to collect Enderdragon Breath with a glass bottle - you get Dirty Water instead.

**Comment by erindal** [comment]
Okay that's a more major bug I think...

**Comment by snurre0** [comment]
Buckets filled from cauldrons also turn into bottles(only tested in nether though).

**Comment by 5igm** [comment]
Is there any cauldron server in 1.8/1.9/1.10?

**Comment by erindal** [comment]
@5igm I think in the wrong place.

**Comment by DoughnutDev** [comment]
This still be fixed?
