### ISSUE TITLE
Using a Flint and Steel to lit a Campfire

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/ToughAsNails#66]
Using a Flint and steel to lit a Campfire will 100% guarantee fire.
This is another way to lit your campfires for those who prefer to do so.

**Comment by pastellexists** [comment]
Good idea, but set this with a label of enhancement.

**Comment by Quizer9O8** [comment]
May I ask why this suggestion is closed?
I was quite suprised you even couldnt lit those campfires with a Flint and Steel if you had one.
This would mean you didnt have to carry stacks of sticks all the time if you got a Flint and Steel instead.

**Comment by Forstride** [comment]
Because I added it?  Check the commits.  It's literally the latest one there

**Comment by Quizer9O8** [comment]
Oh my bad, I didn't see it in there ;p
