### ISSUE TITLE
Fabric Support 1.16.x

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Glitchfiend/ToughAsNails#661]
## Feature Request

I and a ton of other fabric users would love to see this mod have a Fabric Port. Even if it'll take a while, I would wait.</br>

### What feature are you suggesting?

Basically it's just support for Fabric (Mod Loader). I know it's a huge leap from the forge and would require hours on end of learning but Fabric needs this mod. The only other mod (That wasn't shut down by you guys) is EnvironmentZ. Which I personally don't find fun or worth using. </br>

### Why should it be added?

Because there are no other Mods like this on Fabric 1.16.x except for EnvironmentZ. This mod is the best one of its kind and is needed on fabric. (It's the only way I can play it with my other mods due to Performance</br>

**Comment by Forstride** [comment]
No

**Comment by ZaneDragonBorn** [comment]
Why don't you guys want to port? _If you don't mind me asking_

**Comment by Forstride** [comment]
1) We don't have the time to do so.  We are literally two people working on 3 mods in our spare time.  This would essentially add another 3 mods to that that we'd have to maintain and update.

2) We don't have the desire to do so.  Fabric does not interest us *at all*, and is barely even a blip on the radar compared to how many people use Forge/Forge mods.

**Comment by pjlasl** [comment]
There was someone trying to port to Fabric. It was called Tough as Nails Reborn, but the project is no longer available on Curseforge. It's a shame...

**Comment by ZaneDragonBorn** [comment]
> There was someone trying to port to Fabric. It was called Tough as Nails Reborn, but the project is no longer available on Curseforge. It's a shame...

Yeah it was shutdown by the fans and devs of TAN because it used there code. Sadly these guys didn't even bother to offer him into the team so Fabric gets loved

**Comment by Forstride** [comment]
Yes, we're going to welcome someone into our team who broke our license and ported TAN without our permission, and then got mad when I told him to remove it, and proceeded to slander me over Twitter and get his friends to harass me.

**Comment by ZaneDragonBorn** [comment]
Never heard that😐. The guy sent people to harass you?
