### ISSUE TITLE
[1.16.5] Crash on startup when attempting to use the mod on a dedicated server

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Glitchfiend/ToughAsNails#662]
## Bug Report

When attempting to use this mod on a dedicated server, the server just crashes on startup. (I know that this is just an alpha and I probably shouldn't be using this yet, but I thought it would be useful to report this nontheless.)

### How can the crash be reproduced?

Launch a dedicated forge server (36.0.15) with this mod installed on it.

### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/5940010/latest.log)
[crash-2021-02-07_21.10.28-fml.txt](https://github.com/Glitchfiend/ToughAsNails/files/5940015/crash-2021-02-07_21.10.28-fml.txt)

### Mod Version
Tough As Nails: 4.0.1.13
Forge: 36.0.15
Minecraft: 1.16.5

**Comment by Adubbz** [comment]
This should be fixed in the latest build which will be up shortly.

**Comment by The-Bernician-Lamb** [comment]
Can confirm it is fixed. Thanks for your help!
