### ISSUE TITLE
Game crashes when trying to put anything in the bottom left slot of a water purifier

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Glitchfiend/ToughAsNails#667]
## Bug Report

When testing the new water purifier I found that when I attempt to place anything on the bottom left slot of the block's gui the game crashes shortly after.

### How can the crash be reproduced?

1. Load a world with Forge 36.0.22 and Tough as Nails 4.0.1.21
2. Place down a water purifier
3. Get an item (e.g. water bottle, coal, etc.) and try to place it in the bottom left slot of the water purifier's gui.
4. Game Crashes

### Crash Report and Logs
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/5975526/latest.log)
[crash-2021-02-13_10.55.11-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/5975527/crash-2021-02-13_10.55.11-client.txt)

### Mod Version
Tough as Nails: 4.0.1.21
Forge: 36.0.22
Minecraft: 1.16.5

**Comment by Adubbz** [comment]
Fixed, a build should be up shortly.

**Comment by Adubbz** [comment]
I should also add, the correct item to use in the bottom slot is charcoal.

**Comment by The-Bernician-Lamb** [comment]
> Fixed, a build should be up shortly.

I'm impressed, it hasn't even been 10 minutes since I reported this! Thanks for the quick fix!

> I should also add, the correct item to use in the bottom slot is charcoal.

Thanks for the tip! May I suggest having an outline of a piece of charcoal in that slot in the future, so players can get an idea of what goes in that slot? (Similar to how the smithing table has an outline of a netherite ingot.)

**Comment by Adubbz** [comment]
That is a possibility, although I’m also potentially thinking that other filter items may be added in the future with longer durations (and charcoal may be nerfed a bit since I think it’s probably a bit too long right now). Will have to think on it.

**Comment by Forstride** [comment]
> May I suggest having an outline of a piece of charcoal in that slot in the future, so players can get an idea of what goes in that slot? (Similar to how the smithing table has an outline of a netherite ingot.)

I was going to do this, but the outline isn't really distinguishable seeing as it's kind of a generic blob-y shape, plus as Adubbz said we may add additional filter items in the future (Like a higher quality filter crafted with paper and sand or something).  Not to mention the potential to allow items from other mods to work with it.

**Comment by The-Bernician-Lamb** [comment]
> > May I suggest having an outline of a piece of charcoal in that slot in the future, so players can get an idea of what goes in that slot? (Similar to how the smithing table has an outline of a netherite ingot.)
> 
> I was going to do this, but the outline isn't really distinguishable seeing as it's kind of a generic blob-y shape, plus as Adubbz said we may add additional filter items in the future (Like a higher quality filter crafted with paper and sand or something). Not to mention the potential to allow items from other mods to work with it.

I see. Thank you for the explanation! I am very much looking forward to seeing what gets added in the future. Especially 1.17 and beyond!
