### ISSUE TITLE
Infinite Thirst (1.16.5)

### ISSUE THREAD

**Issue by ActurusOfc** [Glitchfiend/ToughAsNails#668]
## Bug Report
Infinite Thirst Effect

### What's the issue you encountered?
When you drink normal water and get thirsty, it doesn't come out anymore

### How can the issue be reproduced?
Take a bottle of water (not purified) and drink it until you have the thirst effect, and then wait for the thirst effect to reach 0:00

### Logs
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/5976204/latest.log)

### Mod Version
Tough As Nails 1.16.5-4.0.1.22

### Video Example
https://youtu.be/JU8Qzfy5A5g

**Comment by Adubbz** [comment]
I can't seem to reproduce this. Does this also happen for you with TAN on its own?

**Comment by Adubbz** [comment]
Managed to get it to happen on peaceful mode. Should be fixed now with a new build up shortly.
