### ISSUE TITLE
Thirst won't decrease

### ISSUE THREAD

**Issue by LegacyQuest** [Glitchfiend/ToughAsNails#669]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ The issue is my thirst is not decreasing at all, i've messed with the configs and everything deleted them and reinstalled but im still having the same issue. ]</br>

### How can the issue be reproduced?

[ play minecraft. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ 1.16.5 ]</br>

**Comment by Adubbz** [comment]
It does go down, however it’s very slow in old versions (which I’m assuming you’re using, because you haven’t given the mod version, only the Minecraft version). Please update the mod and regen your configs.

**Comment by LegacyQuest** [comment]
> It does go down, however it’s very slow in old versions (which I’m assuming you’re using, because you haven’t given the mod version, only the Minecraft version). Please update the mod and regen your configs.

its the newest version added 5 days ago Tough as Nails 1.16.5 -4.0.1.23- universal.jar

**Comment by Adubbz** [comment]
The only other reason it wouldn’t go down would be if you’re in peaceful mode. Alternatively, you may have created your current world with an old version of the mod and thus still have a heavily inflated initial hydration level. The initial hydration level will only be changed in new worlds. It’ll still decline in your current one, but it’ll take some effort to get it to do so.
