### ISSUE TITLE
Happy to see ya'll back!

### ISSUE THREAD

**Issue by UraniumGears** [Glitchfiend/ToughAsNails#670]
## Feature Request

[ I'm really glad to see that you guys revived this awesome mod! I hope ya'll are successful in developing this mod to its fullest potential
as well as attaining whatever you guys wanted from this mod! ]</br>

### What feature are you suggesting?

[ Provide an overview of the feature being suggested. ]</br>

### Why should it be added?

[ Describe the benefits of implementing this feature. ]</br>

**Comment by Forstride** [comment]
I appreciate the enthusiasm, but please don't use issues for something like this in the future.  We have a Discord server for discussions that's linked on the CurseForge page.
