### ISSUE TITLE
Drinking potion can cause thirst

### ISSUE THREAD

**Issue by sharlin073** [Glitchfiend/ToughAsNails#671]
## Bug Report

[  ]</br>

### What's the issue you encountered?
[ Drinking potions can cause thrist ]</br>

### How can the issue be reproduced?
[ drink potions until you get thirst effect. It won't take long ]</br>

### Logs
[ You probably don't need this ]</br>

### Mod Version
[ The latest (posted on Feb 22) ]</br>

This probably happens because the config option only has "minecraft:potion" and does not distinguish if it is just water or potion. Of course, potions are not made of purified water so it is not 100% unreasonable, but I guess people won't make potions just to solve thirst. I can lower poison chance, but then there will be no point in purifying water.

I think this might be an intended behavior but reporting for just in case.
If this is intended, please close this issue.

Thank you for continuing this wonderful mod again! (There is one attempt to replace TAN, but currently, it is very buggy)

**Comment by Forstride** [comment]
It's half intentional, but people would only drink potions to restore thirst if they didn't have a downside.  And ultimately we want people to use canteens for thirst over water bottles.  They just have support because it'd be weird not to.
