### ISSUE TITLE
Can't drink with hand

### ISSUE THREAD

**Issue by sharlin073** [Glitchfiend/ToughAsNails#673]
## Bug Report

[]</br>

### What's the issue you encountered?

[ Right clicked on the water source block, nothing happens ]</br>

### How can the issue be reproduced?

[ I just opened minecraft with appleskin, jei, TAN loaded, and tried to drink from the water source block ]</br>

### Logs

[ Here's the log: https://gist.github.com/sharlin073/7c98cdd85aabc9159ef8cac08b671a3c ]</br>

### Mod Version
[ Latest, with forge 36.0.22 ]</br>

**Comment by Forstride** [comment]
It has to be enabled in the world config

**Comment by sharlin073** [comment]
I believe I enabled it in the world config, and moved it to default config folder, and then made a world again, but it seems like it does not work...well, I'll try again

**Comment by Forstride** [comment]
You aren't supposed to move anything.  The config in the world folder needs to stay there, because that's how server-side configs work.

**Comment by sharlin073** [comment]
I mean, the config file is still there. But if I move(I mean copy) it to the default config folder and start a new world, it will automatically apply to a new world if I'm understanding it correctly. So, the config file there still shows:
[toggles]
	#Enable or disable thirst.
	enable_thirst = true
	#Enable or disable hand drinking.
	enable_hand_drinking = true
However, it does not work and I'm not sure why... that's why I added the whole log

There's nothing wrong with the location of the file.
