### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by kubistonek** [Glitchfiend/ToughAsNails#674]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?
1. Drinking purified water does not restore any thirst
2. Thirst bar seems to have black background (rather than transparent) from time to time. not using texturepacks/shaders. 1 mod affecting visuals is "damage tint" basically adds red vingette when hit, but I dont thnik that its the cause
3. * you have [insert banner here] graphic on curseforge page (right in the middle)

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?
-1. drinking purified water
2. if not happening without mod, use mod like enchanced visuals/damage tint, and get hit untill you have about 2 hearts left

[ Include a detailed step by step process for recreating your issue with only Tough As Nails installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[1.16.5-4.0.1.23 ]</br>

**Comment by Adubbz** [comment]
I'm going to close this, since I don't think either of these bugs apply to current mod versions
