### ISSUE TITLE
Freezing when entering nether loading screen

### ISSUE THREAD

**Issue by kubistonek** [Glitchfiend/ToughAsNails#675]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

Enter nether and look at loading screen (might be too faster  on better pc but on mine it's about 5s), freezing overlay is showing 

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Forstride** [comment]
>freezing overlay

You are using an old version, as temperature has not been re-added in 1.16.4/5, and we do not support versions older than that, as it says when opening a new issue.
