### ISSUE TITLE
Thirst Creative Bug

### ISSUE THREAD

**Issue by TheBlessedKettle** [Glitchfiend/ToughAsNails#679]
### What's the issue you encountered?

When I am in creative, I am still required to drink water. I found this out after finding that my sprint key would not work. I switched it multiple times, to no avail. I then went into survival, finding that my water meter was at 3 bars.

### How can the issue be reproduced?

Play in creative for extended amount of time with Tough As Nails enabled.

### Mod Version
ToughAsNails-1.16.5-4.0.1.10-universal

**Comment by VDeltaGabriel** [comment]
I have this also, and this is even on ToughAsNails-1.16.4-4.0.0.9-universal

**Comment by SweepSwap** [comment]
> I have this also, and this is even on ToughAsNails-1.16.4-4.0.0.9-universal

because thats an older version of tough as nails

**Comment by Adubbz** [comment]
This has already been fixed in newer mod versions
