### ISSUE TITLE
Ozzy chestplate liner

### ISSUE THREAD

**Issue by blh92385** [Glitchfiend/ToughAsNails#680]
## Issue Report

[ Ozzy Chestplate liner compatibility ]</br>

### What's the issue you encountered?

[ Dragon Scale Chestplate cannot be enchanted with Ozzy chestplate liner in RLCraft modpack]</br>

### How can the issue be reproduced?

[Create a Dragon Scale chestplate in RLCraft and try combining it with Ozzy chestplate liner, I'm not sure if it matters, but I am using the Red version of the dragon scale chestplate. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ RLCraft 1.12.2 - Beta v2.8.2 - ToughAsNails-1.12.2-3.1.0.141-universal.jar  ]</br>

**Comment by Forstride** [comment]
1) Modpack issues are not our issues, and neither of the things you mentioned are even part of Tough As Nails.

2) We do not support versions below 1.16, as it says when opening a new issue
