### ISSUE TITLE
Overwriting FoodStats::tick crashes with other mods injecting into the same method

### ISSUE THREAD

**Issue by Fuzss** [Glitchfiend/ToughAsNails#681]
Please don't use `@Overwrite` on FoodStats::tick. My [Golden Age Combat mod](https://github.com/Fuzss/goldenagecombat) tries to inject into that method, it being overwritten by Tough As Nails leads to a crash on start-up.

Using `@Inject` at `HEAD` and then calling `CallbackInfo::cancel` leads to exactly the same result without having any compatibility issues.

**Comment by Adubbz** [comment]
Closing this as this is effectively what is done now, except with ASM rather than Mixins.
