### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#683]
## Features Request

</br>

### What features are you suggesting?

Temperature at 1.16</br>

### Why should it be added?

Because 1.17 was postponed for another year...</br>

**Comment by Forstride** [comment]
Did you miss the part where they're splitting it...?  It's still going to be 1.17, and it's still going to have powdered snow, which is why we're waiting to reimplement temperature.  Please do not open an issue like this again in the future.

**Comment by ghost** [comment]
Just 1.16.5 is a very popular version, something at the level of 1.7.10 
or 1.12.2 and it would be a little sad to see only thirst.... But as you wish ¯\_(ツ)_/¯
