### ISSUE TITLE
Food gives hydration

### ISSUE THREAD

**Issue by MegaGamer265** [Glitchfiend/ToughAsNails#685]
Some or all foods should give you hydration.

Foods that should give hydration:
Mushroom soup
Milk
Betroot soup
Watermelon

And maybe add a bigger canteen.

**Comment by Forstride** [comment]
I already toyed around with certain foods restoring thirst, and it's very unbalanced.  It'd completely negate the point of using thirst-restoring items at all, especially when most of those are pretty good for restoring hunger as well (Aside from melons, but you get them in large quantities).

I may or may not add fruit juices again, but right now I just want people to play around with water as the primary hydration source and see how it feels before we go crazy with new items.  Larger canteens could maybe be a better solution to that though.
