### ISSUE TITLE
Better Liquids + New Items + Compatibility

### ISSUE THREAD

**Issue by MegaGamer265** [Glitchfiend/ToughAsNails#687]
Dirty and purified water could be its own real liquid. Then we can make it compatible with other mods so we can fill
it in tanks from Create or in buckets or maybe in backpacks from TravelersBackpack.

Now to the new items.
There could be new canteens wich are bigger or maybe some have special abbilities, like a magical canteen wich cleans water automaticaly (or an enchantment atleast).

**Comment by HonzaVinCZ** [comment]
I think the actual liquids should be added so we can make some automation with machines. No idea why devs haven't done that yet.

**Comment by Forstride** [comment]
We now have additional canteens that can hold more water in 1.20.4.  We don't have any plans to add dirty/purified water as actual fluids however.
