### ISSUE TITLE
Air Quality

### ISSUE THREAD

**Issue by Squallll94** [Glitchfiend/ToughAsNails#691]
## Feature Request

Air Quality for example in Caves, specific Biomes.

### What feature are you suggesting?

If you stay too long in caves or specific Biomes (configurable) you start to take damage.

### Why should it be added?

By using specific mods, the Overworld can get quite dangerous. An easy way out is to just dig into the ground and live in a cave, instead of building a base on the Overworld.
With this addon, living in a cave gets more challenging and you cant just take some wood logs and food with you in the eraly game and come out with full iron gear or even diamond.

**Comment by SweepSwap** [comment]
i think there should be a way to counter this, such as a gas mask or something similar to negate this effect, though having a durability meter might also be nice for the mask

**Comment by Forstride** [comment]
We planned for this at one point, but air quality/gasses are a big enough feature that it'd be better suited for a separate mod (Which, separate mods *do* already exist for this)
