### ISSUE TITLE
Thirst bar disappears sometimes and doesn't comes

### ISSUE THREAD

**Issue by SiyahEkran** [Glitchfiend/ToughAsNails#694]
## Issue Report

Thirst bar disappears.

### What's the issue you encountered?

When I start to play minecraft with Tough As Nails mod, sometimes the thirst bar disappears and doesn't even comes until I reinstall the mod.

### How can the issue be reproduced?

Sometimes when I right click the any item, sometimes the water bar disappears.

### Logs

![issue](https://user-images.githubusercontent.com/84401529/123989094-3aa1b300-d9d1-11eb-9c81-b82e3fc048b2.png)

### Mod Version

1.12.2 Forge

**Comment by Forstride** [comment]
"For bugs that occur with Tough As Nails for 1.16.4. We do not support older versions!"
