### ISSUE TITLE
ATM 6  V1.16.5   90-100% CPU Load

### ISSUE THREAD

**Issue by SpartaWarsec** [Glitchfiend/ToughAsNails#697]
### What's the issue you encountered?

Problem on server ......    90-100% CPU load. 

### How can the issue be reproduced?

install the mod ...  nothing else .... remove the mod cpu load normal on  4-5 %

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ ToughAsNails-1.12.2-3.1.0.139-. ]</br>

**Comment by Adubbz** [comment]
You say you have nothing else installed, whilst listing ATM 6 in the title which contains a _massive_ amount of other mods. Furthermore, you haven't included any logs, and you've listed the 1.12 version of Tough As Nails despite having 1.16.5 in the issue title...

**Comment by SpartaWarsec** [comment]
the server is for 20 people I had to see that it is running again ... I can see if I play it on a test server and send you another log or if I send you all of the logs from last night from this morning

**Comment by SpartaWarsec** [comment]
[LOGS 26.07-27.07.zip](https://github.com/Glitchfiend/ToughAsNails/files/6884260/LOGS.26.07-27.07.zip)

**Comment by Forstride** [comment]
You're running a massive modpack with like 300+ mods...That's not "nothing else".  Also there's nothing in Tough As Nails specifically that would cause more CPU usage than half of the other mods in the modpack.
