### ISSUE TITLE
Making purifying less useless

### ISSUE THREAD

**Issue by chawrona** [Glitchfiend/ToughAsNails#698]
Making purified water restore 5 units of irrigation bar instead of 3

The irrigation bar is dropping too quickly. 
You need to drink non-stop. It woudnt really be that bad, if only a water bag not restoring only one and half (3) units of irrigation bar. 
You need to drink NON-STOP. 
Just so, there is no need to even try spending time on purify water if that only adds one more (3 instead of 2) units of irrigation.
1.16.5

**Comment by Adubbz** [comment]
I have increased the default thirst restored by canteens/bottles in the 1.18 version. Further changes can be made via datapacks if you wish.
