### ISSUE TITLE
Incompatibility with Slashblade

### ISSUE THREAD

**Issue by APolarBaer** [Glitchfiend/ToughAsNails#70]
for some reason with tough as nails, slashblade doesnt work properly, on left attack and it causes the right attack animations and combos to reset. not a crash but i  wanted to bring this up incase you have time to look into it. 1.9.4 tough as nails 1.0.6 slashblade r13-r15

**Comment by Jomik** [comment]
I don't experience this issue. I'm using the latest versions available at this time.
