### ISSUE TITLE
Game crashes on startup with latest version of Tough as Nails

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Glitchfiend/ToughAsNails#702]
## Bug Report
After updating to the latest version of Tough as Nails, my game just crashes on startup. No crash report was generated so only the latest log is included in this issue.  This issue occurs without any other mods installed.

### How can the crash be reproduced?
1. Download and Install Latest Version of Tough as Nails for Minecraft 1.16.5. (4.0.1.7), (Forge 36.2.2)
2. Start up the game
3. Game crashes

### Crash Report and Logs
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/7008970/latest.log)

### Mod Version
4.0.1.7

**Comment by daritoboi** [comment]
v

**Comment by The-Bernician-Lamb** [comment]
This was a fixed a bit ago, I just forgot to close the issue until now. Thanks for your help!
