### ISSUE TITLE
when i put in tough as nails in my folder game crash

### ISSUE THREAD

**Issue by daritoboi** [Glitchfiend/ToughAsNails#703]
## Bug Report

the launcher crash when i put it in the mods folder and i try to launch minecraft

### How can the crash be reproduced?

1: put in mod folder.
2: message pop up on launcher says the game crashed

### Crash Report and Logs

i cant

### Mod Version
16.5

**Comment by daritoboi** [comment]
help i rely want to play with tough as nails

**Comment by The-Bernician-Lamb** [comment]
Mate, Calm down, Just use this version for now: https://www.curseforge.com/minecraft/mc-mods/tough-as-nails/files/3203067

**Comment by Forstride** [comment]
@daritoboi Stop spamming comments in other issues or you will be blocked.  You have not provided any info at all like a crash report or logs, and if you cannot do so, we cannot help you.

**Comment by Adubbz** [comment]
This should be fixed as of earlier so I’m closing this
