### ISSUE TITLE
The water purifier cannot be obtained

### ISSUE THREAD

**Issue by TheSameCat** [Glitchfiend/ToughAsNails#706]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue with only Tough As Nails installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
1.17.1

**Comment by Forstride** [comment]
?  It can.  The recipe is unlocked for the recipe book when you get charcoal.

**Comment by TheSameCat** [comment]
> ? It can. The recipe is unlocked for the recipe book when you get charcoal.

Apparently I did not put it right, while you break this block, it does not fall out as an object, and breaks for a very long time with any tool
