### ISSUE TITLE
Hunger Bar Frozen; Healing stops.

### ISSUE THREAD

**Issue by Lynxana** [Glitchfiend/ToughAsNails#712]
### What's the issue you encountered?

Having only BOP, Serene Seasons and Tough as Nails installed for 1.17.10 the hunger works fine until encounter with a skeleton.  Unsure if it does this with any other creature.  I did try with three new games and received the same results.  Once I removed Tough as Nails I could not reproduce this situation.</br>

### How can the issue be reproduced?

Get hurt (from height damage, etc.) you should lose enough to eat and heal.
Then go face a skeleton and let them hurt you.
After which the hunger bar is frozen on full and you no longer heal.</br>

### Mod Version
Tough As Nails 1.17.1-5.0.0.45</br>

**Comment by Adubbz** [comment]
Hunger is untouched by Tough As Nails. The only way what you’re describing would happen is if your thirst bar is low, in which case it would be intentional behaviour. You need high levels of hunger AND thirst for health to restore.

**Comment by Lynxana** [comment]
Thank you for getting back to me so quickly.  I am still trying to figure the mod out (first time I have ever used it) I didn't even know you could drink water from standing water unless you crouch until right after I posted this.  Anyway, my thirst bar in the last two times I tried it was missing less than two, but I'm assuming they have to be all the way filled to get the healing effect.   Either way, thank you, I will be trying it again and if all goes well then I am sorry for wasting your time, but I appreciate the time you wasted.
