### ISSUE TITLE
Tough as nails using up more % than necessary

### ISSUE THREAD

**Issue by Raycoms** [Glitchfiend/ToughAsNails#713]
### What's the issue you encountered?

Tough as Nails using more CPU than necessary

### How can the issue be reproduced?

Server with a bunch of players online

![image](https://user-images.githubusercontent.com/6438347/136631574-5c589c97-fa63-4a38-9db5-5afcbed96f63.png)

Full spark for reference:https://spark.lucko.me/n2m43laU1A

This seems sth that could be easily optimized by only ticking it every random x ticks, etc.

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Raycoms** [comment]
This is twice btw:

![image](https://user-images.githubusercontent.com/6438347/136631653-33cbdaa6-64f9-43b0-835a-555d8a408812.png)

**Comment by Raycoms** [comment]
Found some additional costs elsewhere too:
![image](https://user-images.githubusercontent.com/6438347/136708257-50d693bf-dc78-49a9-819a-dc4da5d5653b.png)

**Comment by Adubbz** [comment]
Some level of performance impact is simply unavoidable given what the code aims to do. That said, it should be improved now with the refactor of the code for 1.20.4.
