### ISSUE TITLE
Can't find heating/cooling coils

### ISSUE THREAD

**Issue by roseteeth** [Glitchfiend/ToughAsNails#714]
Hello! I can't find any sort of heating/cooling coils in the game, neither in creative mode in the menu nor using just enough items. I really hope this is a glitch and that they have not been permanently removed, as I find it much less enjoyable to play without being able to heat/cool an enclosed space with them. If you have chosen to remove them please, please bring them back in the next update. Thank you and thank you for your work!

**Comment by Adubbz** [comment]
This is not a bug, they were intentionally removed given their poor performance, horrible code, and frankly bad mechanics. Heating/cooling within your house can be achieved simply by placing heating/cooling blocks within it instead.
