### ISSUE TITLE
Temperature system needs refining

### ISSUE THREAD

**Issue by roseteeth** [Glitchfiend/ToughAsNails#715]
Hello! On the second floor of my house (enclosed space), in which I have heating sources such as campfires & magma blocks, I am still getting the freezing effect during autumn, but only in some parts of the house (despite it all being build on the same biome). The heating sources dont really heat up the space, and trying to stand closer to them immidietly leads to the burning/too hot effect, so there's no real middle ground & I'm afraid the issue will get worse during winter (I'm using serene seasons). I know that the temperature system has just been implemented again and its still a work in progress, but I think it needs to be made to be a bit less sensitive & the coding on the heating blocks needs to be reworked (if the temperature is apparently freezing than standing in the proximity of a fire shouldn't instantly burn you). 

Thank you & thank you for your work and for continuing to update this mod!

**Comment by Barerock** [comment]
Temperature changes seem entirely too abrupt in general. I jump one block down in a cave and instantly burn, walk one block too far into a savannah and immediately take heat damage, stray a little too far over a block into a vaguely snowy area and get hypothermia. It's annoying and restrictive, not hard. It adds nothing to the game to make heat so hardcore.

**Comment by Kingfuzzbut** [comment]
Totally agree. I have a campfire in my base. When I am one block away I burn, two I'm fine, three I'm frostbitten. Feels more proximity based than a stat that goes up or down.

**Comment by dannydjdk** [comment]
Part of the problem is that the debuffs happen much too quickly. I spawned into a world in a rainforest and started taking damage within a few seconds of spawning.

I would classify this as a major bug. It's really not playable in this state.

**Comment by Adubbz** [comment]
Temperature now changes gradually, temperature/cool sources now only apply when they aren't being blocked by other blocks and the only a single point temperature change applies to temperature/cool sources to prevent burning alive when right next to them. With all of these things combined, this should be addressed.
