### ISSUE TITLE
Incompatibility with Origins mod

### ISSUE THREAD

**Issue by ekiplier** [Glitchfiend/ToughAsNails#717]
### What's the issue you encountered?

TAN is compatible with the Origins mod because origins that don't deal well with water still get damaged by drinking water from a water bottle. Also, Origins that allow for water breathing shouldn't really have thirst. The thirst system should be disabled for players who choose such origins

### How can the issue be reproduced?

Install both TAN and Origins; choose origin that can breathe underwater or doesn't like water; drink water from a water bottle; see the issue

### Mod Version
ToughAsNails-1.16.5-4.1.0.9

**Comment by Forstride** [comment]
AFAIK Origins doesn't even have an official port for Forge, so we're definitely not adding extra compatibility for that.  This is stuff that could probably be handled on their end anyway.
