### ISSUE TITLE
temperature and thirst not working

### ISSUE THREAD

**Issue by dudejuststop** [Glitchfiend/ToughAsNails#718]
ok i have no idea what all those extra things were so im just going to delete them and id ask in the discord but the stupid server wont even let me it just does this Clyde
BOT
 — Today at 9:37 PM
Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en-us/articles/360060145013 which makes no sense and its not like i can dm the devs so anyways i have the mod and there is no thirst or temperature with serene or tough as nails and the nails mod version was 1.12.2-3.1.0.141 and serene was the newest one

**Comment by Adubbz** [comment]
1.12 is not supported.
