### ISSUE TITLE
really

### ISSUE THREAD

**Issue by dudejuststop** [Glitchfiend/ToughAsNails#719]
if 1.12 is not supported then why is it litterally a version on BOTH of the mods AND on top of that i literally saw a youtuber using it on that version 😒😒😒

**Comment by Adubbz** [comment]
YouTubers using a given version has nothing to do with us. 1.12 versions of our mods exist and are available to those who wish to use them, we just don’t offer any support for them.

**Comment by dudejuststop** [comment]
ha i was right it was just a setting in the config
