### ISSUE TITLE
So i made config for some mods and want to share it with those who seek it.

### ISSUE THREAD

**Issue by sloweia** [Glitchfiend/ToughAsNails#721]
This config includes: juices, tea, coffee, cacao, hot chocolate, milk, alcohol, soups, some food and some other stuff.

To install
Download txt
Copy and paste all the content to the tan's thirst config under thirst "drink_options" in the end.

(https://github.com/Glitchfiend/ToughAsNails/files/7614486/tough.as.nails.mods.compact.1.16.5.txt)

mods:
better beekeeping
juices (domino_loots) 
alex's mobs
farmer's delight
simple farming
nether agriculture
simple delight
crockpot
vanilla cookbook
create
pharmacist
nethers exoticism
create cafe
create confectionery
drink beer
coffee mod (by owca85)
husbandry

**Comment by Forstride** [comment]
This is not an issue and not the appropriate place to post this...

**Comment by Adubbz** [comment]
You’re certainly welcome to make/distribute such a config, but yeah, this isn’t the venue for it.
