### ISSUE TITLE
Dying Poncho turns back to original state of color 

### ISSUE THREAD

**Issue by Klouver-github** [Glitchfiend/ToughAsNails#723]
## Bug Report

when you dye the leaf clothing that you wear like a naked man in movie the dye disappears 

### What's the issue you encountered?

I was using Brown dye to dye the clothing

### How can the issue be reproduced?

get any color dye, dye the poncho or leaf armor then put it on

### Logs

there no crash logs or anything crashing

### Mod Version
1.18.1-6.0.0.49

**Comment by Forstride** [comment]
It's not supposed to be dyed, but it technically allows you to because that's how the biome-dependent foliage coloring works for it.
