### ISSUE TITLE
1.18.1 Configurable Hot Cold and Warm Liquids 

### ISSUE THREAD

**Issue by drhaber** [Glitchfiend/ToughAsNails#724]
This is actually a request for 1.18.1.

But the ability to have a list of three liquids that can be readily modified would be insanely useful for pack making.

Warm liquids would set the body temp to normal when immersed
Hot liquids would set the body to hot when immersed
Cold liquids would set the body to frigid when immersed

**Comment by DownLoude** [comment]
What about adding the same for held liquid buckets and/or a general system for defining hot or cold items?

**Comment by Forstride** [comment]
> What about adding the same for held liquid buckets and/or a general system for defining hot or cold items?

This is already a feature (Held items affecting temperature that is, not the drinks suggestion)

**Comment by DownLoude** [comment]
Is it a config file with configurable temperatures, or a tag list or something? how do i change it?

**Comment by Forstride** [comment]
> Is it a config file with configurable temperatures, or a tag list or something? how do i change it?

It uses item tags, just like how heating/cooling blocks use block tags.  You can find the default ones in the .jar file

**Comment by Warbringer12** [comment]
can you use a block tag that has nbt?

**Comment by Forstride** [comment]
No, tags can't use NBT data at all

**Comment by Thundercatsffs** [comment]
Would love this. Especially if Ocean water in cold biomes are set to cold, near magma blocks are set warm or hot and if you can heat water with fire. Would be wonderful to have a create addition for this to add some complexity and usefulness to the current steam engines of that mod.

**Comment by Forstride** [comment]
Not sure if this is really necessary since you can just set the fluid *block* as a heating/cooling source.  I feel like if you have a fluid that warms/cools you when you're submerged in it, it would naturally give off that temperature outside of it too.
