### ISSUE TITLE
Late game QOL additions

### ISSUE THREAD

**Issue by Barerock** [Glitchfiend/ToughAsNails#726]
## Feature Request

-QOL additions for late game and modded playthroughs-
<details>
<summary>1. Late game water QOL</summary> 
Better water acquisition, storage, and drinking systems. It'd be great to be able to not deal with water after a certain threshold of resource advancement. This idea can range in implementation; maybe End resources could be used? A water pump that fuels water fountains I can place around my base? Using End resources allows a late game player to stop worrying about the constant need for water - think auto-refilling canteen made of netherite, shulker shell, and ender pearls? That's expensive, but it effectively eliminates a _hard_ limit I have with this mod where getting water and purifying it just takes soooo much time out of my day.

The End Bottle would of course require a source. I'm thinking an "Ender Rain Collector" or an "End Basin" fed by a rain collector with a pipe system that can link with your bottle cross dimensionally to fill it when it has water. If it runs out... oh well, back to collecting dirt water until it rains again. I think this is the easiest of the changes I suggest, the most balanced, and the most needed. Water collection is simply _exhausting_ and never changes throughout the game. I end up turning it off eventually even though I love it initially.
</details>

<details>
<summary>2. Heat system additions</summary>
Armored dual heat resistance AND/OR heating and cooling system for buildings. Having to wear my specialized armor around my base because I don't want a fireplace every five steps, or around my greenhouse farm, or in my mob grinder is annoying. Having to switch out armors constantly can get hectic and ends with getting merced by temp changes. Elytra in a big savannah? Sorry, flew into a rock wall because I was changing my armor without bothering to land because it's time exhaustive.

My suggestion for AC for homes is more of a space heater idea. If I put a fireplace in my house, or 2, or 3, I want it to heat the whole thing. If I have an enclosed space, can a heat source add a parameter that changes the heat of the area it's enclosed in? I don't _think_ it would be too hard to add, but I'm not a Java programmer.
</details>

<details>
<summary>3. Inventory temp control system</summary>
Different types of in-inventory cooling. Going mining sucks with the heat system, currently. Not being able to move at all beyond the temperature threshold underground is awful, I'm sorry, but it is. What would solve this _and_ retain the current system without too many tweaks to the existing code? In-inventory cooling! What if I could dig up a buttload of snow or ice and hold it in my inventory to cool down instead of jumping in water and needing to be stationary? Each block/item of course has a bar once you reach hotter temperatures that depletes until that item no longer exists. It melts. 

Similarly, hot items wouldn't really melt, would they? But things like blaze powder could simply disintegrate, magma cream can be transformed into regular slime, and things like a lava bucket will eventually cool, empty the bucket, and generate one cobblestone. Magma similarly can turn into cobblestone or blackstone when it cools. This system seems simple, but I know it could definitely take a lot of work to implement.
</details>

These are the three major additions I would like to see in the mod, and I think your mod would greatly benefit from the effort to put them in from a sustainable gameplay viewpoint. Each has my explanation, but creative freedom is absolutely welcome! It's your keyboard you're coding with, not mine :)
  
-Why?-

Currently it feels as if this mod doesn't progress naturally. I kill a few cows and get a water skin, mine some iron and get a purifier, get some glass and I have a collector... what else? Adding Serene Seasons obviously helps to add danger and stockpiling needs, but what about late game tech? I've got netherite armor, a castle the size of the moon, and five hundred thousand of every resource in game... but I'm drinking out of a leather water skin and a bucket poured on the ground still? Water especially gets old fast, but the heating system could use some special work to make it a little more useful and convenient.

Adding tech items (not futuristic, just better, more convenient) allows the player more freedom of movement, it's identical to the idea of temperature resistant armors (leaf, fur). They allow more freedom and therefore resource acquisition and less time trying to survive in my billionaire playboy hogwarts castle made out of sponge.

Lastly, thanks for the mod. It truly is awesome and I've been using it since... ever. Since it was released, I think. My experience with it is what makes this feature request special.

**Comment by Forstride** [comment]
I mean there's already a treasure enchantment that completely neutralizes your temperature.  I know we don't have documentation, so you might not have known about it, but if you do, I'm not sure what would even be needed beyond that.  I do kind of want to change up how temperature in the nether/end works though, and add armor types that are "required" for those, since it doesn't really make sense to use leaf armor to cool down in a hellish dimension.  Was also considering adding an insulation block for more permanent temperature solutions in homes.

As for thirst, I'm not sure what exactly you want aside from like, drinks that restore more thirst.  I do think I'll end up adding juices back or something, but IDK if that's necessarily what your suggestion was meant to be.  If you're suggestion an entire overhaul to the mechanic, just keep in mind that it's basically supposed to be a clone of the hunger mechanic.  And with that, it's not like food really changes late game, as your hunger is still going down and you have to keep eating food one piece at a time.

**Comment by Barerock** [comment]
"drinks that restore more thirst" isn't what I want. I'm more suggesting an added item and supply system that make water acquisition easier. Instead of having to carry a bucket around or constantly fill up my tiny water pouch, the canteen would allow water from a pure collection system (with proper end game balance) to be supplied directly to the bottle without having to collect it manually.

I like the mechanic as it is, thirst works very well and provides a threat to survival. I'm more advocating for proper late game advancement so my decked out super soldier Steve doesn't have to drink pondwater every time he leaves home. Water isn't annoying to drink, it's annoying to collect. Unbreaking enchantments don't work on the water skins, and every time I need water I have to stop and wait for the unpure debuff to go away and then drink more, and wait, and... etc. Having a constant supply of pure water is insanely time consuming, and isn't very fun when it requires a whole system of placing the purifier, purifying, carrying other resources just to not get thirst.

As for heat, I had no idea there was an enchantment for that! I've never found it somehow.

**Comment by Barerock** [comment]
As an added statement, I've been thinking about my current modded playthrough and these limits can be broken by technological advancement through other mods. Using Create's factory system, I can totally create a pure water factory that feeds an ender chest when I put an item in the ender chest that it pulls out, signalling that I need some gatorade. 

However, that entire process just to avoid collecting water shouldn't take a separate mod to do.

**Comment by Forstride** [comment]
>to be supplied directly to the bottle without having to collect it manually.

That doesn't even make sense.  Where would the water just magically come from?  There's nothing in vanilla that works like that for food/hunger, and we base the design of our mods around vanilla, not what tech mods do.

**Comment by Barerock** [comment]
Did you read the full description of each addition?

**Comment by Barerock** [comment]
I explained that using End resources and nether resources to properly make it late game (end stone, shulker shells, maybe a nether star, who knows) would make it lore friendly.

**Comment by Forstride** [comment]
I just don't feel like this is a solution that should be in TAN itself.  TAN isn't a tech mod, but you want us to implement tech mod-esque solutions for thirst.  I'm open to adding better drinks that can restore more thirst and whatnot, but not weird magic item transportation specifically for thirst.

**Comment by Barerock** [comment]
How is that weird though? Ender magic is lore friendly and accepted as part of the game. It's not at all tech mod esque because we already have vanilla systems that literally spawn things out of nowhere for our gain (farms), there's ender pearls, and there's enchanting.

**Comment by Barerock** [comment]
We also have things like nether stars and lodestones, which, in-game, connect two items just like what I'm suggesting. It could easily be implemented as a bottle made with a nether star and a "water storage thing" made using a lodestone. Done, that's basically vanilla right there.

**Comment by Barerock** [comment]
At the very least, bigger water containers are needed. This mod could totally utilize the late game resources to make bigger canteens. Iron canteen? Awesome, Netherite canteen? Even better! Shulker and netherite canteen? Very very better! Gathering is the part that needs to be solved.

**Comment by isuke01** [comment]
i strongly agree with you @Barerock, that some bigger water containers would be nice, like made out of some end resource like shulker shell + canteen so make it much bigger etc, sounds good.  
Also some thing to awoid heat early game (Later game just live with fire res-potion is way to go ;p) so I can go to desert or savanna without dying almost immediately, straw hat? So it delay time before player overheat on those biomes, it could not in hell demension since it does not make sense. Now play style is: Water bucket jump into water, take it ... etc

BTW: Yes I'd like to play it with seasons but Seasons does not work on LAN, second player just can't join :(
BTW2: Some wiki would be nice ;D

**Comment by Barerock** [comment]
@isuke01 Wiki would be great. My main point of this thread is to offer very lore friendly late game technological advancements to provide real progression to this mod, as currently it doesn't make sense to be subject to such silly rules with late game gear and resources. My current 3 major additions very much rely on vanilla lore and mechanics, so I'm not sure why they've been dubbed unacceptable. Currently I'm just breaking the mod by using Create to subvert the gathering mechanics for water.

**Comment by Barerock** [comment]
The problem with adding back juices, @Forstride, is that _gathering_ still becomes an issue. The entire point of my suggestion is to come up with an acceptable way to fix the game breaking annoyance that water becomes. I should not have to go to a pond every few minutes when I am geared out. Making juices is the same, I still have to take an immense amount of time farming and preparing said juices, mining sand, smelting, then drinking it all in just 30 minutes because the thirst is unrealistically hardcore (needing a drink after literally 5 seconds is how I'm living right now).

This mod simply does _not_ have any progression in it. It limits you at caveman technology.

**Comment by MarioSMB** [comment]
Have you considered making some foods provide a bit of hydration? This is how some survival games tackle the issue of thirst; a piece of fruit for example would provide almost equal amounts of food and water. With that in mind late-game food sources could double as a source of hydration, reducing the need for constant canteen refills.  

Magic is not an alien concept in Minecraft (what with the Infinity enchantment and 2x2 providing infinite water sources), but I do agree that linear progression towards an infinite canteen would be a little lacklustre gameplay-wise.  
An enchantment to increase the carrying size of canteens would likely go a long way in resolving the frustration of refilling it so often, if that doesn't already exist.  

With regards to the rate of thirst - I do not believe it should be tied to actions the same way hunger is, but rather go down by a semi-linear rate, only being affected by temperature (hot climates would cause quicker thirst for example). Some other things could of course affect thirst, such as the consumption of potions, but that's a little off-topic here.  
The temperature system may benefit from taking some pages from Valheim and similar games; campfires could provide what's effectively a beacon effect for "comfort" - a hidden buff that increases in potency when sheltered (simply placing one down in the rain has minimal effect beyond temperature control, while being under some blocks would provide immunity from the surrounding climate effects).

**Comment by Adubbz** [comment]
Between all of the recent additions to thirst (new canteens, general bugfixes which reduce the thirst reduction rate, the water purifying enchantment) and temperature (the new thermoregulator block, consumable items which provide temporary heating/cooling, support for heating/cooling armor trims) I think we've covered a vast majority of these things in one way or another, so I'm closing this.
