### ISSUE TITLE
Cant drink water in 1.18.1. i checked my control settings. it should be right click as usual. but for some reason i can do everything else with right click but drink water from sources

### ISSUE THREAD

**Issue by RealGBurkly** [Glitchfiend/ToughAsNails#727]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue with only Tough As Nails installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Adubbz** [comment]
Drinking from hands is now a config option and is disabled by default. It can be found in your save folder/serverconfig/toughasnails-server.toml. The intended way of drinking is through canteens or bottles.
