### ISSUE TITLE
Hand drink from Cauldron

### ISSUE THREAD

**Issue by Calibrumm** [Glitchfiend/ToughAsNails#728]
### What feature are you suggesting?

[ you should be able to hand drink from cauldrons. the condition of the water would be based on where you got it. ]</br>

### Why should it be added?

[ convenience? I just thought it was a bug initially but I don't see anyone online talking about it as a bug, or at all, so I figured it was intentional or overlooked. ]</br>

**Comment by Forstride** [comment]
We're not support hand drinking any more than what's already there.  There's a reason it's disabled by default, because it's not meant to be used at all, and is only there so people don't whine to us to re-add it.
