### ISSUE TITLE
Game crashes on startup due to conflict between Pollen and Tough as Nails

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Glitchfiend/ToughAsNails#730]
## Bug Report
After attempting to test some new mods in my modpack I found that whenever I tried to load the game with them installed that the game just crashes on startup without generating a crash report. I found that these new mods didn't crash when loaded on their own, so I gradually removed a few mods at a time to identify which mod they were conflicting with. After a while I found that it was Tough as Nails that was conflicting with these new mods, specifically with their library mod called Pollen (https://www.curseforge.com/minecraft/mc-mods/pollen). Sure enough, I found that when either of these mods were absent from my modpack, the game loaded normally and with no issues. I have no idea which mod is the issue here, so I'm reporting this issue to both githubs and we'll take it from there.

### How can the crash be reproduced?
1. Download and install both Tough as Nails and Pollen.
2. Attempt to launch the game with both of these mods installed.
3. Game crashes without a crash report.

### Crash Report and Logs
(In the absence of a crash report, I decided to include the debug log as well in case that helps)
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/8116529/latest.log)
[debug.log](https://github.com/Glitchfiend/ToughAsNails/files/8116531/debug.log)

### Mod Version
Tough As Nails Version: 6.0.0.68
Pollen Version: 1.1.0
Forge Version: 39.0.88

**Comment by jacksonhardaway** [comment]
Seems to be due to the `LocalPlayer#aiStep` patch causing all `setSprinting` invocations to be redirected to one provided by Tough As Nails.

Pollen targets a `setSprinting` call in a mixin, making it unable to find the target due to it being modified by Tough As Nails.

**Comment by VirtualGaming1** [comment]
Linking this with my Issue on Pollen Side
https://github.com/MoonflowerTeam/pollen/issues/9

I am using MC 1.18.1 and forge 39.0.85

**Comment by Ocelot5836** [comment]
I checked the ToughAsTails ASM and I think this issue would be resolved by redirecting the calls instead of replacing them. Pollen is trying to disable sprint if in custom liquids after the player has started sprinting, so this shouldn't cause any issues for either mods. Plus, I think general compatibility between this mod and others would be slightly improved by leaving the original signature.

**Comment by Adubbz** [comment]
This has been fixed in 1.18.2
