### ISSUE TITLE
Crash with comforts

### ISSUE THREAD

**Issue by ekiplier** [Glitchfiend/ToughAsNails#733]
### What's the issue you encountered?

Game crashes on start-up if TAN is installed with the latest version of Comforts

### How can the issue be reproduced?

Install both Tough as Nails and Comforts mods. Start the game. See crash

### Logs

https://gist.github.com/ekiplier/a2b51aa9b083164222cd0190bcacff65

### Mod Version

4.1.0.9

### Additional information

https://github.com/TheIllusiveC4/Comforts/issues/81#issuecomment-1090396953

**Comment by Adubbz** [comment]
1.16.5 is no longer supported.
