### ISSUE TITLE
Temperature System Improvement

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/ToughAsNails#735]
### Overview

Currently, it goes from -4 to 4 for temperature from my understanding. 
Adding the possibility for players who wish to make the temperature not as hard, allowing larger extremes to flatten out the curve leading to burning and freezing. 
A player could change from -4 to 4 
To something like -8 to 8 if they wanted it to be 2x easier or less punishing.

### Why would this feature be useful?

Would allow more options for customization for the temperature system for modpack makers, would also make it a better option for using TAN temperature system instead of a mod like Cold Sweat which has a very good competing system to yours.

**Comment by random-potato25** [comment]
Also, it seems the temperature seems to change way too fast. Stand in a desert for 15 seconds and you begin to burn (1.18.2).

**Comment by Jusey1** [comment]
Honestly, I be more open to the -4 to 4 system if we could customize the biome related temperatures. I rather being punished for doing something stupid in a biome, not be punished for merely existing.

**Comment by Forstride** [comment]
We don't have any plans to change the actual temperature scale.  That being said, the temperature system has been nerfed in multiple ways since this issue was opened, so I'm just gonna close it.
