### ISSUE TITLE
Lifeblood Crystal Lanterns

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/ToughAsNails#74]
This suggestion might be out of TAN's scope but I'll just give it a try,

After gaining 5 Lifeblood Crystals in the Nether to increase your health back all the way to 10 hearts they become useless afterwards. To give them a little bit of use in mid-/end-game you can use Lifeblood Crystals to make Lifeblood Crystal Lanterns. To craft this lantern you'll need 6 iron ingots, 2 glass blocks and 1 Lifeblood Crystal of course placed in a pattern like this.

![crystal lantern](https://cloud.githubusercontent.com/assets/19509275/16886481/ece60282-4ad4-11e6-931b-573d7cd6875e.png)

 When placing this lantern on the ground nearby players will get a regeneration buff as long as they stay within the lantern radius of 5 blocks.

**Comment by Forstride** [comment]
Interesting idea.  IDK about Regeneration necessarily, as players could just keep one in their inventory to use whenever.

Health Boost might make more sense, although that would probably be unbalanced too.

**Comment by UndeadZeratul** [comment]
This reminds me of the heart lanterns Terraria used, wherein their heart crystals that were used to give the player more max health would then be able to be placed in the world as a lantern and would dispense a pickup that would restore a small bit of health.  Maybe these could activate with a redstone signal to provide a potion effect for a few seconds, with a cooldown period wherein spamming it with more redstone pulses won't do anything?  That way once every, say, 30 seconds a redstone pulse would give players within a radius a small regen effect for, say, 5 seconds.  Any more pulses for the 30 seconds of cooldown would do nothing, as to prevent perpetual regen effect.

**Comment by Quizer9O8** [comment]
Thats were i got my inspiration from :D

**Comment by Quizer9O8** [comment]
About the OP part, I think its not since any nearby players do get a regen buff and lifeblood crystals are limited in the Nether if you look at it that way.

**Comment by Silvrus** [comment]
You could also make it not drop the lantern once placed if mined, or return the components minus the crystal if broken, akin to IC2's machines.

**Comment by Forstride** [comment]
I've removed the Lowered Starting Health feature, so this issue can be closed.
