### ISSUE TITLE
more armor or slots?

### ISSUE THREAD

**Issue by paille-boy** [Glitchfiend/ToughAsNails#744]
### Overview

i have a little problem concerning this mod is that maybe its bcs i also season mod or that i spawn in biome that are ultra cold but i always die of coldness and the issue is that even if i find a sheep and make a wool parka the parka die after 8hit and i have absolutely no armor... and i use other mod like tinker and create but the armor give me no heat/cold resistance so i'm stuck in one place and can't really move safely

so how about some sort of padding to add inside any armor piece or just aditional slot to put the temperature armor or smth

### Why would this feature be useful?

other armor mod compatibility and more realism

**Comment by McSquizzleswag** [comment]
That's basically taking this https://www.curseforge.com/minecraft/mc-mods/armor-underwear-mod and having it baked into TaN,
I need that sort of compatibility with Beyond Earth https://www.curseforge.com/minecraft/mc-mods/beyond-earth

**Comment by paille-boy** [comment]
> That's basically taking this https://www.curseforge.com/minecraft/mc-mods/armor-underwear-mod and having it baked in I need that sort of compatibility with Beyond Earth https://www.curseforge.com/minecraft/mc-mods/beyond-earth

that an interesting slot... sadly it need yet nother mod but that a very smol problem
the biggest is that it isn't in 1.18 x/

**Comment by McSquizzleswag** [comment]
I'm just pointing out that the thing you want, is what that armor underwear mod does too, not that you should download and try to use it

**Comment by McSquizzleswag** [comment]
What you're suggesting for a feature, is having what armor underwear does as a part of Tough as Nails
