### ISSUE TITLE
charcoal filter? / ozzy underwear

### ISSUE THREAD

**Issue by Vapor619** [Glitchfiend/ToughAsNails#745]
### Overview

hello just wondering why the charcoal filters got removed from the mod I remember in 1.12.2 it was there now in 1.18.2 is no longer here.

and also I understand the armor underwear is not part of this mod but since that doesn't seem to be getting updated could that be added to tough as nails? 

### Why would this feature be useful?

better temperature control and makes summer\winter more bearable.

better way of getting clean water whenever needed.

**Comment by Adubbz** [comment]
It was replaced with the water purifier. We have no plans to add underwear to the mod.
