### ISSUE TITLE
Support for drinks from other mods

### ISSUE THREAD

**Issue by wisniacom** [Glitchfiend/ToughAsNails#754]
### Overview

What I mean is to add support to mods like Farmer's Delight or it's addon Farmer's Respite.
For example config file where you can add drinks to replenish your thirst.

### Why would this feature be useful?

Drinks from other mods should replenish thirst.

**Comment by Adubbz** [comment]
This already exists through datapacks

**Comment by wisniacom** [comment]
Where? I searched and couldn't find anything

**Comment by Adubbz** [comment]
Please see the example datapack provided on our Discord server
