### ISSUE TITLE
More forgiving Nether

### ISSUE THREAD

**Issue by twoVipers** [Glitchfiend/ToughAsNails#756]
### Overview

It would be nice to have a recipe for some kind of liquid that survives in the nether but not for long, so you need to keep gathering resources to craft it again. 

You need to be able to get water into cantens and bottles using this liquid (infinite source); 
This liquid does not create obsidian and cobblestone;
Upon touching fire or lava the source block burns;
It does not push entities like regular water and it does not travel as much, you cannot make elevators with magma and soul sand;
It lasts for 10 seconds before it starts to decay. In those 10 seconds you will have time to refill bottles and canteens;
Once placed you can't pick it up in a bucket anymore;
Hand drinking from it will consume the whole block;
Drinking will give nausea effect;
You cannot craft any juice with it nor purrify it.
It gives the thirst effect.

### Why would this feature be useful?

It would be useful for mods that extend the nether. Such an example is Nether's Delight which allows you to farm in the nether and live there, and you can't really do that with TAN.

**Comment by Forstride** [comment]
That's a bit beyond the scope of the mod, so I doubt I'll add anything like this
