### ISSUE TITLE
Tone down the temperature and thrist system

### ISSUE THREAD

**Issue by babacon88** [Glitchfiend/ToughAsNails#758]
### Overview

its getting too hot/cold too quickly
standing next to lava/campfire inside your house often doesn't help
staying outside in desert kills you in less than a min
its annoying to have to wear wool inside your house with a campfire
I drink water multiple times every time, much more than I have to eat and its not normal
There should be better debuffs to freezing/overheating instead of insta kill because you stand outside of the rain.

### Why would this feature be useful?

I cannot just stay inside when it rains/ stand next to campfire half of the time I just want to play the game.

**Comment by Forstride** [comment]
It already was toned down a lot in 1.18.  If you're using an earlier version, we don't support those anymore

**Comment by Proxwian** [comment]
Head and cold is still overpowered, needs more fixes

**Comment by Pantheris2019** [comment]
Nether completely borked due to how intense the system is.  Unplayable.  Can't even get blaze rods or netherite.

**Comment by Dingbat1991** [comment]
Direct sun is one thing but I shouldn't have to take heat damage when being indoors / in shade. Instead there should be a debuff midway between normal temp and hyperthermia, like fatigue or increased thirst.

**Comment by Wulfengard94** [comment]
The temp system needs some adjustment. i've also experiences freezing to death next to a normal campfire while indoors. even with a set of wool on.

**Comment by Forstride** [comment]
Closing this since vanilla biome temperatures are now more appropriate in 1.20.4, and overall I feel like the temperature system is a good place.
