### ISSUE TITLE
Weird Crash when there was an explosion from TechReborn

### ISSUE THREAD

**Issue by erindal** [Glitchfiend/ToughAsNails#76]
http://pastebin.com/U3VEVTYV

The stacktrace includes tough as nails as well as TechReborn, not sure what actually happened or why.

**Comment by modmuss50** [comment]
I think it is TechReborn's fault, I am away from my PC for 2 weeks so it may take a while to get fixed.

It would also be nice to know how to reproduce it.

**Comment by erindal** [comment]
I'm still testing on that

**Comment by erindal** [comment]
I cannot seem to reproduce it. I overloaded an assembly machine with an MFE and glass fibre cable. I picked up the machine block drop, but I can't seem to reproduce it.

**Comment by vladfrangu** [comment]
This is simple to explain.

When the machine explodes, it happebed to spawn an metadata? that is outside of bounds, thus giving a crash.

"java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=type, clazz=class java.lang.Integer, values=[0, 1, 2]} to 6 on block techreborn:techreborn.machineFrame, it is not an allowed value" clearely states that something went wrong.

The fact that Tough as Nails appears, is that it has an achievement, that runs when you pick up blocks.. You picking up an illegal block caused it to spit out an error as well.

I recommend checking TechReborns GitHub (if any) report this bug with blowing up, as this isn't Tough as Nails error, but TechReborns

**Comment by modmuss50** [comment]
It has been reported on our github, I will fix it when I have the time. This issue can be closed here
