### ISSUE TITLE
Add snowshoes to walk on snow/quicksand (biome o plenty) and slide on ice

### ISSUE THREAD

**Issue by babacon88** [Glitchfiend/ToughAsNails#762]
### Overview

If you can make feather falling enchantments be able to walk on snow blocks at some degrees, that would also be nice

### Why would this feature be useful?

Digging yourself out of the snow should not be the only options anymore

**Comment by Forstride** [comment]
Aside from the fact that this is completely out of scope for the mod, Biomes O' Plenty hasn't had quicksand for years, and you can just use leather armor to prevent taking damage from powder snow.
