### ISSUE TITLE
Ice Resistance Potion Glitch

### ISSUE THREAD

**Issue by CasterFTW1** [Glitchfiend/ToughAsNails#763]
### What's the issue you encountered?

Accidentally added redstone to my Instant Health Potion. It made a 2-minute Ice Resistance Potion.

### How can the issue be reproduced?

1. Make an Instant Health Potion. (Water Bottle + Netherwart + Glistering Melon)
2. Add redstone to the Brewing Stand
3. Get an Ice Resistance Potion that is more expensive than the recipe that just uses a snowball.

### Mod Version

0.0NONE

**Comment by Adubbz** [comment]
Fixed
