### ISSUE TITLE
Heat sources ignored when player is mounted

### ISSUE THREAD

**Issue by xarvex** [Glitchfiend/ToughAsNails#764]
### What's the issue you encountered?

When the player is mounted on an entity, any surrounding heat sources are ignored and temperature "defaults" to the area.
This is the case for both vanilla and modded entities.
My best guess is a miscalculation in the block location the player is at.

Having wool clothing or armor enchanted with Thermal Tuning does still function.

![image](https://user-images.githubusercontent.com/60973030/182950301-49d7cc18-c32e-41a0-b503-febe924b29a6.png)

### How can the issue be reproduced?

1. Enter a cold biome.
2. Stand next to a heat source.
3. Mount anything.
4. Freeze.

### Mod Version

8.0.0.78

### Additional information

This bug affects many decoration mods which add chairs, as even when in a furnished and heated house, sitting in one will cause the temperature to fall back to the area default.

Sitting
![image](https://user-images.githubusercontent.com/60973030/182950358-f0202e08-e84b-4bfc-9729-2e513b8e808b.png)
Standing
![image](https://user-images.githubusercontent.com/60973030/182950398-ccacb505-e950-4812-bee8-e6a0983e7ef2.png)

**Comment by Adubbz** [comment]
Fixed
