### ISSUE TITLE
server config not saving

### ISSUE THREAD

**Issue by LarxKuba** [Glitchfiend/ToughAsNails#765]
### What's the issue you encountered?

I wanted to make it so you can drink water by hand so I changed the thingy from false to true but I still couldn't drink by hand. I've also tried disabling the temperature but that didn't work either and the server support told me that they can't do anything about that.

### How can the issue be reproduced?

I guess host a server and try to change the config

### Logs

N/A

### Mod Version

1.19-8.0.0.78

### Additional information

N/A

**Comment by Adubbz** [comment]
These options must be changed inside the server config file within the world folder. I can't reproduce any issues relating to saving these files, so I'm pretty sure this would be an issue with your hosting company.
