### ISSUE TITLE
Offset Temperature and Thirst Icons

### ISSUE THREAD

**Issue by LLavender-Az** [Glitchfiend/ToughAsNails#767]
### Overview

To customize and offset the temperature and thirst icon in the HUD.

### Why would this feature be useful?

Just so things aren't cut off and the HUD is nice and clean as well as customizable!

The reason why is cause I have another mod called 'Raised!' which raises the hot bar and my levels ae cutting off the temperature icon. 

Thank you for any consideration!

**Comment by Adubbz** [comment]
Offset options already exist in the client config in the case of thirst, though not temperature
