### ISSUE TITLE
1.19.2 potential issue with OPTIFINE

### ISSUE THREAD

**Issue by MelrikBirchJr** [Glitchfiend/ToughAsNails#768]
### What's the issue you encountered?

not enought crashes mod thinks its ur mod causing a crash with optifine and its 50/50 true cause im having issues with my mod pack and im still working on it

### How can the issue be reproduced?

Trying to join a single player or multiplayer server causes optifine to crash cause of tough as nails with not enough crashes installed

### Logs

https://gist.github.com/MelrikBirchJr/3d81faa94467309053aa19af733422ac

### Mod Version

1.19.2

### Additional information

your mod has alot of bugs with the configs and such and thirst and drinking from hands doesnt work

**Comment by Forstride** [comment]
Uhh, Tough As Nails isn't in either of the logs you posted.  It's not even in the mod list...

**Comment by MelrikBirchJr** [comment]
> Uhh, Tough As Nails isn't in either of the logs you posted. It's not even in the mod list...

thats because its not finding the error's until i remove it its then fine

**Comment by Adubbz** [comment]
We can’t help you if you don’t provide logs from when our mods are actually installed

**Comment by MelrikBirchJr** [comment]
> We can’t help you if you don’t provide logs from when our mods are actually installed

the crash logs wont provide the crash issues thats what im trying to say i just took my time to figure what mod cause it and fine ill just end it then....
