### ISSUE TITLE
Bringing back 1.12.2's mechanics animations for body temperature indicator

### ISSUE THREAD

**Issue by Pikamochzo** [Glitchfiend/ToughAsNails#769]
### Overview

Would it be possible to bring back 1.12.2's body temperature into the newest releases?? I mean, the way that you **didn't** die instantly of overheating/freezing back in the 1.12.2 was something 1.19.2 releases truly lack. Not only that, but the animations of arrow pointing up for getting warmer and down for getting colder actually made player pay attention to the temperature. Furthermore, the way the indicator was shifting its colors slowly also made this mechanic even deeper (in newest releases it's literally freezing-cold-neutral-hot-burning and if you spawned in hot or cold biome you instantly die)

https://user-images.githubusercontent.com/88740640/198098667-e01d7cb6-97e9-4079-a15c-d6572e7098ea.mp4

### Why would this feature be useful?

That little arrow animation and **gradual** color change of temperature indicator (that little circle between health and hunger) is something I miss so much in 1.18/1.19 versions because it made player pay attention to their temperature.

**Comment by Forstride** [comment]
The temperature scale doesn't work the same way, so there's no need for additional animations/gradients anymore.  Also you don't "instantly die" in 1.19.2.  There's still a delay between temperature changes, and you get 5 minutes of Climate Clemency upon spawning in a new world as well, so...
