### ISSUE TITLE
Waila shows a missing texture when a Rain Collector has water in it

### ISSUE THREAD

**Issue by erindal** [Glitchfiend/ToughAsNails#77]
![2016-07-17_21 36 43](https://cloud.githubusercontent.com/assets/12499779/16904562/a622de18-4c66-11e6-8ba4-7bf1ec21e4c1.png)

Just a minor visual glitch, not a priority by any means.

**Comment by Forstride** [comment]
I mean, I can't really know why it's happening without more info.  The rain collector has a separate item texture, and I mean, the model and everything works normally.

It would help if I knew what model it was looking for instead.

**Comment by erindal** [comment]
I'm not sure what Waila chooses to render specifically

**Comment by Adubbz** [comment]
Closing this, since Waila is rather unreliable when it comes to model rendering to begin with. I believe many of the blocks in BoP have similar issues
