### ISSUE TITLE
[Wiki] Clicking "body temperature" on the wiki yields error: "you do not have permission to edit this wiki"

### ISSUE THREAD

**Issue by JLHasson** [Glitchfiend/ToughAsNails#770]
### What's the issue you encountered?

Clicking the "body temperature" link in the wiki yields an error: "You do not have permission to update this wiki.". The link is pointing to https://github.com/Glitchfiend/ToughAsNails/wiki/Body-Temperature

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/2087380/198910077-ff641776-d7ab-42b0-a313-734297684dd9.png">

### How can the issue be reproduced?

Go to the wiki and click "body temperature" in the sidebar

### Mod Version

xxxx

**Comment by Forstride** [comment]
Yes, the wiki is incomplete, because I do not have time to do proper documentation.  This isn't really an "issue," since I'm obviously aware of it, so I'm just gonna close this
