### ISSUE TITLE
I can't add drink options

### ISSUE THREAD

**Issue by tkykkaosrsrr** [Glitchfiend/ToughAsNails#771]
### What's the issue you encountered?

I changed `thirst.toml` to add drinks
```
[drink_options]
	#Thirst restored from drinking with hands.
	#Range: 0 ~ 20
	hand_drinking_thirst = 1
	#Hydration restored from drinking with hands.
	#Range: 0.0 ~ 1.7976931348623157E308
	hand_drinking_hydration = 0.1

	[[drink_options.drink_entries]]
		location = "minecraft:honey_bottle"
		thirst = 4
		hydration = 0.3
		poison_chance = 0.0

[biome_options]
~~
```
But when the game starts the part about adding drinks is automatically removed.
It also removed when tried in an environment only this mod is installed.

### How can the issue be reproduced?

change `thirst.toml` then launch Minecraft

### Mod Version

8.0.0.78

### Additional information

1.19.2 forge 43.1.52

**Comment by Adubbz** [comment]
Drinks are now added through data packs, not the config file

**Comment by tkykkaosrsrr** [comment]
Could you tell me how to add?
