### ISSUE TITLE
Temperature Changing To Quickly (MC 1.19.2)

### ISSUE THREAD

**Issue by doej26937** [Glitchfiend/ToughAsNails#774]
### What's the issue you encountered?

My player starts to freeze/burn up very fast in the game?! Why? After 45-60 seconds of being on land my player needs to be submerged in water (same with freezing). How long should it actually take? Is there something wrong with the settings? It there a way I can change the time it takes to heat up / cool down?

Edit: Just found out that the temperature works good at night and in caves.
Edit 2: Temperature seems to work fine in most vanilla biomes but not 'Biomes O' Plenty' biomes.

**Edit 3: Everything is okay. I guess some of the biomes in the BOP mod are just really hot. Can someone please list the biomes that are the hottest/coldest?**

### How can the issue be reproduced?

1) Install mod 1.19.2.
2) Create a new world
3) Wait until Climate Clemency wares off
4) get into water until you see the temperature icon turn blue, (not the snowflake)
5) get out
6) count the time until you start burning up.

### Mod Version

8.0.0.78

**Comment by Adubbz** [comment]
Temperature changes are intentionally very fast now compared to 1.12. The delays are configurable in the serverconfig file
