### ISSUE TITLE
Color on leaf armor doesnt stay what it is supposed to be once equipped

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/ToughAsNails#775]
### What's the issue you encountered?

https://streamable.com/uhlg3f

### How can the issue be reproduced?

wear colored leaf armor, see color change like in video

### Mod Version

8.0.0.78

**Comment by Forstride** [comment]
So, the way leaf armor works is that it automatically changes the color to match the biome you're in.  It's technically dyeable due to how color changing armor works, and there's no way for us to disable that and still have the biome coloring work.
