### ISSUE TITLE
No purified water

### ISSUE THREAD

**Issue by TheDukinator0** [Glitchfiend/ToughAsNails#776]
### What's the issue you encountered?

im using 1.18 and i know that it says only do bugs from 1.19 but the game wont let me purify water and several other recipes are also missing, im confused and kinda need help with this
![Screenshot from 2022-12-28 21-28-40](https://user-images.githubusercontent.com/121592932/209899571-44f2c871-9682-4392-b13f-e1090e58eac4.png)
![Screenshot from 2022-12-28 21-28-12](https://user-images.githubusercontent.com/121592932/209899572-a2369721-7cf6-438f-a9ea-3e7782f9d651.png)

### How can the issue be reproduced?

i dont know

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
Water is purified using a water purifier now. Coils were intentionally removed in favour of heating/cooling blocks

**Comment by TheDukinator0** [comment]
they arent there eather

**Comment by TheDukinator0** [comment]
in fact, purified water isnt in the game right now

**Comment by TheDukinator0** [comment]
o wait wat

**Comment by TheDukinator0** [comment]
that wasnt there before i swear

**Comment by TheDukinator0** [comment]
sorry for bothering you
