### ISSUE TITLE
[Suggestion] Temperature and thirst management and expansion

### ISSUE THREAD

**Issue by AlienXtream** [Glitchfiend/ToughAsNails#777]
### Overview

currently its quite trivial to warm up a space. just plop down a campfire or two. inversely its quite a problem to cool one down. while this does mirror real life and entropy its not so good for gameplay mechanics. especially if you get stuck with a hot biome of the start. i propose some notable additions and changes to accomidate a more forgiving (but still quite challenging) gameplay experience by putting temperature control more within the players hands. 

1. the first and simplest improvement is a simple "ice fan". similar to how a campfire warms an area the "ice fan" would cool it, requiring a supply of either ice, packed ice or blue ice (lowering the temperature by one for each respective tier) in the configured "temperature radius". additionally a config for custom "hot/cold" sources for players to add their own (for example one may wish to make a decorative fan actually cool a small area).

2. slightly harder but something that may be nice is mod compatability. create for instance has encased fans that can heat/cool things. making use of that to both serve as a useful tool as well as a slight hazard in large processing facilities. 

3. another option i would like to see is some user defined overrides for both dimensions and biomes. dimension overrides take priority over biomes. these would either set or modify the values depending on if its assigned a "SET" or "ADD" prefix (if this is already possible with datapacks then some documentation would be nice 😊). these overrides would ONLY affect the player temperature calculation and have no affect on the actual temperature a dimension/biome has. 

4. hunger and thirst affects player tollorences. as a consession to help players (especially early game) deal with temperature biome temperature should not cause freezing/burning at high hunger/thurst values (>75-80% full) at the cost of slightly higher exhaustion respectively, emulating the fact that cool climats tend to use more energy to keep warm and warm climats your body uses wanter to cool itself.

5. acclimatization. sleeping in a hot/cold biome gives a buff to the palyer for 10 mins (minecraft "day". morn to night) for +1 tolarence to that climate and -1 for the inverse, making living in those environments more practical. optional perminent buff based off world spawn biome or random per player (config)

6. brutal nether/end temperatures. nether/end are perpetually schorching/freezing and require active measures to survive. 

7. datapack/config compatible armour effects and possigbly silent's gear armour compat?

8. sunlight bonus. standing in "direct sun" (sky exposure, like undead burning) when the weather is clear tips desert temperature over the edge. shade or waring a straw hat (new item) prevents this.

9. physical activity. running for a while warms you up. good in cooler places, not so much in the desert. best walk, carry lots of water and ware a hat.

10. heatstroke and hypothermia. spending too long unprotected in "hot" places gives the player heatstroke. like a combination of weakness, nausia and thurst. hypothermia is the inverse. spending too long in the cold/snow without protection makes you lathargic and vulnerable with aspects of slowness, mining fatigue and weakness. 

11. temperature healing detriment. being warm or cool slows health regeneration. 

12. sunburn and frostbite. spending too long in the sun can cause sunburn (regardless of temperature) and too long in snow can cause frostbite. both are the same but for "cold" and "hot" sources respectively. makes the player take more damage (sunburn hurts...). they are prevented with sunscreen (bottle, milk, clay and honeycomb. shapless. lasts a day or until you enter water) or any boots that have the same affect as leather boots on powder snow. 

13. airconditioner/heatpump. late game, reqpiring blaze rods and chorus fruit (to heat up or "teleport" away heat). actively maintains a tempereture in a "room" (enclosed space up to 16x16x16 area). requires to be placed in a wall/window with the vent facing in and the exhaust fan out. consumes blaze powder to warm and ice to cool. target temperature is defined by redstone signal strength, with 7 being neutral temperature, closer to 1 being colder, to 15 being hotter and 0 being off. optional FE requirement instead of blaze powder/Ice

14. Thermostat. similar to daylight sensor it gives a signal strength based off the temperature where its placed. can be set to cold sensing or hot sensing where the furthur from neutral it is in the respective direction the stronger the signal. useful for only turning on an ice fan when its actually hot, among other automation stuff.

15. thermometer. hand held device that tells you what temperature it is specifically. (-4 to 4)

16 "weather" events. heatwaves and cold fronts that can occur (with seasonal integration perhaps). during these events, while possible to go out, it is best to remain indoors in the cool/warm. their affects should be fairly obvious, raising/lowering the temperature to their respective extremes. this only applies in the overworld. both accompanied by (optional) shaders, with a heat haze and dense "snowy" fog (no actual snow. jsut the show visuals)

### Why would this feature be useful?

i realise there's quite a lot there and some similar things may be planned but i thought i'd share some of my experiences so far and thoughts i've had on how to make things both more brutal at the extremes and for the unprepaired whilst also giving players ways to manage or even negate the effects with effort and some upkeep. at present there is no (obvious) way to control or manage temperature for an area and so your just stuck with whatever the biome is. by expanding upon both preventative and active control options the player is therefore able to manipulate the environment in localised areas to an extent, making exploration less of a punishment and more of a fun challenge of preparation whilst also raising the risks to those who to not take care to do so. these are just ideas intended to perhaps provide inspiration for your own interpretations of such mechanics. i do not presume to tell you what to do with your own mod, only provide feedback on my PERSONAL thoughts on the subject(s). 😊

**Comment by Drezkil** [comment]
Shut up and take my money

**Comment by PickyPixelStudio** [comment]
Really like some idea here

**Comment by Forstride** [comment]
There's way too much in this single post for me to address every individual thing, but yeah...Some of these already were features in the mod, were improved since this issue was opened (Re-added Thermometer in 1.20.4), won't be implemented at all (Acclimatization, sprinting adding heat, hunger/thirst affecting temperature, etc.), or are out of scope for the mod (Weather events for example).
