### ISSUE TITLE
[Feature Request] Disable "Thirst" Status Effect in config

### ISSUE THREAD

**Issue by JohnGhostly** [Glitchfiend/ToughAsNails#779]
### Overview

Add the ability to disable the "Thirst" Status effect from drinking anything above dirty water in the config file.

### Why would this feature be useful?

Would be nice for a *slightly* more casual experience.

**Comment by Rubickevich** [comment]
Better to make people able to change the duration of the effect. I want it just the other way around - so you will be sick for a very long time after drinking bad water.

**Comment by Forstride** [comment]
Poison chance is defined by item tags, so you can override the tags if you don't want that.
