### ISSUE TITLE
Server won't start up with this mod

### ISSUE THREAD

**Issue by BlissFate** [Glitchfiend/ToughAsNails#783]
### What's the issue you encountered?

When placing this mod into my server the server will not start up at all. I have tried multiple configuration mods and tried installing the additional downloads to see if there is any way to use it. 

### How can the issue be reproduced?

For me just placing the mod into the "mods" folder and starting up the server. The server begins to start but soon after its build up and before world generation the server stops.

### Logs

[04Feb2023 00:44:51.374] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ 	Tough As Nails (toughasnails) has failed to load correctly

### Mod Version

1.19.3

**Comment by Adubbz** [comment]
You need to provide a proper log file.

**Comment by KennyKerner** [comment]
Hi there! other user with the same problem here, here's my log. This is an aternos server btw


// Hi. I'm Minecraft, and I'm a crashaholic.
--
3 |  
4 | Time: 2023-02-04 16:01:19
5 | Description: Mod loading error has occurred
6 |  
7 | java.lang.Exception: Mod Loading has failed
8 | at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.3-44.1.8-universal.jar%23154!/:?] {re:classloading}
9 | at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.3-44.1.8-universal.jar%23154!/:?] {re:classloading}
10 | at net.minecraft.server.Main.main(Main.java:114) ~[server-1.19.3-20221207.122022-srg.jar%23149!/:?] {re:classloading}
11 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
12 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
13 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
14 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
15 | at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.3-44.1.8.jar%2368!/:?] {}
16 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2355!/:?] {}
17 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2355!/:?] {}
18 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2355!/:?] {}
19 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2355!/:?] {}
20 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2355!/:?] {}
21 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2355!/:?] {}
22 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2355!/:?] {}
23 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
24 |  
25 |  
26 | A detailed walkthrough of the error, its code path and all known details is as follows:
27 | ---------------------------------------------------------------------------------------
28 |  
29 | -- Head --
30 | Thread: main
31 | Stacktrace:
32 | at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.3-44.1.8.jar%2368!/:1.0] {}
33 | -- MOD toughasnails --
34 | Details:
35 | Mod File: /server/mods/ToughAsNails-1.19.3-8.1.0.87.jar
36 | Failure message: Tough As Nails (toughasnails) has failed to load correctly
37 | java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent for invalid dist DEDICATED_SERVER
38 | Mod Version: 0.0NONE
39 | Mod Issue URL: https://github.com/Glitchfiend/ToughAsNails/issues
40 | Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent for invalid dist DEDICATED_SERVER
41 | Stacktrace:
42 | at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.3-44.1.8.jar%2368!/:1.0] {}
43 | at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2355!/:?] {}
44 | at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2355!/:?] {}
45 | at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2355!/:?] {}
46 | at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?] {}
47 | at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
48 | at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?] {}
49 | at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
50 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?] {}
51 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
52 | at java.lang.Class.forName0(Native Method) ~[?:?] {}
53 | at java.lang.Class.forName(Unknown Source) ~[?:?] {}
54 | at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
55 | at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
56 | at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
57 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
58 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.8.jar%23150!/:?] {}
59 | at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
60 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
61 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
62 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
63 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
64 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
65 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
66 |  
67 |  
68 | -- System Details --
69 | Details:
70 | Minecraft Version: 1.19.3
71 | Minecraft Version ID: 1.19.3
72 | Operating System: Linux (amd64) version 5.4.0-110-generic
73 | Java Version: 17.0.4.1, Eclipse Adoptium
74 | Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
75 | Memory: 691800064 bytes (659 MiB) / 1205862400 bytes (1150 MiB) up to 2411724800 bytes (2300 MiB)
76 | CPUs: 3
77 | Processor Vendor: AuthenticAMD
78 | Processor Name: AMD EPYC 7402P 24-Core Processor
79 | Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
80 | Microarchitecture: Zen 2
81 | Frequency (GHz): -0.00
82 | Number of physical packages: 1
83 | Number of physical CPUs: 24
84 | Number of logical CPUs: 48
85 | Graphics card #0 name: unknown
86 | Graphics card #0 vendor: unknown
87 | Graphics card #0 VRAM (MB): 0.00
88 | Graphics card #0 deviceId: unknown
89 | Graphics card #0 versionInfo: unknown
90 | Virtual memory max (MB): 129864.22
91 | Virtual memory used (MB): 161257.47
92 | Swap memory total (MB): 1024.00
93 | Swap memory used (MB): 924.24
94 | JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx2300M -Xms1150M
95 | ModLauncher: 10.0.8+10.0.8+main.0ef7e830
96 | ModLauncher launch target: forgeserver
97 | ModLauncher naming: srg
98 | ModLauncher services:
99 | mixin-0.8.5.jar mixin PLUGINSERVICE
100 | eventbus-6.0.3.jar eventbus PLUGINSERVICE
101 | fmlloader-1.19.3-44.1.8.jar slf4jfixer PLUGINSERVICE
102 | fmlloader-1.19.3-44.1.8.jar object_holder_definalize PLUGINSERVICE
103 | fmlloader-1.19.3-44.1.8.jar runtime_enum_extender PLUGINSERVICE
104 | fmlloader-1.19.3-44.1.8.jar capability_token_subclass PLUGINSERVICE
105 | accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
106 | fmlloader-1.19.3-44.1.8.jar runtimedistcleaner PLUGINSERVICE
107 | modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE
108 | modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE
109 | FML Language Providers:
110 | minecraft@1.0
111 | lowcodefml@null
112 | javafml@null
113 | Mod List:
114 | server-1.19.3-20221207.122022-srg.jar             \|Minecraft                     \|minecraft                     \|1.19.3              \|COMMON_SET\|Manifest: NOSIGNATURE
115 | mcw-bridges-2.0.6-mc1.19.3forge.jar               \|Macaw's Bridges               \|mcwbridges                    \|2.0.6               \|COMMON_SET\|Manifest: NOSIGNATURE
116 | doubledoors-1.19.3-4.1.jar                        \|Double Doors                  \|doubledoors                   \|4.1                 \|COMMON_SET\|Manifest: NOSIGNATURE
117 | TerraBlender-forge-1.19.3-2.1.0.139.jar           \|TerraBlender                  \|terrablender                  \|2.1.0.139           \|COMMON_SET\|Manifest: NOSIGNATURE
118 | BiomesOPlenty-1.19.3-17.2.0.501.jar               \|Biomes O' Plenty              \|biomesoplenty                 \|17.2.0.501          \|COMMON_SET\|Manifest: NOSIGNATURE
119 | botarium-forge-1.19.3-2.0.4.jar                   \|Botarium                      \|botarium                      \|2.0.4               \|COMMON_SET\|Manifest: NOSIGNATURE
120 | mcw-trapdoors-1.0.8-mc1.19.3forge.jar             \|Macaw's Trapdoors             \|mcwtrpdoors                   \|1.0.8               \|COMMON_SET\|Manifest: NOSIGNATURE
121 | mcw-fences-1.0.7-mc1.19.3forge.jar                \|Macaw's Fences and Walls      \|mcwfences                     \|1.0.7               \|COMMON_SET\|Manifest: NOSIGNATURE
122 | resourcefulconfig-forge-1.19.3-1.1.2.jar          \|Resourcefulconfig             \|resourcefulconfig             \|1.1.2               \|COMMON_SET\|Manifest: NOSIGNATURE
123 | mcwfencesbop-1.19.3-1.0.jar                       \|Macaw's Fences - BOP          \|mcwfencesbop                  \|1.19.3-1.0          \|COMMON_SET\|Manifest: NOSIGNATURE
124 | mcw-windows-2.1.1-mc1.19.3forge.jar               \|Macaw's Windows               \|mcwwindows                    \|2.1.1               \|COMMON_SET\|Manifest: NOSIGNATURE
125 | ecologics-forge-1.19.3-2.1.12.jar                 \|Ecologics                     \|ecologics                     \|2.1.12              \|COMMON_SET\|Manifest: NOSIGNATURE
126 | collective-1.19.3-6.43.jar                        \|Collective                    \|collective                    \|6.43                \|COMMON_SET\|Manifest: NOSIGNATURE
127 | SereneSeasons-1.19.3-8.2.0.27.jar                 \|Serene Seasons                \|sereneseasons                 \|0.0NONE             \|COMMON_SET\|Manifest: NOSIGNATURE
128 | ToughAsNails-1.19.3-8.1.0.87.jar                  \|Tough As Nails                \|toughasnails                  \|0.0NONE             \|ERROR     \|Manifest: NOSIGNATURE
129 | [1.19.3]-Epic-Knights-Armor-and-Weapons-6.7v.jar  \|Epic Knights: Armor and Weapon\|magistuarmory                 \|1.0                 \|COMMON_SET\|Manifest: NOSIGNATURE
130 | resourcefullib-1.2.7.jar                          \|Resourceful Lib               \|resourcefullib                \|1.2.7               \|COMMON_SET\|Manifest: NOSIGNATURE
131 | mcw-roofs-2.2.2-mc1.19.3forge.jar                 \|Macaw's Roofs                 \|mcwroofs                      \|2.2.2               \|COMMON_SET\|Manifest: NOSIGNATURE
132 | mcw-doors-1.0.7forge-mc1.19.3.jar                 \|Macaw's Doors                 \|mcwdoors                      \|1.0.7               \|COMMON_SET\|Manifest: NOSIGNATURE
133 | architectury-7.0.66-forge.jar                     \|Architectury                  \|architectury                  \|7.0.66              \|COMMON_SET\|Manifest: NOSIGNATURE
134 | macawsroofsbop-1.19.3-1.1.jar                     \|Macaw's Roofs - BOP           \|macawsroofsbop                \|1.19.3-1.1          \|COMMON_SET\|Manifest: NOSIGNATURE
135 | cloth-config-9.0.94-forge.jar                     \|Cloth Config v9 API           \|cloth_config                  \|9.0.94              \|COMMON_SET\|Manifest: NOSIGNATURE
136 | forge-1.19.3-44.1.8-universal.jar                 \|Forge                         \|forge                         \|44.1.8              \|COMMON_SET\|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
137 | mcw-paths-1.0.2forge-mc1.19.3.jar                 \|Macaw's Paths and Pavings     \|mcwpaths                      \|1.0.2               \|COMMON_SET\|Manifest: NOSIGNATURE
138 | mcw-lights-1.0.5-mc1.19.3forge.jar                \|Macaw's Lights and Lamps      \|mcwlights                     \|1.0.5               \|COMMON_SET\|Manifest: NOSIGNATURE
139 | ad_astra-forge-1.19.3-1.13.3.jar                  \|Ad Astra!                     \|ad_astra                      \|1.13.3              \|COMMON_SET\|Manifest: NOSIGNATURE
140 | Crash Report UUID: cb0d2a1e-49be-4867-a449-d76a9b20c82c
141 | FML: 44.1
142 | Forge: net.minecraftforge:44.1.8


</body>
</html>// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 202[3](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L3)-02-0[4](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L4) 16:01:19
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:[5](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L5)5) ~[forge-1.19.3-44.1.8-universal.jar%23154!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.3-44.1.8-universal.jar%23154!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:114) ~[server-1.19.3-20221207.122022-srg.jar%23149!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.3-44.1.8.jar%23[6](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L6)8!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:[7](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L7)1) ~[modlauncher-10.0.[8](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L8).jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.1[9](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L9).3-44.1.8.jar%2368!/:1.0] {}
-- MOD toughasnails --
Details:
	Mod File: /server/mods/ToughAsNails-1.19.3-8.1.0.87.jar
	Failure message: Tough As Nails (toughasnails) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent for invalid dist DEDICATED_SERVER
	Mod Version: 0.0NONE
	Mod Issue URL: https://github.com/Glitchfiend/ToughAsNails/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.3-44.1.8.jar%2368!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-[10](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L10).0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:[11](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L11)3) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.3-44.1.8.jar%23151!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:[12](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L12)1) ~[fmlcore-1.19.3-44.1.8.jar%23150!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 5.4.0-110-generic
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 691800064 bytes (659 MiB) / 1205862400 bytes (1150 MiB) up to 2411724800 bytes (2300 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7402P 24-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 48
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129864.22
	Virtual memory used (MB): 161257.47
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 924.24
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx2300M -Xms1150M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.1.8.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.8.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.1.8.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.1.8.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.8.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |COMMON_SET|Manifest: NOSIGNATURE
		mcw-bridges-2.0.6-mc1.19.3forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		doubledoors-1.19.3-4.1.jar                        |Double Doors                  |doubledoors                   |4.1                 |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.3-2.1.0.[13](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L13)9.jar           |TerraBlender                  |terrablender                  |2.1.0.139           |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.3-[17](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L17).2.0.501.jar               |Biomes O' Plenty              |biomesoplenty                 |17.2.0.501          |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.[19](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L19).3-2.0.4.jar                   |Botarium                      |botarium                      |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.8-mc1.19.3forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19.3forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.3-1.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcwfencesbop-1.19.3-1.0.jar                       |Macaw's Fences - BOP          |mcwfencesbop                  |1.19.3-1.0          |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.1.1-mc1.19.3forge.jar               |Macaw's Windows               |mcwwindows                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		ecologics-forge-1.19.3-2.1.12.jar                 |Ecologics                     |ecologics                     |2.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.3-6.43.jar                        |Collective                    |collective                    |6.43                |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.19.3-8.2.0.27.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		ToughAsNails-1.19.3-8.1.0.87.jar                  |Tough As Nails                |toughasnails                  |0.0NONE             |ERROR     |Manifest: NOSIGNATURE
		[1.19.3]-Epic-Knights-Armor-and-Weapons-6.7v.jar  |Epic Knights: Armor and Weapon|magistuarmory                 |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-1.2.7.jar                          |Resourceful Lib               |resourcefullib                |1.2.7               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-roofs-2.2.2-mc1.19.3forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.0.7forge-mc1.19.3.jar                 |Macaw's Doors                 |mcwdoors                      |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-7.0.66-forge.jar                     |Architectury                  |architectury                  |7.0.66              |COMMON_SET|Manifest: NOSIGNATURE
		macawsroofsbop-1.19.3-1.1.jar                     |Macaw's Roofs - BOP           |macawsroofsbop                |1.19.3-1.1          |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-9.0.94-forge.jar                     |Cloth Config v9 API           |cloth_config                  |9.0.94              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.3-44.1.8-universal.jar                 |Forge                         |forge                         |44.1.8              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mcw-paths-1.0.2forge-mc1.19.3.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.5-mc1.19.3forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		ad_astra-forge-1.19.3-1.13.3.jar                  |Ad Astra!                     |ad_astra                      |1.13.3              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: cb0d2a1e-49be-4867-a449-d76a9b[20](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L20)c82c
	FML: [44](https://aternos.org/files/crash-reports/crash-2023-02-04_16.01.19-fml.txt#L44).1
	Forge: net.minecraftforge:44.1.8

**Comment by BlissFate** [comment]
> You need to provide a proper log file. 

Not sure where to go to provide that info

**Comment by Adubbz** [comment]
This has been fixed now. Information regarding how to obtain log files is provided when creating a new issue.
