### ISSUE TITLE
Long freeze protection overwriting other potions

### ISSUE THREAD

**Issue by Otzelix** [Glitchfiend/ToughAsNails#785]
### What's the issue you encountered?

long potions get  transformed into a long freeze potions.

this happens in the brewing stand, but also in the basin of the create mod, if you are using it to brew potions

### How can the issue be reproduced?

if you add redstone to any already extended potion, it will be transformed to a long freeze protection potion.

### Mod Version

1.18.2-7.0.0.69

**Comment by Adubbz** [comment]
This has already been fixed in newer mod versions
