### ISSUE TITLE
Thirst and Healing

### ISSUE THREAD

**Issue by DragonGold121** [Glitchfiend/ToughAsNails#786]
### Overview

I have a gripe and that is it's really annoying to heal because your thirst depletes like hunger but thirst doesn't have saturation
so you have to stand by a source and constantly drink.
I have two solutions.
1. Let us over drink to have extra water in reserve (i.e Thirst saturation.)
2. Lower the required amount of thirst to heal to something like half full.

### Why would this feature be useful?

It would make healing less tedious

**Comment by Adubbz** [comment]
Thirst saturation (hydration) already exists. Drinking with your hands intentionally has no hydration associated with it to discourage doing this. Purified water/juices have greater hydration values.

**Comment by Forstride** [comment]
To clarify, we don't support hand drinking as a balanced gameplay feature.  The option is only there because people complained and wanted an option to re-enable it.

**Comment by DragonGold121** [comment]
> 

Could we get the option to see this thirst saturation?
