### ISSUE TITLE
BiSect Hosting mismatch with Tough As Nails

### ISSUE THREAD

**Issue by AnsonTrang** [Glitchfiend/ToughAsNails#787]
### What's the issue you encountered?

Client has Tough As Nails, server has Tough as Nails on Bisect Hosting.  (Forge version 43.1.1 for Create mod + Optifine compatibility)

Tough as nails is compared to 0.0 none in the "Connection Closed" screen.

### How can the issue be reproduced?

Create a profile for 1.19.2 on CurseForge.

Set Forge Version to 43.1.1

Download Tough As Nails on client.

Download Tough as Nails on Server.

Run the game and connect to server.

### Mod Version

1.19.2

**Comment by Adubbz** [comment]
The mod version number wasn't set correctly in older versions, which has been addressed
