### ISSUE TITLE
Config doesn't apply to custom biomes

### ISSUE THREAD

**Issue by G-Stav** [Glitchfiend/ToughAsNails#788]
### What's the issue you encountered?

In a pack I'm making I noticed that in the custom biome I created it doesn't respect the config and you will still get water from water sources instead of dirty water.

### How can the issue be reproduced?

Have a custom biome created with datapacks, set config to [[biome_options.biome_water_entries]]		location = "datapack:biomename"		type = "DIRTY", use bottle on water source, get water bottle instead of dirty water bottle.

### Mod Version

8.0.0.78

**Comment by Adubbz** [comment]
This should be fixed in newer versions which use tags instead of the config files
