### ISSUE TITLE
Hand drink (addition in a config file, not in serverconfig)

### ISSUE THREAD

**Issue by moayad155** [Glitchfiend/ToughAsNails#790]
### Overview

Hand drink (addition in a config file, not in serverconfig)

It's annoying to drink water from bottles or from a canteen because it takes time when you're drinking

### Why would this feature be useful?

It will be useful for anyone who wants to use it in a modpack

Also for those who want the feature to be activated without activating it manually when creating the world

**Comment by Adubbz** [comment]
You can already enable the option by default using the defaultconfigs folder. Closing this given the option already exists.
