### ISSUE TITLE
Where are the thermal coils

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#791]
### Overview

Can you please add thermal coils, powered by coal and water

### Why would this feature be useful?

Because it would allow you to wear good armor in a extreme climate instead of wearing 2 full points of armor

**Comment by Forstride** [comment]
We don't have any plans to re-add them as they were very laggy and there's likely no better way to implement them.  Use campfires/soul campfires for long-term heating/cooling.
