### ISSUE TITLE
Missing commas in ru_ru.json translation

### ISSUE THREAD

**Issue by AltezaR** [Glitchfiend/ToughAsNails#792]
### What's the issue you encountered?

Missing commas in ru_ru.json translation:
  "block.toughasnails.rain_collector": "Дождесборник"

  "item.toughasnails.melon_juice": "Арбузный сок"
  "item.toughasnails.pumpkin_juice": "Тыквенный сок"
  "item.toughasnails.sweet_berry_juice": "Сок из сладких ягод"
  "item.toughasnails.wool_boots": "Шерстяные ботинки"
  "item.toughasnails.wool_chestplate": "Шерстяная куртка"

  "item.minecraft.splash_potion.effect.ice_resistance": "Взрывное зелье лёдостойкости"

### How can the issue be reproduced?

If you switch to Russian, the mod will remain in English.

### Mod Version

1.19-8.0.0.78

**Comment by Forstride** [comment]
Fixed, but it'll have to be merged into the mod manually at some point
