### ISSUE TITLE
Can u add the hand drinking set off to the config file? 

### ISSUE THREAD

**Issue by Adiwangzhongwang** [Glitchfiend/ToughAsNails#793]
### What's the issue you encountered?

Have to set hand drinking true every time before start a new game in the serverconfig in save folder.
And sometime it doesn't work，maybe same bug? 

### How can the issue be reproduced?

enable hand drinking ,and it does't work.

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
You can already do this by using Forge's defaultconfigs folder.
