### ISSUE TITLE
what heats me or cools me?

### ISSUE THREAD

**Issue by Cactunimations** [Glitchfiend/ToughAsNails#794]
### Overview

I tried looking in the GitHub Wiki but there is nothing there, I tried looking in YouTube videos and found nothing there either, the only thing I know is that wool and leaf armor makes you immune to temperatures. Nothing else. I don't know the rate in which a block heats/cools you and if the GitHub wiki was finished, it would be great.

### Why would this feature be useful?

Help new players (like me) find out what helps you survive and how to use the mod.

**Comment by Adubbz** [comment]
Tooltips have already been added to new versions of the mod which indicate which blocks heat or cool you
