### ISSUE TITLE
Compatibility of juices from other mods ex(Farmers Delight...)

### ISSUE THREAD

**Issue by joaoed17** [Glitchfiend/ToughAsNails#795]
### Overview

Will it be possible to add a means of configuration to add compatibility of juices from other mods with the thirst of the mod?

### Why would this feature be useful?

As an example of farmer's delight, they add very good juices, with the same style as TAN's juices, but when you drink it, it doesn't cure your thirst, it gets a little boring

**Comment by Forstride** [comment]
This is already possible to do with datapacks (An example datapack can be found on our Discord server), and other mods can add native support if they want to.  It's not up to us to maintain it.
