### ISSUE TITLE
crash when clicking the config button in configured mod

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Glitchfiend/ToughAsNails#801]
### What's the issue you encountered?

clicking the biome entrees config button in configured mod

### How can the issue be reproduced?

clicking the biome entrees config button in configured mod

### Logs

https://gist.github.com/SonicTheHedgehog58987276/dbbc80724af250fd8d01f50c240db6e9#file-latest-log

### Mod Version

8.2.0.90

### Additional information

[crash-2023-06-30_20.28.10-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/11923817/crash-2023-06-30_20.28.10-client.txt)

**Comment by Adubbz** [comment]
This is an issue that they would need to resolve on their side. We have no control over how their code works.
