### ISSUE TITLE
Heaters and coolers

### ISSUE THREAD

**Issue by Thunderrock424242** [Glitchfiend/ToughAsNails#805]
### Overview

so there is a mod simple difficulty that has heaters and coolers but they are only on 1.12.2 and you guys are on 1.20.1 already so it would be cool to have something like that. just in case people don't want it maybe make a config for it like if you turn it off you can't craft it or something.

### Why would this feature be useful?

it would be usefull to have during the long winters and the coolers during the long summers.

**Comment by DerpSquad1O1** [comment]
Yeah, I've been searching across the internet for heating machines for hours. I second this for 1.20 and 1.19 if that's possible.

**Comment by PickyPixelStudio** [comment]
Why not just using in game block? Lava, ice?!
