### ISSUE TITLE
Enchantment that Regulates Temperature

### ISSUE THREAD

**Issue by leo-valadao** [Glitchfiend/ToughAsNails#807]
### Overview

Add 3 types of enchantment: 

- One that cools down the body, so you dont need to wear the weak leaf armor on nether;
- One that heats up the body, so you dont neet to wear the wool armor on ice biomes;
- And a treasure enchantmentthat regulates the body temperature to neutral, so when your are on cold or hot environments, you dont get affected by the body temperature.

### Why would this feature be useful?

Would make the mod more useful on the nether or cold biomes without needing to create a campfire every 30 blocks or using bad armors, like wool or leaf armors

**Comment by Forstride** [comment]
>And a treasure enchantmentthat regulates the body temperature to neutral

That already exists.  It's called Thermal Tuning
