### ISSUE TITLE
getDryTicks() because "cap" is null

### ISSUE THREAD

**Issue by Xing-C** [Glitchfiend/ToughAsNails#808]
### What's the issue you encountered?

Create a world, jump into magma, and collapse upon death

### How can the issue be reproduced?

Create a world, jump into magma, and collapse upon death

### Logs

<script src="https://gist.github.com/Xing-C/eaf1ad1e9b1045f5079561c8515d96a4.js"></script>

### Mod Version

9.0.0.95

**Comment by Xing-C** [comment]
https://gist.github.com/Xing-C/eaf1ad1e9b1045f5079561c8515d96a4

**Comment by Adubbz** [comment]
Gonna ping @Favouriteless for this as they added this code

**Comment by Favouriteless** [comment]
Should be fixed in the PR I just submitted. Unsure how the cap is null at this point, guess the tick event runs before caps are attached or something.
