### ISSUE TITLE
Coils - Fuel or Energy?

### ISSUE THREAD

**Issue by AlgorithmX2** [Glitchfiend/ToughAsNails#81]
Would be neat if there was an option to power coils with one of the various energy systems, or maybe just slower burning furnace fuels to power them?

Just a thought, I look forward to trying out the mod though, it looks neat.

**Comment by Forstride** [comment]
I guess having to use fuel for it could be interesting, although I think it might make it more annoying than it's worth.

**Comment by AlgorithmX2** [comment]
Generally speaking it would probably make more sense for some low cost energy drain from a power grid like 1rf/eu per 20 ticks or something...

but if the burn was slow enough I don't know.... I guess the main problem with it is if you have several. you have to go recharge each one separately... but I guess you could also use a pipe mod to supply them from a central "wood pile"

If your worried about the hassle making some central way to supply the fuel could work as well. Like have a Coil Furnace.. that affects all the coils near by. Gives the heat a cost, but not as big a hassle.

**Comment by Forstride** [comment]
Ehh.  I don't want to make it too tech-y, or have it basically rely on tech mods to be viable.  If anything, it'd just be furnace fuels for the heating coil, and ice/snowballs/etc. for the cooling coil, but having it use them up slowly so it's not something you need to constantly fill up.

**Comment by AlgorithmX2** [comment]
Sure I can understand that, do you think something like a central "Coil Furnace" would make more sense then providing the fuel to each coil individually? or you just think that burning them at each coil slowly enough would work?

**Comment by Forstride** [comment]
Yeah, I feel like having an additional block required would just make things a bit more complex than they need to be.  Anyway, it'd probably be a while before this ever gets added.  Adubbz is the lead programmer, but he's very busy with school, and I don't think I'd be able to do GUI stuff myself.

**Comment by WolfieWaffle** [comment]
Would you add a config option to disable to fuel cost, as well as option RF support?
