### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by Demacrada** [Glitchfiend/ToughAsNails#810]
### What's the issue you encountered?

Water Purifier not working. I put the charcoal with the water bottle and nothing happend.

### How can the issue be reproduced?

Create the water purifier.
Grab some water with the canteen or bottles.
Put the charcoal inside the purifier
Put the bottles or canteen
Nothing is happening.

### Mod Version

1.20.2

**Comment by Adubbz** [comment]
I can't reproduce this. Please provide logs.
![image](https://github.com/Glitchfiend/ToughAsNails/assets/2765389/6c094e65-b5dd-47bc-b1ed-906f40611d53)

**Comment by Demacrada** [comment]
Then its has to be some incompatibility with other mod. This one doesnt have any requeriment right?

**Comment by Adubbz** [comment]
This actually appears to be a Forge bug that doesn't occur in development environments. I've added a workaround which should fix this.
