### ISSUE TITLE
Does version 1.16.5 fix this bug?

### ISSUE THREAD

**Issue by yuankun1** [Glitchfiend/ToughAsNails#811]
### What's the issue you encountered?

If the old version 1.16.5 update is dropped, I can only abandon the mod
I don't know if your error code is causing the card thread to drop by 15 tps
Error Reporting https://paste.ubuntu.com/p/3vzgwQTcP3/
Because the catserver kernel is not compatible and does not support closed-source modules

### How can the issue be reproduced?

After restarting the server, there is a chance that two players will enter the server at the same time
After restarting the server, two players enter the server at the same time
Or a new player entering the server will also have a chance of such an error

### Logs

https://paste.ubuntu.com/p/X9fF83ft4Y/

### Mod Version

1.16.5

**Comment by Adubbz** [comment]
No, 1.16.5 is no longer supported.
