### ISSUE TITLE
MY SERVER JUST CRASHED AND IT WONT TURN ON EVEN WHEN I COMPLEATLY REINSTALEDT THE SERVER 

### ISSUE THREAD

**Issue by matesaman9910** [Glitchfiend/ToughAsNails#812]
### What's the issue you encountered?

from day to day i tryed lunching the server but it just crashed i tryied deliting it and starting a new one but it crashes too 
WARNING I AM FROM CZECHIA MY ENGLISH IS TERRIBLE.

### How can the issue be reproduced?

i just started the server.

### Logs

https://mclo.gs/PMabJ0s

### Mod Version

1.20.1

### Additional information

![image](https://github.com/Glitchfiend/ToughAsNails/assets/100013611/d614609c-15eb-45a8-9eb9-991c8f39ac1a)
![image](https://github.com/Glitchfiend/ToughAsNails/assets/100013611/b83392b8-5c5a-4ea7-93a8-19a21128ebf6)
![image](https://github.com/Glitchfiend/ToughAsNails/assets/100013611/ed095f21-9611-4a08-8e1d-b33ddb298ba6)

**Comment by Adubbz** [comment]
You've listed 1.20.1 but are actually using 1.20.2. Anyway, this is due to a Forge change. It should be fixed now.

**Comment by matesaman9910** [comment]
thanks for help i will try and start the server
