### ISSUE TITLE
Unable to turn on hand drinking

### ISSUE THREAD

**Issue by leftbones** [Glitchfiend/ToughAsNails#815]
### What's the issue you encountered?

Using Configured to edit the configs in game works for every other setting in this mod and other mods, but if I enable hand drinking and save, it is set back to "off"

### How can the issue be reproduced?

Set hand drinking to on in the config menu, then save and check again.

### Mod Version

0.0NONE

**Comment by Adubbz** [comment]
Hand-drinking should be enabled in the server config file located in your world folder via a text editor. What you're describing would be an issue with Configured, which isn't something we support.
