### ISSUE TITLE
Config options to add new blocks as heat sources?

### ISSUE THREAD

**Issue by Harrier69** [Glitchfiend/ToughAsNails#817]
### Overview

I've looked around and can't seem to find the option to do this anywhere, but for modpack authors and just players alike, a config option to simply add new blocks as heat/cold sources via their ID would be invaluable. 
I'm currently standing in the middle of my base surrounded by flames, but freezing to death because the firepits don't count as heat sources in the mod.

### Why would this feature be useful?

This would give the mod a whole lot more versatility in modpacks, because it means anyone could add their own blocks as sources of heat or cold where necessary just by using the config files rather than trying to find mods that add compatibility patches, or using awkward workarounds. 

If there is already a way of doing this that I've missed in this version, I'd love to hear it, but so far I haven't found one.

**Comment by Adubbz** [comment]
This can already be achieved via datapacks. An example one can be found on our Discord under pins.

**Comment by Harrier69** [comment]
Thank you! I'll look into it now!
