### ISSUE TITLE
I Cant Get Either Dirty Or Purified Water

### ISSUE THREAD

**Issue by SpacedTax** [Glitchfiend/ToughAsNails#820]
### What's the issue you encountered?

Just what the title says

### How can the issue be reproduced?

I tried to make purified water but i couldnt

### Mod Version

1.18.2-7.0.0.73

### Additional information

This Is On 1.18.2 And Not 1.19.+

**Comment by Forstride** [comment]
We don't support 1.18 (Or 1.19 for that matter...Our issue template needs to be updated), and even if we did, you haven't provided any actual info that we could even use to help you
