### ISSUE TITLE
drinking with empty hand crashes the game

### ISSUE THREAD

**Issue by ColdMt** [Glitchfiend/ToughAsNails#822]
### What's the issue you encountered?

trying to drink from a watersource with an empty hand crashes the game.

### How can the issue be reproduced?

drink water with an empty hand 

[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/13823540/latest.log)

### Logs

gist:563e364faebcbf9ce5e8976982449c48

### Mod Version

9.2.0.77

**Comment by ColdMt** [comment]
Did the gist thin wrong so here is the actual link.

https://gist.github.com/ColdMt/563e364faebcbf9ce5e8976982449c48

**Comment by Adubbz** [comment]
This should now be fixed with a GlitchCore update.
