### ISSUE TITLE
Crash when purifying 

### ISSUE THREAD

**Issue by ColdMt** [Glitchfiend/ToughAsNails#823]
### What's the issue you encountered?

Putting the coal and the water container/bottle in the purifier crashes the game. But on restart it still purifies. 

### How can the issue be reproduced?

see above.
Logs:
[latest.log](https://github.com/Glitchfiend/ToughAsNails/files/13850206/latest.log)

### Logs

https://gist.github.com/ColdMt/9d65bb8d3b4b6f62bf3ca5ce7564a4b3

### Mod Version

9.2.0.88

**Comment by Forstride** [comment]
This was already fixed.  Update to the latest beta of the mod
