### ISSUE TITLE
Optional Configuration about Hypothermia

### ISSUE THREAD

**Issue by Sandendaty** [Glitchfiend/ToughAsNails#826]
### Overview

Add a config option in the config file. If enable this option, players will not be frozen immediately when they fell into powder snow. They will be frozen nomally only if their body temperature decrease to the value that they get hypothermia.

### Why would this feature be useful?

The feature may be useful for some players or modpacks.

**Comment by Forstride** [comment]
Freezing immediately when in fallen snow is a vanilla feature (The entire frost effect is from vanilla, and we reuse it for when your body temperature is too low), and we don't want to interfere with that.

IIRC wearing any piece of leather armor prevents powder snow from freezing you.  Likewise, TAN's Ice Protection potion prevents it as well.
