### ISSUE TITLE
Game crashes when trying to load a world

### ISSUE THREAD

**Issue by TolliLion** [Glitchfiend/ToughAsNails#838]
### What's the issue you encountered?

Hi, my issue is the fact that every time I try to get into my new world, the game freezes and then crashes. This isn't just this mods problem, but it's happening with every mod from you guys. I have no idea why.

### How can the issue be reproduced?

Naturally, I first install the mod first with the requirements (I use the Fabric version.). I launch the game, and wait for the main menu to pop up, then I go to single-player, select the world I made (it's a new world I named “Test”) and play. Everything is loading just fine, until it says “joining world”. The loading takes a while, maybe about 30–40 seconds, and then it suddenly crashes.

### Logs

https://gist.github.com/TolliLion/01e0bebd8204492bd06e64f1b94b02a2

### Mod Version

9.2.0.142

### Additional information

I tested every mod I have to see which one is crashing the game, one by one. Here is a list of mods I use, maybe it will help:
-Fabric API
-Sodium
-Just Enough Items
-Architectury API
-MCA Reborn
-DynamicLights
-ModMenu
-VoxelMap

**Comment by Forstride** [comment]
Update TAN.  You're using a fairly outdated version
