### ISSUE TITLE
[Suggestion]Shelter Mechanic

### ISSUE THREAD

**Issue by CJL48** [Glitchfiend/ToughAsNails#84]
Currently, the temperature system is very well done, and fun to play with. However, I feel that it would both help immersion and early game survival (esp. in very cold/hot biomes) if taking shelter indoors or underground lessened the impact of the time, biome, and season modifiers on the player's temperature, with the exception of the nether. This would both reflect the use of shelter against extreme temperature in real life, and provide options for those who find themselves stuck in a very hot or very cold biome early game (ie. Only water/wool/campfires, no blaze or freeze rods).
However, I also recognize that this would be difficult to implement properly: simply taking cover under a tree should not provide the same amount of protection as a building or underground shelter. To this end, I suggest multiple degrees of shelter:
Shade- Overhead coverage only, mildly reduces effect of time and biome on temperature. This would be being under a tree or pavilion. Mostly good for protection from direct sunlight, and so should probably reduce heat slightly during the daytime (but have no effect during the night).
Shelter- Being underground or inside a building. This would be more difficult to handle, as the mod would have to be able to assess the area around a player. Larger buildings and caverns would pose their own problems, since at least some part of them would potentially exist in unloaded chunks. It would, however, also allow players to take shelter in structures/terrain generated by the game, as well as the ability to create temporary or permanent shelter to survive inhospitable areas or seasons, without needing to create coils. Note that even shelter would not completely eliminate the effects of time, season, and biome on temperature calculations.
Acclimatization- Same as current system- an area affected by coils.

One possible solution would be to use the 'sky light' level to determine how exposed a given position is: the higher the level of sky light, the more external temperature affects the player, though even at sky light zero these factors still have an effect. In addition, the factors would each be reduced to different degrees: time would be the factor most easily countered with shelter, season would be less effected, and biome would be affected the lease (though still enough to potentially be lifesaving).

I would appreciate any input from others they may wish to share.

**Comment by ghost** [comment]
I agree with this idea, and I would like to suggest that for deep cave systems, it should get warmer the closer you are to bedrock (as this is what happens when you go deep underground).  This would make cave exploration more difficult and require preparation, since you can't just jump into a y=12 level strip mine with proper hydration and cooling systems.
