### ISSUE TITLE
Leaf armor server bug

### ISSUE THREAD

**Issue by CalCrafter24** [Glitchfiend/ToughAsNails#846]
### What's the issue you encountered?

Whenever I try to craft leaf armor in my modded minecraft server, it kicks me out and whenever I try to rejoin it just says internal server error, the only way I can get back in is by uninstalling the mod from the server, starting it again, closing it and reinstalling the mod before starting again

### How can the issue be reproduced?

crating leaf armor in a modded aternos minecraft server, I suppose

### Logs

https://mclo.gs/b6kQyDn

### Mod Version

9.2.0.178

**Comment by Forstride** [comment]
The log is showing that you don't have the mod installed on your server

**Comment by CalCrafter24** [comment]
I had the same version on both the server and my version of minecraft, but noticed a newer version was available, downloaded it on both ends and the leaf armor works, thanks
