### ISSUE TITLE
Dyed Leaf armor reverts back to green 1.20.1 

### ISSUE THREAD

**Issue by Hukenon** [Glitchfiend/ToughAsNails#849]
### What's the issue you encountered?

When dying the leaf armor, it reverts back to default green the moment it's equipped. 

### How can the issue be reproduced?

Dye leaf armor then equip it.

### Mod Version

9.0.0.96

### Additional information

I don't see the 1.20.1 option, I hope this is fine.

**Comment by Forstride** [comment]
We don't support 1.20.1 anymore, but this is "intended", as leaf armor's biome coloring can only work by acting as dyeable armor in the first place.

**Comment by Hukenon** [comment]
Oh I see, I should've thought of that tbh. Thanks
