### ISSUE TITLE
[Suggestion] Snow in plains biome

### ISSUE THREAD

**Issue by LiEyWe** [Glitchfiend/ToughAsNails#85]
As the title says, it'd be cool to have snow in plains biomes during the winter.

**Comment by Forstride** [comment]
Snow appears at biomes with a temperature of 0.7 and below.  Plains have a temperature of 0.8, and I feel like they're just too warm to get snow as far as realism/design goes.

**Comment by WolfieWaffle** [comment]
what if plains got sparse snow, like each block in the biome has a 1/x chance to be snowed on. Though now that I say it, it may be hard to code that. Not sure though, so I'll say it as an idea anyways.
