### ISSUE TITLE
compatibility 

### ISSUE THREAD

**Issue by goldrichman9Modded** [Glitchfiend/ToughAsNails#852]
### Overview

I think the temperature mechanic should be in other mods if you install them, like  ice and fire and create, framers delight, etc

### Why would this feature be useful?

too make compatibility  with more mod when installing them with this mod

**Comment by Forstride** [comment]
Mods need to add compatibility on their own, which is entirely feasible with our block/item tags.  We can't maintain compatibility for a million different mods ourselves.
