### ISSUE TITLE
1.21 Crashma Report \\  Water Purifier

### ISSUE THREAD

**Issue by makumaku1974** [Glitchfiend/ToughAsNails#854]
### What's the issue you encountered?

Water Purifier.

### How can the issue be reproduced?

crashed the game after adding container  and charcoal.

### Logs

[latest.log](https://github.com/user-attachments/files/15984719/latest.log)

### Mod Version

10.0.0.3

### Additional information

[crash-2024-06-26_16.18.25-server.txt](https://github.com/user-attachments/files/15984728/crash-2024-06-26_16.18.25-server.txt)

**Comment by makumaku1974** [comment]
![Screenshot 2024-06-26 205736](https://github.com/Glitchfiend/ToughAsNails/assets/129804277/8f314a3d-d292-4a55-9015-b87cc03dcfa1)

**Comment by Adubbz** [comment]
This looks like an issue with Polymorph

**Comment by makumaku1974** [comment]
> This looks like an issue with Polymorph

should I report this to polymorph as well?
