### ISSUE TITLE
ConfigValue for ThermoregulatorScreen height/position

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Glitchfiend/ToughAsNails#855]
### Overview

Add config values to allow the position of the ThermoregulatorScreen (ergo the orb) to be able to be lowered/positioned.

### Why would this feature be useful?

This would allow modpacks that alter/add/remove other bars to make them mesh together better.

Situation:
![CBfse1KLV72IhTme](https://github.com/Glitchfiend/ToughAsNails/assets/61988002/0995a409-e34e-4ed2-b689-c433fe0e11cc)

**Comment by Forstride** [comment]
1) The Thermoregulator is a block.  We call that the temperature orb.

2) There already is an option to move it in the client config.
