### ISSUE TITLE
Goofy Climatologist

### ISSUE THREAD

**Issue by HacoKavanah** [Glitchfiend/ToughAsNails#857]
### What's the issue you encountered?

![image](https://github.com/user-attachments/assets/7b720d2c-1661-4c4a-aa6f-bc1b8a108993)

### How can the issue be reproduced?

By making the name look less goofy and more the type that makes sense

### Mod Version

10.0.0.3

**Comment by Forstride** [comment]
This was already fixed.  You're not using the latest version for 1.21
