### ISSUE TITLE
Problems with enchanted warm armor.

### ISSUE THREAD

**Issue by Nayrd7** [Glitchfiend/ToughAsNails#859]
### What's the issue you encountered?

I have bug in Minecraft 1.12.2 with this mod (tough as nails):
If I use ordinary armor without enchantments, which is prescribed in the config as warming, then it will warm. However, if I enchant her, then my body temperature will drop as well, as if I don't have this armor on.

### How can the issue be reproduced?

Enchant ordinary warm armor and it will have no effect.

### Logs

N/A

### Mod Version

1.12.2

### Additional information

N/A

**Comment by Adubbz** [comment]
1.12.2 is no longer supported.

**Comment by Nayrd7** [comment]
> 1.12.2 is no longer supported.

Okay, then tell me how I can fix this problem.
