### ISSUE TITLE
about EntityPlayer.isWet()

### ISSUE THREAD

**Issue by bangbang93** [Glitchfiend/ToughAsNails#87]
Does this mod do anything with EntityPlayer.isWet() method?
I have a mod using this method to do some magic.But if I using my mod and ToughAsNails together ,isWet() will ignore raining but still work in water .
And even enderman wouldn't damage in rain.

**Comment by Forstride** [comment]
Yes.  It seems to be broken due to one of our ASM overrides.  There is [another issue](https://github.com/Glitchfiend/ToughAsNails/issues/78) for this though, so I'm closing this one.
