### ISSUE TITLE
Config option requests

### ISSUE THREAD

**Issue by Silvrus** [Glitchfiend/ToughAsNails#88]
Love the mod, really is making the UHS pack I'm working on unique. The goal of which is the world itself is what makes survival difficult, not overwhelming mobs. What I'd like, if possible, would be an option to adjust the season lengths, i.e. to make summer and winter longer than spring and fall, to give a larger sense of urgency during the milder seasons to prepare for the harsher ones.

Secondly, would it be possible to add a mechanic to account for extreme temperature change in a short timeframe? For example, suffering hyperthermia and jumping into ice water should cause shock, with some status effects. Don't think there's the reverse though as it takes longer for the body to warm up than cool off through external stimuli. Any thoughts would be appreciated, thank you and keep up the amazing work!

**Comment by Forstride** [comment]
https://github.com/Glitchfiend/ToughAsNails/issues/26

Keeping config stuff in that issue so there aren't duplicates
