### ISSUE TITLE
Temperature change for biomes and armor in the config.

### ISSUE THREAD

**Issue by FilkteZ** [Glitchfiend/ToughAsNails#889]
### Overview

For example, completely **remove** the heating of wool armor heating or make a **super cold** ice biome.

Maybe there is such a function, but I did not find it. I will be glad if they add it or tell **me** where it is, if it is available.

### Why would this feature be useful?

It will be useful in some **maps** or **modpacks**.

**Comment by Forstride** [comment]
This is already possible with datapacks.  You can find an example datapack in the pinned messages of the Tough As Nails channel on our Discord server: https://discord.gg/GyyzU6T
