### ISSUE TITLE
Trying to use the water purifier crashes in the latest version in 1.21.4

### ISSUE THREAD

**Issue by IHateGithub55** [Glitchfiend/ToughAsNails#895]
### What's the issue you encountered?

Using it at all, attempting to put anything into it, always crashes

### How can the issue be reproduced?

Using the item at all crashes the game

### Logs

sorry no logs just wanted to point it out as im the first person to...

### Mod Version

1.21.4-10.4.0.0

**Comment by IHateGithub55** [comment]
UPDATE: quick moving items is what crashes the game! (holding control and clicking). Manually placing the items in the slots does not appear to crash the game.

**Comment by IHateGithub55** [comment]
So what, it's not going to be fixed then? The item is still bugged if you shift click items into it, it will crash your game.

**Comment by Adubbz** [comment]
This was closed because it was fixed, what are you talking about? If you are still experiencing issues you need to provide logs using the latest version.

**Comment by IHateGithub55** [comment]
How was it fixed when the mod was not updated? I told you the problem was quick stacking items into the purifier causing a crash. If you manually drag items in, it won't crash.

**Comment by Adubbz** [comment]
Umm, yes it was updated. 10.4.0.1 exists now.

**Comment by Adubbz** [comment]
The actual problem here was that the NeoForge and Fabric versions were not uploaded to Modrinth automatically as they should have been. Curseforge was fine. I'd advise learning how GitHub works before claiming nothing has been done in future and acting with hostility - I would've fixed the above immediately if informed properly.

**Comment by IHateGithub55** [comment]
Well as you can tell from my username, i hate github
