### ISSUE TITLE
Suggest Canteens should use NBT, not Damage

### ISSUE THREAD

**Issue by capnkirok** [Glitchfiend/ToughAsNails#91]
Hey Glitchfiend. Love the mod and the mechanic changes. Had a couple of Inventory Pets players notice that the Anvil Pet from my mod repairs Canteens and in the process removes all of the water. Might want to look into using NBT Data instead of Damage for determining your water level. I used the same thing for Inventory Pets, and ran into trouble with other mods that do other things with damage (e.g., EE2, OreSpawn, many others). Only drawback is that you don't get the durability bar, but that can be easily reproduced.

I'm going to put a workaround in Inventory Pets, this is just a suggestion so you avoid trouble down the road.

**Comment by WolfieWaffle** [comment]
Personally I'd suggest a blacklist for inventory pets repair items. Would be much simpler to implement and fix the EE2 mods and well.

**Comment by capnkirok** [comment]
Just saw this response @WolfieWaffle. Honestly, both should happen. Canteens should not use damage (esp. in reverse order, where fully repaired = empty canteen, as compared with the way most items work). And Anvil Pet could use a blacklist, sure.

**Comment by Adubbz** [comment]
This specific issue with repairs should be addressed by https://github.com/Glitchfiend/ToughAsNails/commit/ed42f345b335d9e22c2f3a7210245ed8b1fb428b .
