### ISSUE TITLE
Crops not affected by winter

### ISSUE THREAD

**Issue by Silvrus** [Glitchfiend/ToughAsNails#92]
Crops dying in winter seem to only be for vanilla crops, as Pam's crops are not being affected. Please add white/blacklist config options, or have the mod recognize crops other than vanilla. Thank you.

**Comment by Ramireztime** [comment]
Mods need to implement "IDecayableCrop" from the TAN api afaik. I've mentioned it to Pam and she does plan to add support for her crops in a future release of Harvestcraft.

**Comment by Forstride** [comment]
Yeah, like Ramireztime said, this is something other mods can implement with our API once it's publicly available.  As for a whitelist, we planned to do something like that (https://github.com/Glitchfiend/ToughAsNails/issues/26), so I'm going to close this issue so it's not a duplicate
