### ISSUE TITLE
[Suggestion/Request] Air Conditioning Unit (Image Attached)

### ISSUE THREAD

**Issue by praetoras** [Glitchfiend/ToughAsNails#95]
Hello again! Sorry about creating yet another issue, and thank you for the time looking at my proposal. I'll make it brief.

**New Block:** Air Conditioning Unit

**Crafting Recipe:**

![crafting proposal](https://cloud.githubusercontent.com/assets/17558082/17355284/08ac1738-5915-11e6-8ede-27dd331ea21c.png)

**Description:** Powered by Redstone, end-game item similar to the heating and cooling coils, except this block keeps an enclosure held at a medium temperature, neither getting too hot nor too cold. This is useful to keep a long-term base stable.

**Reason for Proposal:** I love the mod, and I love the temperature system. However, I found that even with the heating and cooling coils in my base, I constantly have to turn them on or off because they would over-heat/cool depending on the situation. I would be working on a project and suddenly taking damage because things were getting too hot/cold because they were either turned off or had been running too long.

Creating a "sensor" to control it through redstone seems like it'd be more work for you guys than just creating a block that's very code-similar to the coils, except it sets the temperature to a stable medium regardless of outside influences instead of heating or cooling. The recipe above is just a proposal. If you want to make it harder to craft, feel free to.

I just feel this would be a worthwhile and logical addition, while not nullifying the effect of the mod so that when they go out a-wandering they still have to make use of the mechanics.

**Comment by praetoras** [comment]
I would still love to see this block added if possible. I really enjoy the survival aspect and seasons of this mod and hope to include it in my modpack in the future. I'll definitely be watching to see where you take development of this!

Other thoughts on the possible implementation: I saw another thread where fuel was required for running the coils. Requiring fuel and redstone power for the air conditioning unit might be a good trade-off for the convenience as well.

**Comment by Forstride** [comment]
I think the better way to go would be to add a temperature sensor block (Similar to daylight/season sensors), that way I don't just add the air conditioning unit for the sake of it.  Temperature sensors could be used for a lot more than just this as well.

**Comment by praetoras** [comment]
I'd be totally up for that. My only concern was that with a temperature sensor block, if you have a setup where you're trying to keep the temperature stable, it would be constantly turning on/off either the heater or the cooler and I wasn't sure how heavy that would be on a server. I figured an air conditioning unit would use less server resources ultimately.
