### ISSUE TITLE
[Suggestion] Reset Hearths when dying!

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#96]
Hello! First of all thanks for doing this its a great mod!

I think it would be nice if you guys could make a config or something that allow us to lose crafted hearths on death. Maybe others do too?

Thanks again!

**Comment by Forstride** [comment]
That would make sense.  Don't want it to be on by default, but yeah, good suggestion

**Comment by Forstride** [comment]
I've removed the Lowered Starting Health feature, so this issue can be closed.
