### ISSUE TITLE
Wool and Slime armor doesn't seem to have a texture

### ISSUE THREAD

**Issue by erindal** [Glitchfiend/ToughAsNails#99]
Forge build 2064, TAN Build 1.0.11.

![image](https://cloud.githubusercontent.com/assets/12499779/17652992/19893768-625a-11e6-8d2d-37cf54d6d87c.png)

**Comment by Forstride** [comment]
Works fine for me

![2016-08-14_21 04 07](https://cloud.githubusercontent.com/assets/1512908/17653376/aa4b7d26-6262-11e6-81a2-a090beb843e7.png)

Some other mod might be conflicting, so we'll need more details, like what mods you have installed, FML logs, etc.

**Comment by erindal** [comment]
[fml-client-latest.txt](https://github.com/Glitchfiend/ToughAsNails/files/417411/fml-client-latest.txt)

[HCI-TANBUGNOSCRIPTS-0.zip](https://github.com/Glitchfiend/ToughAsNails/files/417412/HCI-TANBUGNOSCRIPTS-0.zip)

First file is the fml log, second file is for the Curse Launcher while I get a mod list together.

**Comment by erindal** [comment]
https://docs.google.com/spreadsheets/d/1Ky-OvAv_cZ-scvcGDCcUNu_Z71wag22zQORfnO-IdiY/edit?usp=sharing

**Comment by Forstride** [comment]
Hmm, really not sure.  Do you have any other mods with custom armor installed, and do they work?

**Comment by erindal** [comment]
"Build 2065:
    LexManos: Fix armors rendering badly. Closes #3196"

I will test this and confirm this asap.

**Comment by erindal** [comment]
Confirmed...updating forge fixes it.
